### ISSUE TITLE
 'LocalTimezone' object has no attribute 'localize'

### ISSUE THREAD

**Issue by bobemoe** [graphite-project/graphite-web#1019]
I am getting this error when trying to render a date range defined by absolute date/times. If I use relative (from=-24h and until=now or similar) then the graph renders fine.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 54, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File "/opt/graphite/webapp/graphite/render/views.py", line 301, in parseOptions
    untilTime = parseATTime(queryParams['until'], tzinfo, now)
  File "/opt/graphite/webapp/graphite/render/attime.py", line 41, in parseATTime
    return tzinfo.localize(datetime.strptime(s,'%H:%M%Y%m%d'), daylight)
AttributeError: 'LocalTimezone' object has no attribute 'localize'
```

Graphite version 0.9.x installed from git today.
Django version 1.7.1.

Timezone in local_settings.py is set to 
`TIME_ZONE = 'Europe/London'`

The only thing I am doing slightly different than normal is using Waitress rather than Apache.  I am using the /opt/graphite/conf/graphite.wsgi.example with the following lines added at the bottom:

```
from waitress import serve
serve(application, host='0.0.0.0', port=8080)
```

**Comment by billowqiu** [comment]
I have the same problem when use uwsgi with graphite.wsgi.example.
But start the app with run-graphite-devel-server.py is ok, even don't install pytz.

**Comment by deniszh** [comment]
@billowqiu - yes, that will also work, but please note that development server is for development only, and not for production load.

**Comment by stttt2003pk** [comment]
@deniszh @billowqiu but anybody know how to fix this on Centos7
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 56, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File "/opt/graphite/webapp/graphite/render/views.py", line 318, in parseOptions
    fromTime = parseATTime('-1d', tzinfo, now)
  File "/opt/graphite/webapp/graphite/render/attime.py", line 48, in parseATTime
    return tzinfo.normalize(parseTimeReference(ref).astimezone(tzinfo) + parseTimeOffset(offset))
AttributeError: 'LocalTimezone' object has no attribute 'normalize'

if i try to get the render

**Comment by billowqiu** [comment]
@stttt2003pk install pytz?
