### ISSUE TITLE
constantLine should work with diffSeries

### ISSUE THREAD

**Issue by caipre** [graphite-project/graphite-web#1020]
According to #415, diffSeries doesn't support constant values. The `constantLine` function returns a series though, so it should work. I'm seeing this backtrace with the following target on 0.9.12.

`diffSeries(constantLine(2), constantLine(1))`

```
Traceback (most recent call last):
  File "python2.7/site-packages/Django-1.4.12-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/views.py", line 110, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/functions.py", line 248, in diffSeries
    name = "diffSeries(%s)" % formatPathExpressions(seriesList)
  File "python2.7/site-packages/graphite_web-0.9.12.1-py2.7.egg/graphite/render/functions.py", line 131, in formatPathExpressions
    [pathExpressions.append(s.pathExpression) for s in seriesList if not pathExpressions.count(s.pathExpression)]
AttributeError: 'TimeSeries' object has no attribute 'pathExpression'
```

The line numbers may be slightly off from 0.9.12 since I have a few patches of my own, but I don't think that they would cause this.

**Comment by g76r** [comment]
Since constantLine() produces a TimeSeries with pathExpression (I suppose thanks to this commit: c1a04ec5), this exception no longer occurs. However diffSeries still does not really work with constantLine since constantLine only produces 2 or 3 values (2 with current master, 3 with #645) and diffSeries produces null values whenever one of the diffed series is null.

IMHO diffSeries or constantLine should not be fixed to work together, but one of this option should rather be choosen:
- You can use offset with negative value instead. Example: offset(my.metric,-1). Or event diffSeries and then offset. Example: offset(diffSeries(my.{a,b}.metrics),-1)
- Or diffSeries should be modified to accept either series or constants as parameters, see issues #415 and #626. This would be more user-friendly, but, IMHO, not so easy to do.

I would propose to close this issue since either using offset or merging with #626 solves it.

**Comment by caipre** [comment]
Agreed, offset seems fine.

**Comment by vlad-vintila-hs** [comment]
In case someone gets here and wants to subtract a metric from a constant, something which offset doesn't support directly:
`offset(scale(<metric>,-1),<constant>)`
