### ISSUE TITLE
Nested groupByNode fails

### ISSUE THREAD

**Issue by magicrobotmonkey** [graphite-project/graphite-web#1088]
Trying to nest groupByNode to get an average of disk usage per host:

```
groupByNode(groupByNode(collectd.compute.george*.disk.dm-*.disk_octets{write,read},4,"sumSeries"),2,"averageSeries")
```

Results in:

```

Traceback (most recent call last):
  File "/opt/graphite/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 113, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 2358, in groupByNode
    key = series.name.split(".")[nodeNum]
IndexError: list index out of range

```

**Comment by magicrobotmonkey** [comment]
On further inspection, it seems there's no way this can work, as the first call just spits out the nodename rather than the absolute path to the metric.

**Comment by obfuscurity** [comment]
That sounds right, and I don't think it would make sense to include the absolute path since we're aggregating anyways. Ok to close?
