### ISSUE TITLE
Graphite crash on smartSummarize

### ISSUE THREAD

**Issue by ricardmestre** [graphite-project/graphite-web#1142]
Hi everyone!
I'm testing the smartSummarize function working over the lastest master  65b395648b8e814404023a411904871b57b257a7, and I'm getting the following crash on this query:

http://graphite_server/render/?format=json&target=smartSummarize(testSmartSummarize,"1h")

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 111, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 7, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 2896, in smartSummarize
    newSeries = evaluateTarget(requestContext, series.pathExpression)[0]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 7, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return fetchData(requestContext, tokens.pathExpression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 94, in fetchData
    startTime = int( epoch( requestContext['startTime'] ) )
  File "/opt/graphite/webapp/graphite/util.py", line 60, in epoch
    return calendar.timegm(dt.astimezone(pytz.utc).timetuple())
ValueError: astimezone() cannot be applied to a naive datetime
```

The summarize function is working properly:

![image](https://cloud.githubusercontent.com/assets/8693668/6125480/be0dba4e-b116-11e4-97e6-d20047a35957.png)

What I'm doing wrong?

Thank you!

**Comment by checkmypi** [comment]
+1

**Comment by loisaidasam** [comment]
Similar issue: https://github.com/brutasse/graphite-api/issues/51

**Comment by Dieterbe** [comment]
I think this can be closed.  with an old graphite server, i was getting:
```
File &#34;/opt/graphite/webapp/graphite/render/datalib.py&#34;, line 96, in fetchData&#10;
    startTime = int( epoch( requestContext['startTime'] ) )&#10;  
File &#34;/opt/graphite/webapp/graphite/util.py&#34;, line 60, in epoch&#10;
    return calendar.timegm(dt.astimezone(pytz.utc).timetuple())&#10;
ValueError: astimezone() cannot be applied to a naive datetime&#10;&#10;</pre>&#10;</div>&#10;&#10;</center>&#10;
```			

but using graphite 1.0.2, it works.
