### ISSUE TITLE
Could not import settings 'graphite.settings'

### ISSUE THREAD

**Issue by th936** [graphite-project/graphite-web#1153]
I have some problems when I try to install graphite.

I have set up carbon, whisper, ceres and graphite-web.  And copy the manage.py to /opt/graphite/webapp/graphite from source package.

But when I excute 'python manage.py syncdb' showed error as below, I'm not sure what caused this. Please help to.

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/lib/python2.6/site-packages/django/core/management/commands/syncdb.py", line 8, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/usr/lib/python2.6/site-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/usr/lib/python2.6/site-packages/django/db/__init__.py", line 11, in <module>
    if DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/usr/lib/python2.6/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 95, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'graphite.settings' (Is it on sys.path?): No module named graphite.settings

**Comment by brutasse** [comment]
You don't need manage.py. Please try:

`PYTHONPATH=/opt/graphite/webapp django-admin.py syncdb`

**Comment by th936** [comment]
Thanks!  It works fine when I try to execute as below:
PYTHONPATH=/opt/graphite/webapp /usr/lib/python2.6/site-packages/django/bin/django-admin.py syncdb --settings=graphite.settings
