### ISSUE TITLE
django-tagging version problem in requirements.txt

### ISSUE THREAD

**Issue by lifenglifeng001** [graphite-project/graphite-web#1219]
The [django-tagging version](https://github.com/graphite-project/graphite-web/blob/master/requirements.txt#L43) in requirements.txt error in django1.7 and django1.8.

```
Traceback (most recent call last):
  File "/home/lf/.virtualenvs/graphite/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/tagging/admin.py", line 3, in <module>
    from tagging.forms import TagAdminForm
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/tagging/forms.py", line 11, in <module>
    class TagAdminForm(forms.ModelForm):
  File "/home/lf/.virtualenvs/graphite/local/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagAdminForm needs updating.
```
This error is fixed in a newer version of django-tagging.

Should it be changed.
From:

    django-tagging==0.3.1
To:

    django-tagging==0.3.4
or

    django-tagging

**Comment by swills** [comment]
Also see #326 though I may have been wrong about django-tagging not working with django 1.8.

**Comment by makefu** [comment]
i stumbled upon the same issue, installing the most recent version of django-tagging worked.

**Comment by obfuscurity** [comment]
The version of django-tagging pinned in 0.9.x ([0.3.1](https://github.com/graphite-project/graphite-web/blob/0.9.x/requirements.txt#L36)) works fine with the version of Django pinned ([1.4](https://github.com/graphite-project/graphite-web/blob/0.9.x/requirements.txt#L32)). If you need to run a newer version of Django then you may need to update django-tagging, but it's not something that's currently mismatched as found in the source tree.
