### ISSUE TITLE
grep function is not found

### ISSUE THREAD

**Issue by ghost** [graphite-project/graphite-web#1230]
I am seeing an error with graphite-web in version `0.10.0_alpha` when I try to use `grep` function :

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 122, in renderView
    response = HttpResponse(content_type='text/csv')
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    if type(result) is TimeSeries:
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    arglist.update(dict([(kwarg.argname, evaluateTokens(requestContext, kwarg.args[0])) for kwarg in tokens.template.kwargs]))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 27, in evaluateTokens
KeyError: u'grep'
```

My serie list is correct and work find without function or with the function exclude. I don't thnik a use the function incorrectly because is only `grep(metric, pattern)` and with signle or double quote for the pattern is the same issue. 

What could the issue be ?

**Comment by brutasse** [comment]
A fix was committed for this issue, you should only have to update your graphite installation to the latest master: https://github.com/graphite-project/graphite-web/commit/9f73f67c77d17013446b4a2f0231b5dbba7a7da0

**Comment by fmargelidon** [comment]
I had check my file /opt/graphite/webapp/graphite/render/functions.py and I have already this line. This is why I don't understand the reason of my issue.
