### ISSUE TITLE
Django 1.8 breaks with django-tagging <= 0.3.1

### ISSUE THREAD

**Issue by SEJeff** [graphite-project/graphite-web#1249]
```python
$ ./manage.py test --settings=tests.settings
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/tagging/admin.py", line 4, in <module>
    from .forms import TagAdminForm
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/tagging/forms.py", line 12, in <module>
    class TagAdminForm(forms.ModelForm):
  File "/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagAdminForm needs updating.
Removed temporary directory: /tmp/graphite-test-NNX8Fg
```

From `pip install -r requirements.txt`

```bash
(ve)[jschroeder@chit-jsl3 webapp]$ pip freeze | egrep 'Django|tagging'
Django==1.8.2
django-tagging==0.3.1
```

Now when updating django-tagging to `0.3.2` 

```python
(ve)[jschroeder@chit-jsl3 webapp]$ ./manage.py test --settings=tests.settings
Creating test database for alias 'default'...
/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

./home/jschroeder/git/graphite-web/webapp/graphite/events/views.py:61: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  if 'jsonp' in request.REQUEST:

/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/core/handlers/wsgi.py:126: RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)

/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Event.when received a naive datetime (1970-01-01 01:00:00) while time zone support is active.
  RuntimeWarning)

/home/jschroeder/git/graphite-web/ve/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Event.when received a naive datetime (1970-01-01 00:00:00) while time zone support is active.
  RuntimeWarning)

.................................../home/jschroeder/git/graphite-web/webapp/graphite/render/views.py:224: RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  queryParams = request.REQUEST

...........
----------------------------------------------------------------------
Ran 47 tests in 0.112s

OK
Destroying test database for alias 'default'...
Removed temporary directory: /tmp/graphite-test-rpYAXE
```

Seems to be good to go!

```bash
$ pip freeze | egrep 'Django|tagging'
Django==1.8.2
django-tagging==0.3.3
```

**Comment by SEJeff** [comment]
The upstream changelog shows >= django-tagging 0.3.5 supports Django 1.8 officially.
