### ISSUE TITLE
/static configuration broken when storage installed in different location

### ISSUE THREAD

**Issue by yzehani** [graphite-project/graphite-web#1363]
Summary:
When executing django-admin collectstatic command I get error: OSError: [Errno 2] No such file or directory: '/opt/graphite/webapp/content'

It should have looked at /opt/**data**/graphite/webapp/content instead

I added a debug print line in graphite.settings to indicated that the script is not picking the location of the content folder from the storage directory but rather from the default directory.

(The documentation is not clear as to what parameters should be applied when we decide to put the storage files and DB in a non default location)

Thanks for helping to resolve this issue

```
root@graphite-001:/opt/data/graphite# django-admin collectstatic --pythonpath=/opt/graphite/webapp --noinput --settings=graphite.settings 

>>>>>>>>>>>>>>
STATICFILES_DIRS is in: ('/opt/graphite/webapp/content',)
>>>>>>>>>>>>>>

Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 167, in handle_noargs
    collected = self.collect()
  File "/usr/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 102, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/usr/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 106, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/usr/lib/python2.7/dist-packages/django/contrib/staticfiles/utils.py", line 25, in get_files
    directories, files = storage.listdir(location)
  File "/usr/lib/python2.7/dist-packages/django/core/files/storage.py", line 249, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/opt/graphite/webapp/content'
```

**Comment by deniszh** [comment]
IIRC /opt/graphite prefix unfortunately hardcoded and you can't easily change that. But maybe I'm wrong.

**Comment by yzehani** [comment]
I was able to get through this by changing STATICFILES_DIRS in settings.py

#STATICFILES_DIRS = (
#    join(WEBAPP_DIR, 'content'),
#)
STATICFILES_DIRS = (
        join("/opt/data/graphite/webapp", 'content'),
)

The problem comes apparently from hard coding the value of WEBAPP_DIR in:
# Filesystem layout
WEB_DIR = dirname( abspath(__file__) )
WEBAPP_DIR = dirname(WEB_DIR)
GRAPHITE_ROOT = dirname(WEBAPP_DIR)

**An easy workable solution could be to be able to set WEBAPP_DIR in local_settings.py**
settings.py should change to pickup that setting.

**Comment by brutasse** [comment]
> An easy workable solution could be to be able to set WEBAPP_DIR in local_settings.py

That's already the case, at least in master. Which version are you using?

**Comment by yzehani** [comment]
Yes, I'm using master.
local_settings.py doesn't have any reference to WEBAPP_DIR
and even if so, it would be clobbered by settings.by
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/local_settings.py.example

**Comment by brutasse** [comment]
settigngs.py defines WEBAPP_DIR *then* imports local_settings so it really should be taken into account when overridden in local_settings.

**Comment by yzehani** [comment]
Ok, then I suggest adding a commented line defining WEBAPP_DIR right under #STATIC_ROOT
in local_settings.py.example to address that and close this issue.
Thanks for your support.
