### ISSUE TITLE
 error TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1399]
This error is thrown from some days ago.

Can anybody help us to locate the origin of the error ?

Trank you very much

```
Tue Nov 17 14:34:37 2015 :: Exception encountered in <GET http://graphite_pro/render/?width=586&height=308&_salt=1447767060.269&target=carbon.agents.cche-wr*.cpuUsage>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 141, in fetchData
    raise Exception("Failed after %i retry! See: %s" % (settings.MAX_FETCH_RETRIES, e))
Exception: Failed after 2 retry! See: 'float' object is not iterable
Tue Nov 17 14:35:05 2015 :: Got an exception when fetching data! See: 'float' object is not iterable Will do it again! Run: 1 of 2
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 136, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 99, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Tue Nov 17 14:35:05 2015 :: Failed after 2 retry! See: 'float' object is not iterable
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 136, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 99, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
```

**Comment by deniszh** [comment]
https://github.com/graphite-project/graphite-web/issues/1156#issuecomment-144720336

**Comment by toni-moreno** [comment]
Hi @deniszh I'm working with master 8710ff76f0b4571481d295d997a83e4c895dd092 ( from June) the fix you show me was merged on February. 

this error happens mainly querying carbon metrics when carbon processes are heavily loaded , you can see https://github.com/graphite-project/carbon/issues/479 

```` 
grep "Exception encountered in"  /logs/apps/graphite/webapp/exception.log


Mon Dec 07 15:39:43 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
Mon Dec 07 15:42:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.memUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-dist%2A.memUsage&format=pickle&local=1&noCache=1&from=1449477746&until=1449499286>
Mon Dec 07 15:42:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449477747&until=1449499287>
Mon Dec 07 15:49:01 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.memUsage&format=pickle&local=1&noCache=1&from=1449478141&until=1449499681>
Mon Dec 07 15:49:02 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449478142&until=1449499682>
Mon Dec 07 15:49:03 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.relays.graphitehost01%2A.destinations.%2A.relayMaxQueueLength&format=pickle&local=1&noCache=1&from=1449478143&until=1449499683>
Mon Dec 07 15:51:46 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
Mon Dec 07 16:23:40 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480220&until=1449501760>
Mon Dec 07 16:23:41 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480221&until=1449501761>
Mon Dec 07 16:23:42 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.errors&format=pickle&local=1&noCache=1&from=1449480221&until=1449501761>
Mon Dec 07 16:25:26 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480326&until=1449501866>
Mon Dec 07 16:25:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-dist%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480326&until=1449501866>
Mon Dec 07 16:25:27 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449480327&until=1449501867>
Mon Dec 07 16:25:28 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.overflow&format=pickle&local=1&noCache=1&from=1449480327&until=1449501867>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449480419&until=1449501959>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.pointsPerUpdate&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:27:00 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480420&until=1449501960>
Mon Dec 07 16:34:36 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449480876&until=1449502416>
Mon Dec 07 16:34:37 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449480877&until=1449502417>
Mon Dec 07 16:34:38 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449480878&until=1449502418>
Mon Dec 07 16:34:38 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449480878&until=1449502418>
Mon Dec 07 16:37:12 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449481032&until=1449502572>
Mon Dec 07 16:49:47 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:47 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:48 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449481787&until=1449503327>
Mon Dec 07 16:49:48 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449481788&until=1449503328>
Mon Dec 07 17:06:01 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449482761&until=1449504301>
Mon Dec 07 17:07:06 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queues&format=pickle&local=1&noCache=1&from=1449482826&until=1449504366>
Mon Dec 07 17:07:06 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449482826&until=1449504366>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449483450&until=1449504990>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:17:31 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.avgUpdateTime&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:17:32 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.agents.graphitehost01%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449483452&until=1449504992>
Mon Dec 07 17:17:32 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449483451&until=1449504991>
Mon Dec 07 17:33:57 2015 :: Exception encountered in <GET http://10.16.172.192/render?from=-15min&format=raw&target=carbon.agents.graphitehost01-wr07a.cpuUsage>
```

**Comment by toni-moreno** [comment]
hi @deniszh , what I can do to debug this error code on the graphite-web or carbon code? . It seems like self made metrics "carbon.*.*.*" sometimes (randomly) are not in correct format.


````
# awk '{ if ($9 == 500) print $0 }' /logs/apps/graphite/webapp/access.log`
..
..
10.16.172.147 - - [10/Dec/2015:11:47:18 +0100] "GET /render/?target=carbon.%2A.graphitehost01%2A.cache.size&format=pickle&local=1&noCache=1&from=1449740838&until=1449744438 HTTP/1.1" 500 1637 "-" "-" 86419
10.16.172.147 - - [10/Dec/2015:11:49:38 +0100] "GET /render/?target=carbon.relays.graphitehost01-dist07.destinations.%2A.relayMaxQueueLength&format=pickle&local=1&noCache=1&from=1449740978&until=1449744578 HTTP/1.1" 500 1637 "-" "-" 180795
10.16.172.147 - - [10/Dec/2015:11:51:08 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449741068&until=1449744668 HTTP/1.1" 500 1637 "-" "-" 79747
10.16.172.147 - - [10/Dec/2015:11:51:09 +0100] "GET /render/?target=carbon.%2A.graphitehost01%2A.cache.size&format=pickle&local=1&noCache=1&from=1449741069&until=1449744669 HTTP/1.1" 500 1637 "-" "-" 92099
10.16.172.147 - - [10/Dec/2015:11:51:09 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cache.queries&format=pickle&local=1&noCache=1&from=1449741069&until=1449744669 HTTP/1.1" 500 1637 "-" "-" 77749
10.16.172.147 - - [10/Dec/2015:11:51:20 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449741080&until=1449744680 HTTP/1.1" 500 1637 "-" "-" 68884
10.16.172.147 - - [10/Dec/2015:11:52:05 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449741125&until=1449744725 HTTP/1.1" 500 1637 "-" "-" 34663
10.16.172.147 - - [10/Dec/2015:11:52:09 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449741129&until=1449744729 HTTP/1.1" 500 1637 "-" "-" 38939
10.16.172.147 - - [10/Dec/2015:11:52:10 +0100] "GET /render/?target=carbon.%2A.graphitehost01%2A.creates&format=pickle&local=1&noCache=1&from=1449741130&until=1449744730 HTTP/1.1" 500 1637 "-" "-" 42131
10.16.172.147 - - [10/Dec/2015:11:53:15 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.cpuUsage&format=pickle&local=1&noCache=1&from=1449741195&until=1449744795 HTTP/1.1" 500 1637 "-" "-" 86375
10.16.172.147 - - [10/Dec/2015:11:53:15 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.memUsage&format=pickle&local=1&noCache=1&from=1449741195&until=1449744795 HTTP/1.1" 500 1637 "-" "-" 69825
10.16.172.147 - - [10/Dec/2015:11:53:15 +0100] "GET /render/?target=carbon.agents.graphitehost01%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1449741195&until=1449744795 HTTP/1.1" 500 1637 "-" "-" 42753
10.16.172.147 - - [10/Dec/2015:11:53:16 +0100] "GET /render/?target=carbon.relays.graphitehost01-dist07.destinations.%2A.relayMaxQueueLength&format=pickle&local=1&noCache=1&from=1449741196&until=1449744796 HTTP/1.1" 500 1637 "-" "-" 73782
..
..
```

I've tried to force with different render format  ( png/json) but the error is not dependent on the format.

And always  with this stacktrace.

```` 
Thu Dec 10 12:00:55 2015 :: Exception encountered in <GET http://graphite/render/?width=586&height=308&_salt=1449745256.475&target=carbon.agents.graphitehost01-wr07b.cpuUsage&target=carbon.agents.graphitehost01-wr07a.cpuUsage&target=carbon.agents.graphitehost01-wr07c.cpuUsage&target=carbon.agents.graphitehost01-wr07d.cpuUsage&target=carbon.agents.graphitehost01-wr07e.cpuUsage>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 141, in fetchData
    raise Exception("Failed after %i retry! See: %s" % (settings.MAX_FETCH_RETRIES, e))
Exception: Failed after 2 retry! See: 'float' object is not iterable
```

**Comment by toni-moreno** [comment]
Thank you very much @mleinart  for this patch I will apply ASAP to get more information that can help us to locate the origin of this exception.

**Comment by toni-moreno** [comment]
Hi @mleinart , after apply the patch and reproducte the error, this is the exception stacktrace. ( it seems like something wrong in the path isn't it?)

```
Mon Dec 14 09:30:09 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.metricsReceived&format=pickle&local=1&noCache=1&from=1450060209&until=1450081689>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 147, in fetchData
    (retries, settings.MAX_FETCH_RETRIES), format_exc())
TypeError: not enough arguments for format string
```

**Comment by toni-moreno** [comment]
Hi @mleinart after change this line

```
(retries, settings.MAX_FETCH_RETRIES), format_exc())
```

by this other:

````
(retries, settings.MAX_FETCH_RETRIES, format_exc()))
```` 

I could see the complete exception and this is the output



````
Wed Dec 16 15:05:06 2015 :: Got an exception when fetching data! Try: 1 of 2. Root cause:
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 138, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 101, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 138, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 101, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Wed Dec 16 15:05:06 2015 :: Failed after 2 retry! Root cause:
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 138, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 101, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 138, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 101, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Wed Dec 16 15:05:06 2015 :: Exception encountered in <GET http://10.16.172.192/render/?target=carbon.%2A.graphitehost01-wr%2A.cache.overflow&format=pickle&local=1&n                                                                             oCache=1&from=1450101905&until=1450274645>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 144, in fetchData
    raise e
TypeError: 'float' object is not iterable
```` 

There is enough information ?

**Comment by mleinart** [comment]
Yeah, the stacktrace points to the issue fixed via #1122. Are you sure you have that patch applied?

To fix this you'll either need to apply the workaround to graphite-web: https://github.com/graphite-project/graphite-web/pull/1122.patch 
or this fix to carbon: https://github.com/graphite-project/carbon/pull/496.patch
(or update either to the latest master)

**Comment by toni-moreno** [comment]
Hi @mleinart , as you can see in the image , the patch is applied in the file /opt/graphite/webapp/graphite/readers.py on the affected server.

![image](https://cloud.githubusercontent.com/assets/5883405/11892290/f7e5f02a-a566-11e5-8e64-16c095b09cc6.png)

The exception ONLY affect to carbon metrics but not always sometimes happens and sometimes not. The exception seems happens usually when  carbon-caches has I/O heavy load and number of cached points are growing, it happens 20 or 30 times every day.

**Comment by toni-moreno** [comment]
Hi @mleinart I'm still getting errors only from carbon metrics (as you can see in the next screenshot) And only when there is heavy IO in the system (you can say I/O wait has grown until 50% last 2 hours) , all the other stored metrics ( system/apache/etc) are got  from the same carbon instances and all ok.

It's something annoying when trying to check graphite/carbon health in our systems.

![image](https://cloud.githubusercontent.com/assets/5883405/12389506/8205a36a-bdd9-11e5-9306-23477c4c86d2.png)

There is any other way to debug this error?

```
Mon Jan 18 11:46:31 2016 :: Exception encountered in <GET http://graphite/render?from=-15min&format=raw&target=carbon.agents.graphitehost-wr05a.cpuUsage>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 141, in fetchData
    raise Exception("Failed after %i retry! See: %s" % (settings.MAX_FETCH_RETRIES, e))
Exception: Failed after 2 retry! See: 'float' object is not iterable
Mon Jan 18 11:51:31 2016 :: Got an exception when fetching data! See: 'float' object is not iterable Will do it again! Run: 1 of 2
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 136, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 99, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
Mon Jan 18 11:51:31 2016 :: Failed after 2 retry! See: 'float' object is not iterable
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 136, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 99, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    return self.reader.fetch(startTime, endTime)
  File "/opt/graphite/webapp/graphite/readers.py", line 177, in fetch
    for (timestamp, value) in cached_datapoints:
TypeError: 'float' object is not iterable
```

Thank you very much!

**Comment by toni-moreno** [comment]
As you can see @mleinart , after heavy load finishes carbon instances begin to report carbon metrics ok.

![image](https://cloud.githubusercontent.com/assets/5883405/12389831/a849fc04-bddb-11e5-9671-ced50958f556.png)

**Comment by toni-moreno** [comment]
Hi @mleinart  I have more information about when this problem happens.

Perhaps this issue should be placed better to a carbon issue, but in the meanwhile I would like to give you more feedback.

I've notice than query over carbon.agent.*. are failing over 2 cache  instances in the same moment than they begin to queue( both at the same time)..

![image](https://cloud.githubusercontent.com/assets/5883405/12507713/bd06ec8c-c0f7-11e5-94b3-8ec1d1c3a2dc.png)

I don't know why but queue size on both instances seems to reach over 40.000 metrics.

This is my configuration

````
[cache]
LOG_DIR=/logs/apps/graphite
STORAGE_DIR    = /tsdb/metrics/
USER=carbon
LOCAL_DATA_DIR = %(STORAGE_DIR)s/
ENABLE_LOGROTATE = False
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 50000
MAX_CREATES_PER_MINUTE = 500
LINE_RECEIVER_INTERFACE = 127.0.0.1
ENABLE_UDP_LISTENER = False
UDP_RECEIVER_INTERFACE = 127.0.0.1
UDP_RECEIVER_PORT = 2003
PICKLE_RECEIVER_INTERFACE = 127.0.0.1
USE_INSECURE_UNPICKLER = False
CACHE_QUERY_INTERFACE = 127.0.0.1
USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CACHE_HITS = False
WHISPER_AUTOFLUSH = False
LOG_LISTENER_CONN_SUCCESS = False

...
[cache:wr05x]
LINE_RECEIVER_PORT=2X13
PICKLE_RECEIVER_PORT = 2X14
CACHE_QUERY_PORT = 7X02
...
````

I will be grateful if you can help us on this issue. Thank you very much.
