### ISSUE TITLE
Problem with graphite.wsgi

### ISSUE THREAD

**Issue by moshe0076** [graphite-project/graphite-web#1462]
Hi,

I'm using the 0.9.15 branch on Amazon linux. I get the following error in the Apache error log:

```
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] Traceback (most recent call last):
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60]   File "/opt/graphite/conf/graphite.wsgi", line 9, in <module>
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60]     from django.utils.importlib import import_module
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] ImportError: No module named django.utils.importlib
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] mod_wsgi (pid=20061): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module., referer: http://10.0.0.68/
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] mod_wsgi (pid=20061): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'., referer: http://10.0.0.68/
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] Traceback (most recent call last):, referer: http://10.0.0.68/
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60]   File "/opt/graphite/conf/graphite.wsgi", line 9, in <module>, referer: http://10.0.0.68/
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60]     from django.utils.importlib import import_module, referer: http://10.0.0.68/
[Mon Feb 01 15:01:18 2016] [error] [client 192.168.10.60] ImportError: No module named django.utils.importlib, referer: http://10.0.0.68/
```

Thanks,

Moshe

**Comment by wawrzek** [comment]
Did you install all require dependences? (E.g. django)

**Comment by utkarshcmu** [comment]
+1

**Comment by obfuscurity** [comment]
Sounds like you're running an [incompatible version of Django](http://stackoverflow.com/a/32763639/2275058). Graphite-web 0.9.15 [requires Django 1.4](https://github.com/graphite-project/graphite-web/blob/0.9.15/requirements.txt#L32).
