### ISSUE TITLE
Problem 0.9.x, Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'

### ISSUE THREAD

**Issue by kennedyoliveira** [graphite-project/graphite-web#1472]
Hello everyone!

I'm trying to install the branch 0.9.x, but i'm getting the following error:

```
[Mon Feb 22 01:28:11.077967 2016] [wsgi:error] [pid 112:tid 140390432941952] mod_wsgi (pid=112): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Mon Feb 22 01:28:11.078024 2016] [wsgi:error] [pid 112:tid 140390432941952] mod_wsgi (pid=112): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Mon Feb 22 01:28:11.078069 2016] [wsgi:error] [pid 112:tid 140390432941952] Traceback (most recent call last):
[Mon Feb 22 01:28:11.078181 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/opt/graphite/conf/graphite.wsgi", line 32, in <module>
[Mon Feb 22 01:28:11.078316 2016] [wsgi:error] [pid 112:tid 140390432941952]     application = DjangoWhiteNoise(application)
[Mon Feb 22 01:28:11.078339 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/usr/local/lib/python2.7/site-packages/whitenoise/django.py", line 46, in __init__
[Mon Feb 22 01:28:11.080182 2016] [wsgi:error] [pid 112:tid 140390432941952]     self.configure_from_settings(settings)
[Mon Feb 22 01:28:11.080255 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/usr/local/lib/python2.7/site-packages/whitenoise/django.py", line 68, in configure_from_settings
[Mon Feb 22 01:28:11.080328 2016] [wsgi:error] [pid 112:tid 140390432941952]     getattr(settings, 'STATIC_URL', ''))
[Mon Feb 22 01:28:11.080350 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/usr/local/lib/python2.7/site-packages/whitenoise/django.py", line 36, in get_prefix_from_url
[Mon Feb 22 01:28:11.080383 2016] [wsgi:error] [pid 112:tid 140390432941952]     return format_prefix(urlparse.urlparse(url).path)
[Mon Feb 22 01:28:11.080403 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/usr/local/lib/python2.7/urlparse.py", line 143, in urlparse
[Mon Feb 22 01:28:11.080709 2016] [wsgi:error] [pid 112:tid 140390432941952]     tuple = urlsplit(url, scheme, allow_fragments)
[Mon Feb 22 01:28:11.080740 2016] [wsgi:error] [pid 112:tid 140390432941952]   File "/usr/local/lib/python2.7/urlparse.py", line 182, in urlsplit
[Mon Feb 22 01:28:11.080778 2016] [wsgi:error] [pid 112:tid 140390432941952]     i = url.find(':')
[Mon Feb 22 01:28:11.080810 2016] [wsgi:error] [pid 112:tid 140390432941952] AttributeError: 'NoneType' object has no attribute 'find'
```

I used all the example files, only editing virtual host for apache

```
# This needs to be in your server's config somewhere, probably
# the main httpd.conf
# NameVirtualHost *:80

# This line also needs to be in your server's config.
# LoadModule wsgi_module modules/mod_wsgi.so

# You need to manually edit this file to fit your needs.
# This configuration assumes the default installation prefix
# of /opt/graphite/, if you installed graphite somewhere else
# you will need to change all the occurances of /opt/graphite/
# in this file to your chosen install location.

<IfModule !wsgi_module.c>
    LoadModule wsgi_module modules/mod_wsgi.so
</IfModule>

# XXX You need to set this up!
# Read http://code.google.com/p/modwsgi/wiki/ConfigurationDirectives#WSGISocketPrefix
WSGISocketPrefix /var/run/apache2/wsgi

<VirtualHost *:80>
        ServerName graphite
        DocumentRoot "/opt/graphite/webapp"
        ErrorLog /opt/graphite/storage/log/webapp/error.log
        CustomLog /opt/graphite/storage/log/webapp/access.log common

        # I've found that an equal number of processes & threads tends
        # to show the best performance for Graphite (ymmv).
        WSGIDaemonProcess graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
        WSGIProcessGroup graphite
        WSGIApplicationGroup %{GLOBAL}
        WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite application-group=%{GLOBAL}

        # XXX You will need to create this file! There is a graphite.wsgi.example
        # file in this directory that you can safely use, just copy it to graphite.wgsi
        WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi

        # XXX To serve static files, either:
        # django-admin.py collectstatic --noinput --settings=graphite.settings
        # * Install the whitenoise Python package (pip install whitenoise)
        # or
        # * Collect static files in a directory by running:
        #     django-admin.py collectstatic --noinput --settings=graphite.settings
        #   And set an alias to serve static files with Apache:
        Alias /content/ /opt/graphite/webapp/content/
        <Location "/content/">
                SetHandler None
        </Location>

        # XXX In order for the django admin site media to work you
        # must change @DJANGO_ROOT@ to be the path to your django
        # installation, which is probably something like:
        # /usr/lib/python2.6/site-packages/django
        Alias /media/ "/usr/local/django/contrib/admin/media/"
        <Location "/media/">
                SetHandler None
        </Location>

        # The graphite.wsgi file has to be accessible by apache. It won't
        # be visible to clients because of the DocumentRoot though.
        <Directory /opt/graphite/conf/>
                Order deny,allow
                Allow from all
        </Directory>

</VirtualHost>
```

The script:
```
import os
import sys
sys.path.append('/opt/graphite/webapp')

try:
    from importlib import import_module
except ImportError:
    from django.utils.importlib import import_module

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'graphite.settings')  # noqa

from django.conf import settings
from django.core.wsgi import get_wsgi_application
from graphite.logger import log

application = get_wsgi_application()

try:
    import whitenoise
except ImportError:
    whitenoise = False
else:
    # WhiteNoise < 2.0.1 does not support Python 2.6
    if sys.version_info[:2] < (2, 7):
        whitenoise_version = tuple(map(
                int, getattr(whitenoise, '__version__', '0').split('.')))
        if whitenoise_version < (2, 0, 1):
            whitenoise = False

if whitenoise:
    from whitenoise.django import DjangoWhiteNoise
    application = DjangoWhiteNoise(application)
    prefix = "/".join((settings.URL_PREFIX.strip('/'), 'static'))
    for directory in settings.STATICFILES_DIRS:
        application.add_files(directory, prefix=prefix)
    for app_path in settings.INSTALLED_APPS:
        module = import_module(app_path)
        directory = os.path.join(os.path.dirname(module.__file__), 'static')
        if os.path.isdir(directory):
            application.add_files(directory, prefix=prefix)

# Initializing the search index can be very expensive. The import below
# ensures the index is preloaded before any requests are handed to the
# process.
log.info("graphite.wsgi - pid %d - reloading search index" % os.getpid())
import graphite.metrics.search  # noqa
```

I'm using python 2.7.11 on ubuntu 14 machine with apache 2.4.10.

Can someone help please?

**Comment by deniszh** [comment]
Could you please attach your local_settings.py ?

**Comment by kennedyoliveira** [comment]
Hi @deniszh, i used the example one, but did not changed any configuration, except for the secret key,
anyway, check below:

```
## Graphite local_settings.py
# Edit this file to customize the default Graphite webapp settings
#
# Additional customizations to Django settings can be added to this file as well

#####################################
# General Configuration #
#####################################
# Set this to a long, random unique string to use as a secret key for this
# install. This key is used for salting of hashes used in auth tokens,
# CRSF middleware, cookie storage, etc. This should be set identically among
# instances if used behind a load balancer.
SECRET_KEY = 'TESTING'

# In Django 1.5+ set this to the list of hosts your graphite instances is
# accessible as. See:
# https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-ALLOWED_HOSTS
#ALLOWED_HOSTS = [ '*' ]

# Set your local timezone (Django's default is America/Chicago)
# If your graphs appear to be offset by a couple hours then this probably
# needs to be explicitly set to your local timezone.
#TIME_ZONE = 'America/Los_Angeles'

# Override this to provide documentation specific to your Graphite deployment
#DOCUMENTATION_URL = "http://graphite.readthedocs.org/"

# Metric data and graphs are cached for one minute by default
#DEFAULT_CACHE_DURATION = 60

# Logging
#LOG_ROTATION = True
#LOG_ROTATION_COUNT = 1
#LOG_RENDERING_PERFORMANCE = True
#LOG_CACHE_PERFORMANCE = True

# Enable full debug page display on exceptions (Internal Server Error pages)
#DEBUG = True

# If using RRD files and rrdcached, set to the address or socket of the daemon
#FLUSHRRDCACHED = 'unix:/var/run/rrdcached.sock'

# This lists the memcached servers that will be used by this webapp.
# If you have a cluster of webapps you should ensure all of them
# have the *exact* same value for this setting. That will maximize cache
# efficiency. Setting MEMCACHE_HOSTS to be empty will turn off use of
# memcached entirely.
#
# You should not use the loopback address (127.0.0.1) here if using clustering
# as every webapp in the cluster should use the exact same values to prevent
# unneeded cache misses. Set to [] to disable caching of images and fetched data
#MEMCACHE_HOSTS = ['10.10.10.10:11211', '10.10.10.11:11211', '10.10.10.12:11211']

# Metric data and graphs are cached for one minute by default. If defined,
# DEFAULT_CACHE_POLICY is a list of tuples of minimum query time ranges mapped
# to the cache duration for the results. This allows for larger queries to be
# cached for longer periods of times. All times are in seconds. If the policy is
# empty or undefined, all results will be cached for DEFAULT_CACHE_DURATION.
#DEFAULT_CACHE_DURATION = 60 # Cache images and data for 1 minute
#DEFAULT_CACHE_POLICY = [(0, 60), # default is 60 seconds
#                        (7200, 120), # >= 2 hour queries are cached 2 minutes
#                        (21600, 180)] # >= 6 hour queries are cached 3 minutes
#MEMCACHE_KEY_PREFIX = 'graphite'

# Set URL_PREFIX when deploying graphite-web to a non-root location
#URL_PREFIX = '/graphite'

#####################################
# Filesystem Paths #
#####################################
# Change only GRAPHITE_ROOT if your install is merely shifted from /opt/graphite
# to somewhere else
#GRAPHITE_ROOT = '/opt/graphite'

# Most installs done outside of a separate tree such as /opt/graphite will only
# need to change these three settings. Note that the default settings for each
# of these is relative to GRAPHITE_ROOT
#CONF_DIR = '/opt/graphite/conf'
#STORAGE_DIR = '/opt/graphite/storage'
#STATIC_ROOT = '/opt/graphite/static'

# To further or fully customize the paths, modify the following. Note that the
# default settings for each of these are relative to CONF_DIR and STORAGE_DIR
#
## Webapp config files
#DASHBOARD_CONF = '/opt/graphite/conf/dashboard.conf'
#GRAPHTEMPLATES_CONF = '/opt/graphite/conf/graphTemplates.conf'

## Data directories
# NOTE: If any directory is unreadable in STANDARD_DIRS it will break metric browsing
#CERES_DIR = '/opt/graphite/storage/ceres'
#WHISPER_DIR = '/opt/graphite/storage/whisper'
#RRD_DIR = '/opt/graphite/storage/rrd'
# Data directories using the "Standard" finder (i.e. not Ceres)
#STANDARD_DIRS = [WHISPER_DIR, RRD_DIR] # Default: set from the above variables
#LOG_DIR = '/opt/graphite/storage/log/webapp'
#INDEX_FILE = '/opt/graphite/storage/index'  # Search index file


#####################################
# Email Configuration #
#####################################
# This is used for emailing rendered Graphs
# Default backend is SMTP
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 25
#EMAIL_HOST_USER = ''
#EMAIL_HOST_PASSWORD = ''
#EMAIL_USE_TLS = False
# To drop emails on the floor, enable the Dummy backend:
#EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'


#####################################
# Authentication Configuration #
#####################################
## LDAP / ActiveDirectory authentication setup
#USE_LDAP_AUTH = True
#LDAP_SERVER = "ldap.mycompany.com"
#LDAP_PORT = 389
#LDAP_USE_TLS = False
#        OR
#LDAP_URI = "ldaps://ldap.mycompany.com:636"
#LDAP_SEARCH_BASE = "OU=users,DC=mycompany,DC=com"
#LDAP_BASE_USER = "CN=some_readonly_account,DC=mycompany,DC=com"
#LDAP_BASE_PASS = "readonly_account_password"
#LDAP_USER_QUERY = "(username=%s)"  #For Active Directory use "(sAMAccountName=%s)"
#
# User DN template to use for binding (and authentication) against
# the LDAP server. %(username) is replaced with the username supplied at
# graphite login.
#LDAP_USER_DN_TEMPLATE = "CN=%(username)s,OU=users,DC=mycompany,DC=com"
#
# If you want to further customize the ldap connection options you should
# directly use ldap.set_option to set the ldap module's global options.
# For example:
#
#import ldap
#ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW) # Use ldap.OPT_X_TLS_DEMAND to force TLS
#ldap.set_option(ldap.OPT_REFERRALS, 0) # Enable for Active Directory
#ldap.set_option(ldap.OPT_X_TLS_CACERTDIR, "/etc/ssl/ca")
#ldap.set_option(ldap.OPT_X_TLS_CERTFILE, "/etc/ssl/mycert.pem")
#ldap.set_option(ldap.OPT_X_TLS_KEYFILE, "/etc/ssl/mykey.pem")
#ldap.set_option(ldap.OPT_DEBUG_LEVEL, 65535) # To enable verbose debugging
# See http://www.python-ldap.org/ for further details on these options.

## REMOTE_USER authentication. See: https://docs.djangoproject.com/en/dev/howto/auth-remote-user/
#USE_REMOTE_USER_AUTHENTICATION = True

# Override the URL for the login link (e.g. for django_openid_auth)
#LOGIN_URL = '/account/login'


###############################
# Authorization for Dashboard #
###############################
# By default, there is no security on dashboards - any user can add, change or delete them.
# This section provides 3 different authorization models, of varying strictness.

# If set to True, users must be logged in to save or delete dashboards. Defaults to False
#DASHBOARD_REQUIRE_AUTHENTICATION = True

# If set to the name of a user group, dashboards can be saved and deleted by any user in this
# group.  Groups can be set in the Django Admin app, or in LDAP.  Defaults to None.
# NOTE: Ignored if DASHBOARD_REQUIRE_AUTHENTICATION is not set
#DASHBOARD_REQUIRE_EDIT_GROUP = 'dashboard-editors-group'

# If set to True, dashboards can be saved or deleted by any user having the appropriate
# (change or delete) permission (as set in the Django Admin app).  Defaults to False
# NOTE: Ignored if DASHBOARD_REQUIRE_AUTHENTICATION is not set
#DASHBOARD_REQUIRE_PERMISSIONS = True



##########################
# Database Configuration #
##########################
# By default sqlite is used. If you cluster multiple webapps you will need
# to setup an external database (such as MySQL) and configure all of the webapp
# instances to use the same database. Note that this database is only used to store
# Django models such as saved graphs, dashboards, user preferences, etc.
# Metric data is not stored here.
#
# DO NOT FORGET TO RUN 'django-admin.py syncdb' AFTER SETTING UP A NEW DATABASE
#
# The following built-in database engines are available:
#  django.db.backends.postgresql_psycopg2
#  django.db.backends.mysql
#  django.db.backends.sqlite3
#  django.db.backends.oracle
#
# The default is 'django.db.backends.sqlite3' with file 'graphite.db'
# located in STORAGE_DIR
#
#DATABASES = {
#    'default': {
#        'NAME': '/opt/graphite/storage/graphite.db',
#        'ENGINE': 'django.db.backends.sqlite3',
#        'USER': '',
#        'PASSWORD': '',
#        'HOST': '',
#        'PORT': ''
#    }
#}
#

#########################
# Cluster Configuration #
#########################
# (To avoid excessive DNS lookups you want to stick to using IP addresses only in this entire section)
#
# This should list the IP address (and optionally port) of the webapp on each
# remote server in the cluster. These servers must each have local access to
# metric data. Note that the first server to return a match for a query will be
# used.
#CLUSTER_SERVERS = ["10.0.2.2:80", "10.0.2.3:80"]

## These are timeout values (in seconds) for requests to remote webapps
#REMOTE_FIND_TIMEOUT = 3.0             # Timeout for metric find requests
#REMOTE_FETCH_TIMEOUT = 6.0            # Timeout to fetch series data
#REMOTE_RETRY_DELAY = 60.0             # Time before retrying a failed remote webapp
#REMOTE_EXCLUDE_LOCAL = False          # Try to detect when a cluster server is localhost and don't forward queries
#REMOTE_READER_CACHE_SIZE_LIMIT = 1000 # Maximum number of remote URL queries to cache
#FIND_CACHE_DURATION = 300             # Time to cache remote metric find results
# If the query doesn't fall entirely within the FIND_TOLERANCE window
# we disregard the window. This prevents unnecessary remote fetches
# caused when carbon's cache skews node.intervals, giving the appearance
# remote systems have data we don't have locally, which we probably do.
#FIND_TOLERANCE = 2 * FIND_CACHE_DURATION

## Remote rendering settings
# Set to True to enable rendering of Graphs on a remote webapp
#REMOTE_RENDERING = True
# List of IP (and optionally port) of the webapp on each remote server that
# will be used for rendering. Note that each rendering host should have local
# access to metric data or should have CLUSTER_SERVERS configured
#RENDERING_HOSTS = []
#REMOTE_RENDER_CONNECT_TIMEOUT = 1.0

# If you are running multiple carbon-caches on this machine (typically behind a relay using
# consistent hashing), you'll need to list the ip address, cache query port, and instance name of each carbon-cache
# instance on the local machine (NOT every carbon-cache in the entire cluster). The default cache query port is 7002
# and a common scheme is to use 7102 for instance b, 7202 for instance c, etc.
#
# You *should* use 127.0.0.1 here in most cases
#CARBONLINK_HOSTS = ["127.0.0.1:7002:a", "127.0.0.1:7102:b", "127.0.0.1:7202:c"]
#CARBONLINK_TIMEOUT = 1.0
#CARBONLINK_RETRY_DELAY = 15 # Seconds to blacklist a failed remote server

# A "keyfunc" is a user-defined python function that is given a metric name
# and returns a string that should be used when hashing the metric name.
# This is important when your hashing has to respect certain metric groupings.
#CARBONLINK_HASHING_KEYFUNC = "/opt/graphite/bin/keyfuncs.py:my_keyfunc"

# Prefix set in carbon for the carbon specific metrics.  Default in carbon is 'carbon'
#CARBON_METRIC_PREFIX='carbon'

# The replication factor to use with consistent hashing
# This should usually match the value configured in Carbon
#REPLICATION_FACTOR = 1

# How often should render.datalib.fetch() retry to get remote data
# MAX_FETCH_RETRIES = 2

#####################################
# Additional Django Settings #
#####################################
# Uncomment the following line for direct access to Django settings such as
# MIDDLEWARE_CLASSES or APPS
#from graphite.app_settings import *
```

**Comment by kennedyoliveira** [comment]
Hey @deniszh, any news on that? It's driving me crazy, i can't start testing the monitoring module for my application in production due to this :cry:

Maybe i'm doing something wrong? I need to change any of this configuration to work or the defaults is ok?

**Comment by deniszh** [comment]
Hi @kennedyoliveira,
have no idea tbh. Something is definitely wrong with your installation. :(
I can only advice to try to install https://github.com/obfuscurity/synthesize on DO or in Virtualbox (try video if stuck - https://www.youtube.com/watch?v=-ql3X5Dbsdo) and check configs there and compare with yours.
You can compare configs even w/o installing, of course - https://github.com/obfuscurity/synthesize/tree/master/templates

**Comment by deniszh** [comment]
If configs are the same (I suspect that) - compare versions of Django and python modules.

**Comment by deniszh** [comment]
OR
try this wsgi script - https://gist.github.com/deniszh/ba79af2728f8ba23afcb
or - if do not work - https://gist.github.com/deniszh/133befd85d2e5ada2de4

**Comment by kennedyoliveira** [comment]
Hi @deniszh, thanks again for you help!

I already ran synthesize with vagrant and it worked flawlessly, i checked the versions and they all match, but i noticed a difference in the django installation, in mine the files are in the dir `site-packages` instead of `dist-packages` like the template from synthesize, maybe it's helping to cause some sort of problem?

Your `wsgi2.py` works, the project starts but the it doesn't serve the static files, i managed to make it works removing the `SetHandler None` from `/media` and `/content` then it worked but django admin isn't working, it gives and error saying a admin template wasn't found.

Even managing it to work like that, sounds like a lot of workaround, doesn't look like a easy fresh installation and probably will cause problems in the future when i forgot that to install need to do all that stuff or maybe cause some sort of problem because it's not working as expected.

I'm a java developer and i don't have apache and django knowledge, maybe i'm doing something wrong? 

What is this whitenoise? I have any significative benefits from it or can i forget it and continue using your `wsgi2.py`?

About the django admin, what i'll miss if i let it not working? sorry for the newbie question, like a said i have no knowledge about django stuff, if you have some patience to help me.

Thank you again.

**Comment by deniszh** [comment]
whitenoise is a python library which helps django app to serve static files. Without it, you need to set up Apache properly to serve static files instead.
Why wsgi1.py isn't working? In wsgi2.py I removed whitenoise part completely, then you need to take all Apache setup burden. In wsgi1.py I tried to setup whitenoise static prefix manually, instead of (in your case) broken autodetect.

**Comment by deniszh** [comment]
I found out that Nginx + Gunicorn setup nowadays looks much simpler than Apache + mod_wsgi.
You can also try that - http://www.kinvey.com/blog/108/graphite-on-ubuntu-1204-lts-8211-part-ii-gunicorn-nginx-and-supervisord

**Comment by kennedyoliveira** [comment]
@deniszh , i don't know why whitenoise didn't work, i noticed that synthesize also isn't using it.

I used a ubuntu 14.04 machine like the one from synthesize and installed everything from 0, i noticed the following diferences:

-  When i install python manually and after install django it will be installed in site-packages, and if i point apache to there for admin stuff it doesn't work. Is there any difference when installed in site-packages?
-  Whitenoise never works with me, no matter what i try, it doesn't work even with synthesize. Currently it use without whitenoise, and if i put the original wsgi with withenoise or the one that you sent it doesn't work too. [synthesize wsgi](https://github.com/obfuscurity/synthesize/blob/master/templates/graphite/conf/graphite.wsgi)
- If i install python from ubuntu repository (apt-get install) and remove whitenoise stuff from wsgi, like using your wsgi2.py and configure apache correctly to handle the static content, it works fine.

Thanks for the nginx suggestion, i'll try to configure white that, but since the problem is the whitenoise, i guess i'll need to do the same thing as with apache, configuring to nginx serve the static files then it'll work.

Just to be sure, for whitenoise work i need to do something extra? Because i saw some people saying you need to use a `collectstatic` django admin command so it can process, but it's not available with django 1.4, that used in graphite 0.9.x

**Comment by deniszh** [comment]
If it's working for you in the same setup as in synthesize - that's great. whitenoise should help with setup, not bring other troubles.
Nginx + gunicorn doesn't need static files setup and wsgi too. Maybe gunicorn serve static w/o additional  setup.

**Comment by kennedyoliveira** [comment]
@deniszh , thank you for all the support, i will try Nginx + gunicorn and will post the results here after

**Comment by wawrzek** [comment]
Have toy check that '/usr/local/django/contrib/admin/media/' exist?
I installed django via pip and had to set media alias as follow:
        Alias /media/ "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/"

**Comment by kennedyoliveira** [comment]
hey @wawrzek, yeah i checked for "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/admin/" and it doesn't existed, so i found that mine was installed in '/usr/local/django/contrib/admin/media/', thats why i pointed to there

**Comment by wawrzek** [comment]
@kennedyoliveira - You use WhiteNoise, don't you? I tried, but it didn't work so I turned it off. After sorting out /media alias I was fine.

It might be useful if you tell exactly what version of graphite you are installing. BTW. I noticed that Django 1.9.x is another problem.

**Comment by kennedyoliveira** [comment]
Hey @wawrzek - Yeah, i'm using WhiteNoise, i had to turn it off to work too. I'm installing 0.9.12.
About Django, what version do you recommend?

**Comment by deniszh** [comment]
0.9.12 only supports 1.3, maybe 1.4 IIRC
It's really old

2016-03-11 13:58 GMT+01:00 Kennedy Oliveira <notifications@github.com>:

**Comment by kennedyoliveira** [comment]
@deniszh, @wawrzek thanks for your help, i solved the problem using the NGinx + GUnicorn, and installing django 1.4 and removing white noise, that was the most "easily" way i found to get the setup working fine.

Sorry for the delay, i got really busy with some health issues and work, anyway, i appreciate the help you guys gave me.
