### ISSUE TITLE
Creating Initial Schema Fails...

### ISSUE THREAD

**Issue by rsvancara** [graphite-project/graphite-web#1514]
Hi,

Attempting to initialize the database schema for graphite-web.  I have tried so many things and all them ask for the file graphite.settings.  I am not a django developer and the documentation does not appear to be correct either.

http://graphite.readthedocs.io/en/latest/config-database-setup.html
PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py syncdb --settings=graphite.settings

I have tried:

source /opt/graphite/bin/activate
PYTHONPATH=/opt/graphite/webapp /opt/graphite/bin/django-admin.py syncdb

I have tried different versions of Django.  

Here is my error:
```
PYTHONPATH=/opt/graphite/webapp /opt/graphite/bin/django-admin.py syncdb
Traceback (most recent call last):
  File "/opt/graphite/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 5, in <module>
    from django.contrib.auth import get_user_model
  File "/opt/graphite/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/opt/graphite/local/lib/python2.7/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/opt/graphite/local/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/opt/graphite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by deniszh** [comment]
Hi @rsvancara 
Which versions of Django did you try? What's your Graphite version is?

**Comment by obfuscurity** [comment]
Closing due to inactivity.
