### ISSUE TITLE
mapSeries and reduceSeries fail if a metric hierarchy doesn't exist

### ISSUE THREAD

**Issue by lovelaced** [graphite-project/graphite-web#1516]
Perhaps related to #1507.

Traceback:
```
Traceback (most recent call last):
  File "/opt/graphite/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/graphite/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/graphite/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/graphite/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/graphite/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 401, in render
    series_list = evaluateTarget(context, target, data_store)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 496, in evaluateTarget
    result = evaluateTokens(requestContext, tokens, data_store)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 514, in evaluateTokens
    arg, data_store) for arg in tokens.call.args]
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/app.py", line 520, in evaluateTokens
    ret = func(requestContext, _args, *_kwargs)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/functions.py", line 2844, in reduceSeries
    metaSeries[key])[0]
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/functions.py", line 318, in diffSeries
    seriesList, start, end, step = normalize(seriesLists)
  File "/opt/graphite/env/lib/python2.7/site-packages/graphite_api/functions.py", line 152, in normalize
    step = reduce(lcm, [s.step for s in seriesList])
AttributeError: 'NoneType' object has no attribute 'step'
```
This happens when, for example, I have something like this (found in the grafana playground):

![2016-05-09-151329_3729x957_scrot](https://cloud.githubusercontent.com/assets/8581604/15126781/4fa1f388-15f9-11e6-80a3-f03597434759.png)

But what happens if `web_server_01` doesn't have a `counters` metric? This throws the error pasted above, and I believe it should return the series which do have the provided metrics, if possible. This would be very useful for metrics which come in and out of being (as is the case with the metrics I work with).

This is graphite 0.10.0 running on Scientific Linux 6.7 and python 2.7.
Thanks!

**Comment by dene14** [comment]
Any hint on this? Experiencing exactly the same issue on ubuntu 14.04

**Comment by dene14** [comment]
Haven't tried this, however statement that now is failing was definitely working before... The reason it's started to fail - most probably kind of upgrade (graphite's itself or some of its dependencies). Unfortunately it's totally unclear from the error traceback what's wrong in the system... All other functions do work properly (I have quite complex constructions)...

What I can say additionally according to uwsgi behaviour, request lasts in infinite loop causing 100% CPU usage per worker.

I've tried to install HEAD of 0.9.x branch, functions don't work either, however I haven't noticed infinite loop problem. Traceback also different:
```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "./graphite/render/views.py", line 126, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "./graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "./graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "./graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "./graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "./graphite/render/evaluator.py", line 27, in evaluateTokens
    func = SeriesFunctions[tokens.call.func]
KeyError: u'reduceSeries'
```

**Comment by jdbranham** [comment]
@obfuscurity 
I have the same issue; some of my metrics have only half of the required metric pair.  

Using the example -  
reduceSeries(mapSeries(servers.*.disk.*,1),"asPercent",3,"bytes_used","total_bytes")  

In my dataset, there may be a series with only "total_bytes".  

Would there be a way to use the "grep" or another function to validate the existence of both sides, before passing to reduce?

Thanks!
