### ISSUE TITLE
ImportError when running server

### ISSUE THREAD

**Issue by suhussai** [graphite-project/graphite-web#1539]
I am having an issue getting the graphite server to run on my machine. 

As per the instructions in the docs, I created a virtual environment, installed the requirements, created the directories and ran the server. I found these instructions here: http://graphite.readthedocs.io/en/latest/development.html

The server starts fine but when I navigate to 127.0.0.1:8000, this is what I see

> A server error occurred.  Please contact the administrator.

And the terminal shows this output:
```
(env) Sat-Jun-11 21:14:26 /home/suhussai/graphite-web/webapp> ./manage.py runserver
Could not import graphite.local_settings, using defaults!
Could not import graphite.local_settings, using defaults!
Performing system checks...

System check identified no issues (0 silenced).
June 12, 2016 - 03:14:29
Django version 1.9.7, using settings 'graphite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 296, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/suhussai/graphite-web/webapp/graphite/views.py", line 7, in server_error
    template = loader.get_template(template_name)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 142, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/suhussai/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 159, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'tagging.templatetags.tagging_tags': cannot import name get_model
```

My machine specs are:

OS: Ubuntu 14.04.3 LTS
Python: Python 2.7.6
Django==1.9.7
django-tagging==0.3.6

As for the graphite-web version, I did a git clone of the project and used the latest one.

**Comment by suhussai** [comment]
This issue is resolved.
Ticket is related to #1538
