### ISSUE TITLE
Metrics tree is empty when one of the cluster servers is down

### ISSUE THREAD

**Issue by roeezab** [graphite-project/graphite-web#1587]
Hi,
When one of the cluster servers is down, metrics tree returns empty, and the following exception occurs:

Tue Jul 12 05:23:10 2016 :: Exception Caught
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/metrics/views.py", line 164, in find_view
    matches = list( store.find(query) )
  File "/opt/graphite/webapp/graphite/storage.py", line 55, in find
    for match in self.find_all(query):
  File "/opt/graphite/webapp/graphite/storage.py", line 117, in find_all
    for match in request.get_results():
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 83, in get_results
    response = self.connection.getresponse()
  File "/usr/lib64/python2.6/httplib.py", line 1010, in getresponse
    method=self._method)
  File "/usr/lib64/python2.6/httplib.py", line 341, in __init__
    self.fp = sock.makefile('rb', 0)
AttributeError: 'NoneType' object has no attribute 'makefile'

The problem can be reproduced by putting a server that doesn't exist in the list.
It happens in version 0.9.15. We have an old server with version 0.9.12 and it doesn't happen there.

Any ideas?

**Comment by deniszh** [comment]
Fixed by https://github.com/graphite-project/graphite-web/pull/1560
Apply it to 0.9.15 locally or upgrade to 0.9.x branch please.

**Comment by roeezab** [comment]
Thanks!

**Comment by roeezab** [comment]
The patch has solved it after a little change to for python 2.6:
https://github.com/graphite-project/graphite-web/pull/1588
