### ISSUE TITLE
Graphite-web not running when run with nginx.

### ISSUE THREAD

**Issue by anirbanroydas** [graphite-project/graphite-web#1665]
When run, it is showing error. I am giving the error log. Server not starting, Nginx is running okay. Problem is at the uwsgi interface.

```
Thu Aug 25 12:06:32 2016 - SIGINT/SIGQUIT received...killing workers...
Thu Aug 25 12:06:33 2016 - worker 1 buried after 1 seconds
Thu Aug 25 12:06:33 2016 - worker 2 buried after 1 seconds
Thu Aug 25 12:06:33 2016 - goodbye to uWSGI.
Thu Aug 25 12:06:33 2016 - *** Starting uWSGI 1.9.17.1-debian (64bit) on [Thu Aug 25 12:06:33 2016] ***
Thu Aug 25 12:06:33 2016 - compiled with version: 4.8.2 on 23 March 2014 17:15:32
Thu Aug 25 12:06:33 2016 - os: Linux-3.19.0-65-generic #73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016
Thu Aug 25 12:06:33 2016 - nodename: heineken
Thu Aug 25 12:06:33 2016 - machine: x86_64
Thu Aug 25 12:06:33 2016 - clock source: unix
Thu Aug 25 12:06:33 2016 - pcre jit disabled
Thu Aug 25 12:06:33 2016 - detected number of CPU cores: 4
Thu Aug 25 12:06:33 2016 - current working directory: /
Thu Aug 25 12:06:33 2016 - writing pidfile to /run/uwsgi/app/graphite/pid
Thu Aug 25 12:06:33 2016 - detected binary path: /usr/bin/uwsgi-core
Thu Aug 25 12:06:33 2016 - setgid() to 33
Thu Aug 25 12:06:33 2016 - setuid() to 33
Thu Aug 25 12:06:33 2016 - your processes number limit is 112504
Thu Aug 25 12:06:33 2016 - your memory page size is 4096 bytes
Thu Aug 25 12:06:33 2016 - detected max file descriptor number: 1024
Thu Aug 25 12:06:33 2016 - lock engine: pthread robust mutexes
Thu Aug 25 12:06:33 2016 - thunder lock: disabled (you can enable it with --thunder-lock)
Thu Aug 25 12:06:33 2016 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/graphite/socket fd 3
Thu Aug 25 12:06:33 2016 - uwsgi socket 1 bound to TCP address 127.0.0.1:3031 fd 5
Thu Aug 25 12:06:33 2016 - Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
Thu Aug 25 12:06:33 2016 - *** Python threads support is disabled. You can enable it with --enable-threads ***
Thu Aug 25 12:06:33 2016 - Python main interpreter initialized at 0x160b7e0
Thu Aug 25 12:06:33 2016 - your server socket listen backlog is limited to 100 connections
Thu Aug 25 12:06:33 2016 - your mercy for graceful operations on workers is 60 seconds
Thu Aug 25 12:06:33 2016 - mapped 218376 bytes (213 KB) for 2 cores
Thu Aug 25 12:06:33 2016 - *** Operational MODE: preforking ***
  File "./wsgi.py", line 6
    .*
    ^
SyntaxError: invalid syntax
Thu Aug 25 12:06:33 2016 - unable to load app 0 (mountpoint='') (callable not found or import error)
Thu Aug 25 12:06:33 2016 - *** no app loaded. going in full dynamic mode ***
Thu Aug 25 12:06:33 2016 - *** uWSGI is running in multiple interpreter mode ***
Thu Aug 25 12:06:33 2016 - spawned uWSGI master process (pid: 46603)
Thu Aug 25 12:06:33 2016 - spawned uWSGI worker 1 (pid: 46613, cores: 1)
Thu Aug 25 12:06:33 2016 - spawned uWSGI worker 2 (pid: 46614, cores: 1)
Thu Aug 25 12:06:47 2016 - --- no python application found, check your startup logs for errors ---
[pid: 46614|app: -1|req: -1/1] 127.0.0.1 () {34 vars in 416 bytes} [Thu Aug 25 12:06:47 2016] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 1 headers in 57 bytes (0 switches on core 0)
```

**Comment by obfuscurity** [comment]
Updated your report to use a blockquote.

**Comment by obfuscurity** [comment]
I don't personally run Graphite with NGINX but there's an obvious syntax error in your output. Have you checked that?

**Comment by anirbanroydas** [comment]
Actually, this wsgi.py is what came with the source code. So I haven't done anything in that file. It's the same file. 

Apart from that, I could see there is a python issue, where it is unable to find it, also can you put some light on why is this happening and what about the line where it says thread support is disabled?

**Comment by obfuscurity** [comment]
You haven't mentioned what version you're running so I can't intuit what your `wsgi.py` looks like, nor have you posted the file itself. I'd be happy to take a look but I need more details. :)

**Comment by anirbanroydas** [comment]
```
# This file takes a single regular expression per line
# If USE_WHITELIST is set to True in carbon.conf, only metrics received which
# match one of these expressions will be persisted. If this file is empty or
# missing, all metrics will pass through.
# This file is reloaded automatically when changes are made
.*

```

The above is the wsgi.py

I am using python 2.7.6
django 1.6.11
graphite i am doing a pip install as mentioned in the docs.

Let me know if you need more info.

**Comment by obfuscurity** [comment]
That's from [whitelist.conf.example](https://github.com/graphite-project/carbon/blob/77e1eb09b9708c91ffbca6e94ffd46e1143b04ee/conf/whitelist.conf.example) from the Carbon project. That's not a valid wsgi configuration.

**Comment by obfuscurity** [comment]
Also, you haven't mentioned what version of Graphite you have installed. I'm going to _assume_ 0.9.15, but it would be helpful if you got the specific version from pip.

**Comment by obfuscurity** [comment]
Here's the [sample graphite.wsgi](https://github.com/graphite-project/graphite-web/blob/0.9.x/conf/graphite.wsgi.example) file included with Graphite 0.9.15. Alternatively you could look at [this gist](https://gist.github.com/drawks/1830579) by @drawks with his wsgi setup for NGINX.

**Comment by JeanFred** [comment]
I’m using Graphite behind nginx − happy to help if needed.

**Comment by anirbanroydas** [comment]
@JeanFred  : Can you give me a step by step starting from installation including all configuration and file creations.

NOTE:  Give me the steps with the pip installation method.

System: Ubuntu 14.04
Graphite : 0.9.15

**Comment by anirbanroydas** [comment]
Also, what is this setting?

`PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py syncdb --settings=graphite.settings`

And whenever I try this I get this following error?

```
Unknown command: 'syncdb'
Type 'django-admin.py help' for usage.
```

NOTE: I already made the changes regarding DATABASE in the local_settings.py before running the above command. I am trying to use postgres.

**Comment by anirbanroydas** [comment]
@obfuscurity  Yes my mistake with the wsgi.py. So, do I have to cp the graphite.wsgi.example as wsgi.py and put in /opt/graphite/conf directory or is it not required for setting up graphite with nginx?

**Comment by obfuscurity** [comment]
@anirbanroydas Sorry, I don't use NGINX. Did you look at @drawks' gist that I linked earlier?

Also note that I suspect you're mixing [instructions for the master branch](http://graphite.readthedocs.io/en/latest/index.html) with the 0.9.15 pip packages. Please ensure that you're following the [correct installation docs for 0.9.15](http://graphite.readthedocs.io/en/0.9.15/).

**Comment by anirbanroydas** [comment]
@obfuscurity  I used this one http://graphite.readthedocs.io/en/0.9.15/install-pip.html 
And I made a wsgi.py file in the conf directory as a copy of graphite.wsgi.example

Also, @JeanFred  This is my current configs for the setup.

My wsgi.py file in the /opt/graphite/conf directory 
```
import os
 import sys
 sys.path.append('/opt/graphite/webapp')

 try:
     from importlib import import_module
 except ImportError:
     from django.utils.importlib import import_module

 os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'graphite.settings')  # noqa

 from django.conf import settings
 from django.core.wsgi import get_wsgi_application
 # from graphite.logger import log

 application = get_wsgi_application()

 try:
     import whitenoise
 except ImportError:
     whitenoise = False
 else:
     # WhiteNoise < 2.0.1 does not support Python 2.6
     if sys.version_info[:2] < (2, 7):
         whitenoise_version = tuple(map(
                 int, getattr(whitenoise, '__version__', '0').split('.')))
         if whitenoise_version < (2, 0, 1):
             whitenoise = False

 if whitenoise:
     from whitenoise.django import DjangoWhiteNoise
     application = DjangoWhiteNoise(application)
     prefix = "/".join((settings.URL_PREFIX.strip('/'), 'static'))
     for directory in settings.STATICFILES_DIRS:
         application.add_files(directory, prefix=prefix)
     for app_path in settings.INSTALLED_APPS:
         module = import_module(app_path)
         directory = os.path.join(os.path.dirname(module.__file__), 'static')
         if os.path.isdir(directory):
             application.add_files(directory, prefix=prefix)

 # Initializing the search index can be very expensive. The import below
 # ensures the index is preloaded before any requests are handed to the
 # process.
 # log.info("graphite.wsgi - pid %d - reloading search index" % os.getpid())
 import graphite.metrics.search  # noqa
```


my uwsgi config, graphite.ini 
```
 [uwsgi]
 vacuum = true
 master = true
 processes = 2
 socket = 127.0.0.1:3031
 gid = www-data
 uid = www-data
 # virtualenv = /opt/graphite
 chdir = /opt/graphite/conf
 module = wsgi:application
```

my nginx conf

```
server {
     listen 80 default_server;
     listen [::]:80 default_server ipv6only=on;

     root /usr/share/nginx/html;
     index index.html index.htm;

     # Make site accessible from http://localhost/
     server_name localhost;

      charset     utf-8;
         # Django admin media.
         location /media/admin/ {

             alias /usr/lib/python2.7/site-packages/django/contrib/admin/media/;
         }

         # Your project's static media.
         location /content/ {

             alias /opt/graphite/webapp/content/;
         }


     location /graphite {

             uwsgi_pass  127.0.0.1:3031;
             include     uwsgi_params;
     }



     location /grafana/ {
         proxy_pass  http://localhost:3000/;
         proxy_set_header Host $host;
     }
}
```

**Comment by anirbanroydas** [comment]
@obfuscurity @JeanFred 
Also adding the uwsgi log file located at /var/log/uwsgi/apps/graphite.log

```
Fri Aug 26 18:37:56 2016 - SIGINT/SIGQUIT received...killing workers...
 Fri Aug 26 18:37:57 2016 - worker 1 buried after 1 seconds
 Fri Aug 26 18:37:57 2016 - worker 2 buried after 1 seconds
 Fri Aug 26 18:37:57 2016 - goodbye to uWSGI.
 Fri Aug 26 18:37:57 2016 - VACUUM: unix socket /run/uwsgi/app/graphite/socket removed.
 Fri Aug 26 13:07:57 2016 - *** Starting uWSGI 1.9.17.1-debian (64bit) on [Fri Aug 26 13:07:57 2016] ***
 Fri Aug 26 13:07:57 2016 - compiled with version: 4.8.2 on 23 March 2014 17:15:32
 Fri Aug 26 13:07:57 2016 - os: Linux-3.19.0-65-generic #73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016
 Fri Aug 26 13:07:57 2016 - nodename: heineken
 Fri Aug 26 13:07:57 2016 - machine: x86_64
 Fri Aug 26 13:07:57 2016 - clock source: unix
 Fri Aug 26 13:07:57 2016 - pcre jit disabled
 Fri Aug 26 13:07:57 2016 - detected number of CPU cores: 4
 Fri Aug 26 13:07:57 2016 - current working directory: /
 Fri Aug 26 13:07:57 2016 - writing pidfile to /run/uwsgi/app/graphite/pid
 Fri Aug 26 13:07:57 2016 - detected binary path: /usr/bin/uwsgi-core
 Fri Aug 26 13:07:57 2016 - setgid() to 33
 Fri Aug 26 13:07:57 2016 - setuid() to 33
 Fri Aug 26 13:07:57 2016 - your processes number limit is 112504
 Fri Aug 26 13:07:57 2016 - your memory page size is 4096 bytes
 Fri Aug 26 13:07:57 2016 - detected max file descriptor number: 1024
 Fri Aug 26 13:07:57 2016 - lock engine: pthread robust mutexes
 Fri Aug 26 13:07:57 2016 - thunder lock: disabled (you can enable it with --thunder-lock)
 Fri Aug 26 13:07:57 2016 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/graphite/socket fd 3
 Fri Aug 26 13:07:57 2016 - uwsgi socket 1 bound to TCP address 127.0.0.1:3031 fd 5
 Fri Aug 26 13:07:57 2016 - Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
 Fri Aug 26 13:07:57 2016 - *** Python threads support is disabled. You can enable it with --enable-threads ***
 Fri Aug 26 13:07:57 2016 - Python main interpreter initialized at 0x1100a70
 Fri Aug 26 13:07:57 2016 - your server socket listen backlog is limited to 100 connections
 Fri Aug 26 13:07:57 2016 - your mercy for graceful operations on workers is 60 seconds
 Fri Aug 26 13:07:57 2016 - mapped 218376 bytes (213 KB) for 2 cores
 Fri Aug 26 13:07:57 2016 - *** Operational MODE: preforking ***
Traceback (most recent call last):
   File "./wsgi.py", line 16, in <module>
     application = get_wsgi_application()
   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
     django.setup()
   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
     app_config.import_models(all_models)
   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
     self.models_module = import_module(models_module_name)
   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
     __import__(name)
   File "/usr/lib/python2.7/dist-packages/graphite/events/models.py", line 6, in <module>
     from tagging.managers import ModelTaggedItemManager
   File "/usr/lib/python2.7/dist-packages/tagging/managers.py", line 8, in <module>
     from tagging.models import Tag, TaggedItem
   File "/usr/lib/python2.7/dist-packages/tagging/models.py", line 10, in <module>
     from django.contrib.contenttypes import generic
 ImportError: cannot import name generic
 Fri Aug 26 18:37:57 2016 - unable to load app 0 (mountpoint='') (callable not found or import error)
 Fri Aug 26 18:37:57 2016 - *** no app loaded. going in full dynamic mode ***
 Fri Aug 26 18:37:57 2016 - *** uWSGI is running in multiple interpreter mode ***
 Fri Aug 26 18:37:57 2016 - spawned uWSGI master process (pid: 9888)
 Fri Aug 26 18:37:57 2016 - spawned uWSGI worker 1 (pid: 9900, cores: 1)
 Fri Aug 26 18:37:57 2016 - spawned uWSGI worker 2 (pid: 9901, cores: 1)
 Fri Aug 26 18:38:15 2016 - --- no python application found, check your startup logs for errors ---
 [pid: 9901|app: -1|req: -1/1] 106.51.64.7 () {40 vars in 690 bytes} [Fri Aug 26 18:38:15 2016] GET /graphite => generated 21 bytes in 0 msecs (HTTP/1.1 500) 1 headers in 57 bytes   (0 switches on core 0)
```

**Comment by deniszh** [comment]
@anirbanroydas - which Django do you using? 0.9.15 doesn't support 1.9, try downgrade it to 1.8

**Comment by JeanFred** [comment]
> @JeanFred : Can you give me a step by step starting from installation
including all configuration and file creations.

I can share you my Ansible play later today - it's completely reproducible
:-)

**Comment by anirbanroydas** [comment]
@JeanFred. Okay. That would be great.
@deniszh , yes, its 1.9, but do you thing the generic import issue is because of 1.9, I think it may appear it 1.8 too.

**Comment by deniszh** [comment]
Django 1.9 is not compatible with Graphite 0.9.15, it's 100%

**Comment by anirbanroydas** [comment]
@deniszh What is the compatible version then? Also, I followed the 0.9.15 docs for installation, so it  led me to this.

Where else can I reach you guys? Need solutions quickly. IRC?

**Comment by JeanFred** [comment]
@anirbanroydas I quickly dumped relevant bits of my Ansible role at https://gist.github.com/JeanFred/f9357bb485fd9428d52895951e26875d − let me know if that helps.

**Comment by deniszh** [comment]
@anirbanroydas: IIRC 1.4 - 1.8 is fine.
Sorry, I'm not on IRC now.

**Comment by anirbanroydas** [comment]
@deniszh  @JeanFred @obfuscurity 
Till now I was doing the pip installation, but now I tried the apt-get install.

I followed this link [http://arpitbhayani.me/techie/graphite.html](url) almost except the nginx config.

My nginx config is : 
```
server {
     listen 80 default_server;
     listen [::]:80 default_server ipv6only=on;

     root /usr/share/nginx/html;
     index index.html index.htm;
     
    server_name localhost;
    
   location / {

         try_files $uri $uri/ =404;

         auth_basic "Restricted Content";
         auth_basic_user_file /etc/nginx/.htpasswd;
     }

    
     location /content {
         alias /usr/share/graphite-web/static;
         expires max;
     }


     location /graphite {
             alias /usr/share/graphite-web;
             proxy_set_header Host $http_host;
             uwsgi_pass  unix:/var/run/graphite.sock;
             include     uwsgi_params;
     }
}
```

Now although nginx, uwsgi, carbon-cache all seem to start properly, but I am now getting the following error, Since I made my Debug=True.

```
ImportError at /graphite
cannot import name Col
Request Method:	GET
Request URL:	http://<my_server_domain>/graphite
Django Version:	1.6.11
Exception Type:	ImportError
Exception Value:	
cannot import name Col
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py in import_module, line 40
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7/dist-packages',
 '/usr/share/graphite-web/',
 '.',
 '',
 '/usr/share/graphite-web',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/etc/graphite',
 '/usr/lib/python2.7/dist-packages/graphite/thirdparty']
Server time:	Sun, 28 Aug 2016 02:24:12 +0530
```

You can check my python and django version from the above error itself.
Other info:
Graphite : 0.9.12
System : Ubuntu 14.04

I installaed django 1.8, then there were errors, I changed to 1.7,  old errors gone, but new errors came, I changed to 1.6 and finally 1.6.11.

What is going on here? I don't want to invest too much time in Django. Please tell me.

**Comment by deniszh** [comment]
dod you run syncdb command?
`PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py syncdb --settings=graphite.settings` 
It's mandanory.

**Comment by anirbanroydas** [comment]
@deniszh  I ran the version mentioned in the link I provided earlier since I installed it via `apt-get`.

the command I ran is : 
```sudo graphite-manage syncdb```

Please have a look at the installation from the link. I followed each and every step except the nginx configuration.

**Comment by deniszh** [comment]
According to http://stackoverflow.com/questions/29442323/django-centos-7-cannot-import-name-col/29612399#29612399 error above could be caused by improper downgraded Django.
Try to "uninstall Django, remove the remaining Django directories under site-packages, then reinstall it", as suggested.

**Comment by anirbanroydas** [comment]
@deniszh @JeanFred @obfuscurity 
Now I uninstalled cleanly, and reinstalled Django 1.6. Now its not even showing the Django Debug page unlike earlier when it was showing, now its showing 404 error.

I have followed the installation from the same link again - [https://github.com/graphite-project/graphite-web/issues/url](url)

I uninstalled many elements cleanly and reinstalled them.
```
graphite = 0.9.12 ( this installed graphite-web, graphite-carbon, whisper all version = 0.9.12)
Django = 1.6
Twisted = 13.2.0
django-tagging = 0.3.6
carbonate = 0.2.2
ceres = 0.10.0
uwsgi = 2.0.13.1
postgres = 9.3.13
```

My nginx config is still the same as above:
```
server {
     listen 80 default_server;
     listen [::]:80 default_server ipv6only=on;

     root /usr/share/nginx/html;
     index index.html index.htm;

    server_name localhost;

   location / {

         try_files $uri $uri/ =404;

         auth_basic "Restricted Content";
         auth_basic_user_file /etc/nginx/.htpasswd;
     }


     location /content {
         alias /usr/share/graphite-web/static;
         expires max;
     }


     location /graphite {
             alias /usr/share/graphite-web;
             proxy_set_header Host $http_host;
             uwsgi_pass  unix:/var/run/graphite.sock;
             include     uwsgi_params;
     }
}
```

My custom uwsgi init script is same as the one mentioned in the link I mentioned.

My nginx access.log (generalizing few confidential info)
```
 <ip-address> - - [28/Aug/2016:12:38:33 +0000] "GET / HTTP/1.1" 401 605 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.   2743.116 Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:42 +0000] "GET / HTTP/1.1" 200 419 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:48 +0000] "GET /graphite/ HTTP/1.1" 200 542 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like  Gecko) Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:48 +0000] "GET /browser/header/ HTTP/1.1" 404 208 "http://my_public_domain/graphite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X       10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:48 +0000] "GET /composer/? HTTP/1.1" 404 208 "http://my_public_domain/graphite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4)   AppleWebKit/537.36 (KHTML, like Gecko) Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:51 +0000] "GET /graphite HTTP/1.1" 200 542 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like   Gecko) Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:51 +0000] "GET /browser/header/ HTTP/1.1" 404 208 "http://my_public_domain/graphite" "Mozilla/5.0 (Macintosh; Intel Mac OS X        10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/source_ip-address Safari/537.36"
 <ip-address> - <my_user_name> [28/Aug/2016:12:38:51 +0000] "GET /composer/? HTTP/1.1" 404 208 "http://my_public_domain/graphite" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4)    AppleWebKit/537.36 (KHTML, like Gecko) Chrome/source_ip-address Safari/537.36"
```

My Nginx error.log has no info regarding this, so not updating that.

And this is my graphite.log file in /var/log/graphite.log (its configured as the uwsgi log file, if you follow the installation link then you will understand).

```
 *** Starting uWSGI 2.0.13.1 (64bit) on [Sun Aug 28 12:36:23 2016] ***
 compiled with version: 4.8.4 on 27 August 2016 19:25:41
 os: Linux-3.19.0-65-generic #73~14.04.1-Ubuntu SMP Wed Jun 29 21:05:22 UTC 2016
 nodename: heineken
 machine: x86_64
 clock source: unix
 detected number of CPU cores: 4
 current working directory: /
 detected binary path: /usr/local/bin/uwsgi
 !!! no internal routing support, rebuild with pcre support !!!
 uWSGI running as root, you can use --uid/--gid/--chroot options
 *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
 your processes number limit is 112504
 your memory page size is 4096 bytes
 detected max file descriptor number: 1024
 lock engine: pthread robust mutexes
 thunder lock: disabled (you can enable it with --thunder-lock)
 uwsgi socket 0 bound to UNIX address /var/run/graphite.sock fd 3
 Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]
 *** Python threads support is disabled. You can enable it with --enable-threads ***
 Python main interpreter initialized at 0x1f71af0
 your server socket listen backlog is limited to 100 connections
 your mercy for graceful operations on workers is 60 seconds
 mapped 507200 bytes (495 KB) for 4 cores
 *** Operational MODE: preforking ***
 added /usr/share/graphite-web/ to pythonpath.
 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1f71af0 pid: 45501 (default app)
 *** uWSGI is running in multiple interpreter mode ***
 spawned uWSGI master process (pid: 45501)
 spawned uWSGI worker 1 (pid: 45509, cores: 1)
 spawned uWSGI worker 2 (pid: 45510, cores: 1)
 spawned uWSGI worker 3 (pid: 45511, cores: 1)
 spawned uWSGI worker 4 (pid: 45512, cores: 1)
 [pid: 45510|app: 0|req: 1/1] 122.167.241.239 () {42 vars in 762 bytes} [Sun Aug 28 18:08:48 2016] GET /graphite/ => generated 542 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 135  bytes (1 switches on core 0)
 [pid: 45509|app: 0|req: 1/2] 122.167.241.239 () {42 vars in 760 bytes} [Sun Aug 28 18:08:51 2016] GET /graphite => generated 542 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 135   bytes (1 switches on core 0)
```

NOTE: please have a look at the installation link, so that you can be in sync with what I have tried so far.

Now tell me where is the problem here? Is is with my nginx config, or anything else going on here? Or is it some python or django or any dependency issue?

Really need to get this over with? Need graphite big time. But unfortunately stuck since 3-4 days.

**Comment by anirbanroydas** [comment]
This issue got solved, I made two changes.

One in the custom graphite_wsgi.py in `/usr/share/graphite-web/` , I commented the `import graphite.metrics.search`  line. And in my nginx config, I did a direct proxy pass like 

```
location / {
       // proxy pass   directive
   } 

instead of indirect
location /graphite {
       // proxy pass directives
}
```

This is the only way I could resolve this. I am closing the issue now.
