### ISSUE TITLE
 SyntaxError: invalid syntax, Help.

### ISSUE THREAD

**Issue by howfree** [graphite-project/graphite-web#1707]
I installed the following:
Graphite,Carbon,Whisper : 0.9.15，Django: 1.5，Python：2.6.6  under the Centos 6.7.
After started Httpd successfully, the same error occured in the file: error.log.
why and how to fixed it,  I appreciate your help.

Thanks.

```
================================================================
[Tue Sep 27 16:08:38 2016] [error]   warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
[Tue Sep 27 16:08:38 2016] [error] [client ::1] mod_wsgi (pid=2761): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Sep 27 16:08:38 2016] [error] [client ::1] Traceback (most recent call last):
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     response = self.get_response(request)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 178, in get_response
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 220, in handle_uncaught_exception
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     if resolver.urlconf_module is None:
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     self._urlconf_module = import_module(self.urlconf_name)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     __import__(name)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/opt/graphite/webapp/graphite/urls.py", line 32, in <module>
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     ('^render/?', include('graphite.render.urls')),
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/conf/urls/__init__.py", line 25, in include
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     urlconf_module = import_module(urlconf_module)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     __import__(name)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     from . import views
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/opt/graphite/webapp/graphite/render/views.py", line 32, in <module>
[Tue Sep 27 16:08:38 2016] [error] [client ::1]     from graphite.remote_storage import connector_class_selector
[Tue Sep 27 16:08:38 2016] [error] [client ::1]   File "/opt/graphite/webapp/graphite/remote_storage.py", line 168
[Tue Sep 27 16:08:38 2016] [error] [client ::1]      for series in unpickle.loads(pickled_response)
[Tue Sep 27 16:08:38 2016] [error] [client ::1]        ^
[Tue Sep 27 16:08:38 2016] [error] [client ::1]  SyntaxError: invalid syntax
```

**Comment by obfuscurity** [comment]
The 2nd and last lines are telling you there's a syntax error in your `graphite.wsgi` file.
