### ISSUE TITLE
No module named graphite.settings

### ISSUE THREAD

**Issue by zhaojigang** [graphite-project/graphite-web#1708]
hi,  I used "PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb" to set up a new database, but the terminal show some error:

Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named graphite.settings

I'm a little confused, can you explain why??

**Comment by yarons** [comment]
Have you found the solution?

**Comment by shammy12** [comment]
For anyone else running into this, try running it without the PYTHONPATH variable to make sure it isn't an issue with the PATH. Find the settings file location and run from there e.g. cd /opt/graphite/webapp/graphite

then

django-admin.py migrate --settings=graphite.settings --run-syncdb

**Comment by makarczyk** [comment]
good call shammy12.

**Comment by saifromeo** [comment]
I still get the following error

ubuntu@ip-172-31-27-43:/opt/graphite/webapp/graphite$ django-admin.py migrate --settings=graphic.settings --run-syncdb
Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named graphic.settings

**Comment by deniszh** [comment]
Dublicate of #1867.
@saifromeo : Try to run
```
cd /opt/graphite/webapp/
PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
```

**Comment by cixelsyd** [comment]
This is hitting me also.  All the graphite releases since 1.0.0 are giving me this error.

**Comment by deniszh** [comment]
I suspecting it's because of some Centos-specific things but I have no idea which things exactly...

**Comment by deniszh** [comment]
which version of Django are you trying, @cixelsyd ?

**Comment by cixelsyd** [comment]
I tried both 1.8 and 1.11 and they both exhibited the same behavior.

**Comment by piotr1212** [comment]
Just tried it on a quite clean centos7 and it just works for me. Are you sure you `cd` into the correct directory?

```bash
yum install python-virtualenv libffi-devel python-devel gcc
virtualenv /opt/venv
source /opt/venv/bin/activate
pip install -U setuptools
pip install -U carbon
pip install -U graphite-web
cd /opt/graphite/webapp
PYTHONPATH=/opt/graphite/webapp/ django-admin migrate --settings=graphite.settings --run-syncdb
```

**Comment by cixelsyd** [comment]
thank you very much for your efforts, i will verify today or this weekend and post my results.


mobile

**Comment by mknornschild** [comment]
Seems the same problem at Ubuntu 18.04

I installed graphite with this tutorial https://www.christian-klemm.de/icingaweb2-graphite-modul/
At the point "sudo graphite-manage syncdb " I get the following errors:

root@icinga2:/# sudo graphite-manage syncdb
Traceback (most recent call last):
  File "/usr/bin/graphite-manage", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/graphite/dashboard/models.py", line 3, in <module>
    from graphite.util import json
  File "/usr/lib/python2.7/dist-packages/graphite/util.py", line 38, in <module>
    from graphite.logger import log
  File "/usr/lib/python2.7/dist-packages/graphite/logger.py", line 87, in <module>
    log = GraphiteLogger() # import-shared logger instance
  File "/usr/lib/python2.7/dist-packages/graphite/logger.py", line 40, in __init__
    level = logging.INFO,
  File "/usr/lib/python2.7/dist-packages/graphite/logger.py", line 65, in _config_logger
    handler = Rotater(log_file, when=when, backupCount=backupCount)
  File "/usr/lib/python2.7/logging/handlers.py", line 171, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/storage/log/webapp/info.log'

**Comment by deniszh** [comment]
@mknornschild: Looks like a completely different issue to me. Sorry, I can't read German, but looks like your manual is broken somehow. Not sure which version of Graphite is in Ubuntu 18.04 packets, also Django 1.4 is probably too old.
We officially recommend to [install Graphite from sources](https://graphite.readthedocs.io/en/latest/install-source.html) or use [Docker image](https://hub.docker.com/r/graphiteapp/docker-graphite-statsd/).
