### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by zhaojigang** [graphite-project/graphite-web#1709]
hi, I used "sudo PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb" to set up a new database, but the terminal show some error:

Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Library/Python/2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/Library/Python/2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/urls.py", line 32, in <module>
    ('^render/?', include('graphite.render.urls')),
  File "/Library/Python/2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
    from . import views
  File "/opt/graphite/webapp/graphite/render/views.py", line 34, in <module>
    from graphite.render.evaluator import evaluateTarget
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 82, in <module>
    from graphite.render.functions import (SeriesFunctions,
  File "/opt/graphite/webapp/graphite/render/functions.py", line 33, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 17, in <module>
    import cairocffi as cairo
  File "/Library/Python/2.7/site-packages/cairocffi/__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "/Library/Python/2.7/site-packages/cairocffi/__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

I'm a little confused, can you explain why??

myplatform：OSX10.10.5

**Comment by obfuscurity** [comment]
The last line is telling you that you're missing the cairo libraries needed for cairocffi.

**Comment by cosmingodeanu** [comment]
I can't get this to work on solaris 11, and I've installed a lot of libraries with both pip and pkgutil

**Comment by andChow** [comment]
I have the same question，but I had installed cairocffi。
```
[root@kafka-3-2016-7 Twisted-14.0.0]# pip list
cairocffi (0.8.0)
ceres (1.1.0)
cffi (1.10.0)
distribute (0.6.14)
Django (1.9.13)
django-tagging (0.4.3)
pip (1.5.5)
pycparser (2.17)
pyparsing (2.2.0)
pytz (2017.2)
scandir (1.5)
setuptools (7.0)
Twisted (14.0.0)
txAMQP (0.7.0)
urllib3 (1.21.1)
WeasyPrint (0.36)
whisper (1.0.1)
wsgiref (0.1.2)
zope.interface (4.4.1)
```
@obfuscurity

**Comment by deniszh** [comment]
@andChow : you installed python part (`cairocffi`) but probably missing cairo libraries. Which linux distribution do you use?

**Comment by andChow** [comment]
tks, you are right, In our system，lack of libcairo.so.2。
```
[root@kafka-3-2016-7 ~]# find / -name 'libcairo.so.2'
[root@kafka-3-2016-7 ~]# cat /etc/redhat-release 
CentOS release 6.5 (Final)
[root@kafka-3-2016-7 ~]#  cat /proc/version
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013
```
