### ISSUE TITLE
ProgrammingError: (1146, "Table 'graphite.account_profile' doesn't exist")

### ISSUE THREAD

**Issue by liuhuang9492** [graphite-project/graphite-web#1750]
for example I'am install graphite for pip.This is my installation step:**

```
1. export PYTHONPATH="/opt/graphite-web/lib/:/opt/graphite-web/webapp/"
2. pip install https://github.com/graphite-project/whisper/tarball/master
3. pip install https://github.com/graphite-project/carbon/tarball/master
4. git clone https://github.com/graphite-project/graphite-web.git

```
My system environment is:
```
Django 1.9
CentOS 7.2
python 2.7
MySQL 5.6
```

The command to start the service：
`python /opt/graphite-web/bin/run-graphite-devel-server.py /opt/graphite-web/`

I start the server,the is no error.  but it report:

```
usr/bin/django-admin runserver --pythonpath /opt/graphite-web/webapp --settings graphite.settings 0.0.0.0:8080
Could not import graphite.local_settings, using defaults!
/opt/graphite-web/webapp/graphite/settings.py:243: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Could not import graphite.local_settings, using defaults!
/opt/graphite-web/webapp/graphite/settings.py:243: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Performing system checks...

System check identified no issues (0 silenced).
November 22, 2016 - 07:04:20
Django version 1.9, using settings 'graphite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
```

and I open the Web page http://IP:8080,It report:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite-web/webapp/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/opt/graphite-web/webapp/graphite/util.py", line 66, in getProfile
    return default_profile()
  File "/opt/graphite-web/webapp/graphite/util.py", line 135, in default_profile
    profile, created = Profile.objects.get_or_create(user=user)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'graphite.account_profile' doesn't exist")

```
When I synchronize the database, I found that the table did not created.

help me,please.thanks

**Comment by artkrz** [comment]
Same error, get rid of the bloody Django crap! No one cares about it. We have Grafana :)

**Comment by pat1** [comment]
try:
http://graphite.readthedocs.io/en/latest/config-local-settings.html
```
Remember, setting up a new database requires running PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb to create the initial schema.
```

**Comment by shaik1990** [comment]
I changed db_table variable in Meta class to verbose_name_plural and so i`m getting the error..! Did you solve this issue..?

**Comment by gogich77** [comment]
Same issue at Ubuntu by manual and by source installation. 
It looks the project is dropped.

**Comment by gogich77** [comment]
Fix in case it is installed by the package manager
graphite-manage  migrate --settings=graphite.settings --run-syncdb

**Comment by deniszh** [comment]
@gogich77 : which project dropped? Graphite itself is alive and kicking.
Exact Django migration command depends on Django version, current Graphite support Django 1.8.xx - 2.1.xx, which are quite different.
We always recommend install everything from source and do not use built-in packages - or use Docker image.

**Comment by tsvsj** [comment]
> 
> 
> Fix in case it is installed by the package manager
> graphite-manage migrate --settings=graphite.settings --run-syncdb

@gogich77 Thank you very much! That hint saved my day!
