### ISSUE TITLE
graphite-manage syncdb error

### ISSUE THREAD

**Issue by Dan33l** [graphite-project/graphite-web#1767]
# on ubuntu 16.04  Graphite Carbon / Graphite Web
  apt-get install graphite-web graphite-carbon

Installed versions are graphite-carbon 0.9.15-1 and graphite-web 0.9.15+debian-1 

# Install a database for Django backend
   apt-get install postgresql libpq-dev python-psycopg2

# Create a Database User and a Database
   sudo -u postgres psql

   postgres =# CREATE USER graphite WITH PASSWORD 'mypassword';
   postgres =# CREATE DATABASE graphite WITH OWNER graphite;
   postgres =# \q

# Configure Graphite Web Application
vi /etc/graphite/local_settings.py
```
      # Change the default secret key ...
      => SECRET_KEY = 'mysecretkey'
      # Change the default Time Zone (set to your time zone)
      => TIME_ZONE = 'Europe/Paris'
      # Remote user authentication
      => USE_REMOTE_USER_AUTHENTICATION = True
      # Configure the database access
      DATABASES = {
         'default': {
            'NAME': 'graphite',
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'USER': 'graphite',
            'PASSWORD': 'mypassword',
            'HOST': '127.0.0.1',
            'PORT': '5432'
         }
      }
```
 Save the file

# Sync the Database
graphite-manage syncdb
```
Operations to perform:
  Synchronize unmigrated apps: account, cli, render, whitelist, metrics, url_shortener, dashboard, composer, events, browser
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table account_profile
    Creating table account_variable
    Creating table account_view
    Creating table account_window
    Creating table account_mygraph
    Creating table dashboard_dashboard
    Creating table events_event
    Creating table url_shortener_link
    Running deferred SQL...
Traceback (most recent call last):
  File "/usr/bin/graphite-manage", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 318, in sync_apps
    cursor.execute(statement)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
```

**Comment by obfuscurity** [comment]
We don't package Graphite for any distributions. In fact, I have no idea what `graphite-manage` even is. Please open a bug report with the vendor.

As a point of reference, here are the official database setup instructions:

**Comment by Dan33l** [comment]
The command `graphite-manage` is a wraper :
```
#! /usr/bin/python

import os
import sys

try:
    import graphite.settings # Assumed to be in the same directory.
except ImportError:
    sys.stderr.write("Error: Can't find the file 'settings.py' in the directory containing %r. It appears you've customized things.\nYou'll have to run django-admin.py, passing it your settings module.\n(If the file settings.py does indeed exist, it's causing an ImportError somehow.)\n" % __file__)
    sys.exit(1)

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "graphite.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
/usr/bin/graphite-manage (END)
```
