### ISSUE TITLE
Render api - events: list index out of range

### ISSUE THREAD

**Issue by zacharya19** [graphite-project/graphite-web#1776]
When trying to access to render url like that:
`render?from=-5minute&target=events(%27fe%27)&format=json`
and there is event in the last 5 min, I get:
```
Traceback (most recent call last):
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 125, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 30, in evaluateTokens
    return func(requestContext, *args)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 2826, in events
    if values[value_offset] is None:
IndexError: list index out of range
```

Python version: 2.7.6
OS: Ubuntu 14.04

**Comment by zacharya19** [comment]
Look like the problem was with the time zone.
#1482 fixed it.
