### ISSUE TITLE
Randomly returns HTTP 500, pyparsing fails to parse

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/graphite-web#1806]
Original POST request :
```
target=aliasByNode(highestAverage(netapp.perf.{MBP}.{clus1}.node.*.vol_summary.total_data,5),5)&from=-6h&until=now&format=json&maxDataPoints=auto
```

Randomly, an error is returned like this one :

```
Tue Jan 31 14:34:04 2017 :: Exception encountered in <POST http://127.0.0.1:81/graphite/render>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 115, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 7, in evaluateTarget
    tokens = grammar.parseString(target)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3964, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3964, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3900, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3839, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3829, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1517, in _parseCache
    cache.set(lookup, pe.__class__(*pe.args))
  File "/usr/local/lib/python2.7/dist-packages/pyparsing.py", line 1464, in set
    cache.popitem(False)
  File "/usr/lib/python2.7/collections.py", line 161, in popitem
    value = self.pop(key)
  File "/usr/lib/python2.7/collections.py", line 143, in pop
    raise KeyError(key)
KeyError: ([{Combine:({"{" Combine:({{{Suppress:("\") W:((){}...)} | W:(!#%$...)}}...) [, Combine:({{{Suppress:("\") W:((){}...)} | W:(!#%$...)}}...)]... "}"}) | Combine:({{{Suppress:("\") W:((){}...)} | W:(!#%$...)}}...)}]..., u'aliasByNode(highestAverage(netapp.perf.{MBP}.{clus1}.node.*.vol_summary.total_data, 5), 5)', 38, True, True)
```

I'm using Grafana in the frontend, if I reload from the Grafana reload button, it'll usually fetch correctly then again it will fail after a few tests.

**Comment by ybizeul** [comment]
Same query performed again :

```
target=aliasByNode(highestAverage(netapp.perf.{MBP}.{clus1}.node.*.vol_summary.total_data, 5), 5)&from=-6h&until=now&format=json&maxDataPoints=437
```

```
HTTP/1.1 200 OK\r\n
```

**Comment by deniszh** [comment]
Maybe bug in pyparsing? Try to upgrade or downgrade it.

**Comment by ybizeul** [comment]
I was actually looking at https://github.com/graphite-project/graphite-web/commit/587a48cd6fbb07a4c79dcf7ce573e02c6b6580d8

**Comment by ybizeul** [comment]
Certainly looks like a pyparsing issue.

The parser chokes on this for example :

```
aliasByNode(highestAverage(netapp.perf.{MBP}.{clus1}.node.*.processor.avg_processor_busy, 5), 5)
```

With that said, before that, I see it parsing things like that :

```
Parse:[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]
Done: ['[', [[u'\xc0', u'\xd6'], [u'\xd8', u'\xf6'], [u'\xf8', u'\xff']], ']']
Parse:[\0xa1-\0xbf\0xd7\0xf7]
Done: ['[', [[u'\xa1', u'\xbf'], u'\xd7', u'\xf7'], ']']
```

I don't know where that comes from yet

**Comment by ybizeul** [comment]
Apparently pyparsing 2.1 is broken with Graphite.
Debian Jessiec omew with 2.0 preinstaller, but installing setuptools (I assume) bring 2.1 as part of the dependencies.

Just uninstalling with `pip uninstall pyparsing` did the job.

Before :
```
root@adva:~# pip show pyparsing
Name: pyparsing
Version: 2.1.10
Summary: Python parsing module
Home-page: http://pyparsing.wikispaces.com/
Author: Paul McGuire
Author-email: ptmcg@users.sourceforge.net
License: MIT License
Location: /usr/local/lib/python2.7/dist-packages
Requires: 

root@adva:~# dpkg -l python-pyparsing
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python-pyparsi 2.0.3+dfsg1- all          Python parsing module
```

**Comment by deniszh** [comment]
Does 2.0 working fine? Then we need to pin it, instead of 1.5.7

**Comment by ybizeul** [comment]
1.5.7 i son longer pinned indeed. 2.0 is just fine

**Comment by iksaif** [comment]
I use 2.1.10 and it works just fine. Could you try in an isolated venv ?

**Comment by ybizeul** [comment]
Are you sure graphite is using it? Make a dashboard with around 10 panels on it and refresh until it breaks, it doesn't take more than 3 or 4 refresh here before some panels show errors. Has been confirmed with fresh installs as well. Pyparsing developer came back to me and was very helpful explaining the major difference with multi threading with 2.2 that didn't exists in 2.1, it seems pretty clear 2.1 needs to be pinned.

**Comment by deniszh** [comment]
@ybizeul 
>  Pyparsing developer came back to me and was very helpful explaining the major difference with multi threading with 2.2 that didn't exists in 2.1, it seems pretty clear 2.1 needs to be pinned.
Did you mean 2.1 and 2.0 - or 2.2 and 2.1 ? 
pyparsing 2.2 doesn't exist

**Comment by iksaif** [comment]
@ybizeul ah, I don't use threads.

**Comment by ybizeul** [comment]
@deniszh Yes, sorry for the confusion!
@iksaif It's actually unclear what the issue is, not sure what needs to be done to actually use 2.1, it looks like we end up with some garbage pulled from the dictionary when concurrent requests are done

**Comment by xneo64** [comment]
I got the same issue here with pyparsing 2.1.10 and graphite master. After reading this thread I tried downgrading pyparsing to 1.5.7 and now not getting random errors anymore. 

Give me a shout if anybody wants me to test other versions.

**Comment by DanCech** [comment]
@xneo64 Can you share any exception logs?  The changes in #1810 should have resolved the issue that was previously causing problems with 2.1+
