### ISSUE TITLE
A code error when request to the Graphite Web

### ISSUE THREAD

**Issue by zhkmxx9302013** [graphite-project/graphite-web#1807]
When I request to the Graphite Webapp, there always an error like below.

`[01/Feb/2017 04:40:36] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 93, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 176, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 218, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/python2.6/site-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/urls.py", line 22, in <module>
    url('^render/?', include('graphite.render.urls')),
  File "/usr/lib/python2.6/site-packages/django/conf/urls/__init__.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
    from . import views
  File "/opt/graphite/webapp/graphite/render/views.py", line 33, in <module>
    from graphite.remote_storage import connector_class_selector
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 177
     for series in unpickle.loads(pickled_response):
       ^
 SyntaxError: invalid syntax
`

I don't know the reason of the " SyntaxError: invalid syntax" , thx..

**Comment by zhkmxx9302013** [comment]
I've solved this issue now. It caused by the wrong version of the Python. The tag 0.9.15 is not support the python 2.6, it use some new feature of the python 2.7, for example “Dictionary comprehensions”.  

So, by using the tag 0.9.14 with the python 2.6, can solve this problem.
