### ISSUE TITLE
NameError: name 'patterns' is not defined

### ISSUE THREAD

**Issue by jacobweber** [graphite-project/graphite-web#1816]
I'm following the instructions [here](https://graphite.readthedocs.io/en/latest/install-pip.html) and [here](https://graphite.readthedocs.io/en/latest/config-database-setup.html), to install graphite. This is on a CentOS 6.7 box, using python 2.7. When I installed django using pip, it installed 1.10.5.

When I get to the step of creating the database:
```
PYTHONPATH=/opt/graphite/webapp django-admin migrate --settings=graphite.settings --run-syncdb
```

it returns an error:
```
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib64/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/urls.py", line 29, in <module>
    urlpatterns = patterns('',
NameError: name 'patterns' is not defined
```

That file (urls.py) contains the statement which seems to be causing the error:
```
urlpatterns = patterns('',
  ('^admin/', include(admin.site.urls)),
  ...
)
```

Anything I can do to fix this? For what it's worth, I followed the same steps on a different box a while back, and it worked. That box had django 1.8.4.

**Comment by jacobweber** [comment]
Installing the older version of django fixed this:
```
pip uninstall Django
pip install "Django>=1.9,<1.9.99
```

**Comment by q2dg** [comment]
Ei, I have the same problem!
Installing old Django versions is not a solution!
Please reopen this issue

**Comment by deniszh** [comment]
@q2dg - no need to install old Django version, vice versa - Django should be updated.
Graphite 1.1.x requires at least Django 1.8, or newer.

**Comment by q2dg** [comment]
Thanks a lot @deniszh . It's strange because I'm using 1.11 version of Django (it's the one is package in artful/bionic Ubuntu distros)

**Comment by DanCech** [comment]
You are running an old version of Graphite, please update to the current release which will solve the problem.

**Comment by q2dg** [comment]
Thanks. Well..I'm using packages provided by official Ubuntu repositories, which, now I see, are below 1.0 version except in bionic. What a pity.Thanks

**Comment by deniszh** [comment]
@q2dg : You can install Graphite from source, that's not that hard. Or you can use old Graphite, of course, but then you need to downgrade Django to 1.6, indeed.

**Comment by ainsey11** [comment]
Installing old Django worked for me 👍

**Comment by ponikrf** [comment]
The installation in ubuntu 17.10 from the packages leads to the same error, tell it will be fixed in the future?

**Comment by deniszh** [comment]
@ponikrf: sorry, we can't guarantee that all current and future versions of all Linux distros will be compatible with Graphite. If you installing Graphite not from the package the please install Django and other dependencies also not from package.
