### ISSUE TITLE
Object has no attribute 'OP_NO_TLSv1_1'

### ISSUE THREAD

**Issue by Neurobion** [graphite-project/graphite-web#1838]
**trusty-64**
```
root@vagrant-ubuntu-trusty-64:/opt/graphite/conf# history
    1  apt-get install python-dev libcairo2-dev libffi-dev
    2  apt-get update
    3  apt-get install python-dev libcairo2-dev libffi-dev
    4  export PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/"
    5  apt-get install python-pip
    6  pip install https://github.com/graphite-project/whisper/tarball/master
    7  pip install https://github.com/graphite-project/carbon/tarball/master
    8  pip install https://github.com/graphite-project/graphite-web/tarball/master
    9  pushd /opt/graphite/conf
   10  cp carbon.conf.example carbon.conf
   11  cp storage-schemas.conf.example storage-schemas.conf
   12  /opt/graphite/bin/carbon-cache.py start
```
with result:

```
root@vagrant-ubuntu-trusty-64:/opt/graphite/conf# /opt/graphite/bin/carbon-cache.py start
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 60, in run_twistd_plugin
    from twisted.internet import epollreactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'
```

**Comment by deniszh** [comment]
Please see https://github.com/graphite-project/graphite-web/issues/1721#issuecomment-253279181
Remove system `python-openssl` package or upgrade it if it's needed - `pip install pyopenssl`

**Comment by Neurobion** [comment]
Or alternatively install older Twisted 16.0.0.
`pip install Twisted==16.0.0`

Thank you
