### ISSUE TITLE
OperationalError: no such table: account_profile

### ISSUE THREAD

**Issue by hexian55** [graphite-project/graphite-web#1840]
Django Version:	1.9.12
Exception Type:	OperationalError
Exception Value:	
no such table: account_profile
Exception Location:	/usr/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 323
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/graphite/webapp',
 '/opt/graphite/webapp',
 '/opt/graphite/webapp',
 '/usr/bin',
 '/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages',
 '/opt/graphite/webapp/graphite/thirdparty']

**Comment by hexian55** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib64/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib64/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/lib64/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/lib64/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/lib64/python2.7/site-packages/django/core/urlresolvers.py", line 115, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/browser/views.py", line 22, in <module>
    from graphite.util import getProfile, getProfileByUsername, defaultUser, json
  File "/opt/graphite/webapp/graphite/util.py", line 89, in <module>
    defaultProfile = Profile.objects.get(user=defaultUser)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: account_profile

**Comment by SEJeff** [comment]
This is not a graphite problem. This is a setup problem with your install. You need to run `python manage.py migrate` to create the tables.

Please read the install document to setup your system properly first.

**Comment by hexian55** [comment]
python manage.py migrate
Operations to perform:
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Running migrations:
  No migrations to apply.


I have been executed ,but I do not think it's the problem

**Comment by deniszh** [comment]
@hexian55 - your graphite should work despite error above

**Comment by hexian55** [comment]
but graphite-web don't work,how to do?

**Comment by deniszh** [comment]
That's a different issue then. What's symptoms? What's in the logs?

**Comment by hexian55** [comment]
When I visit through the browser, I will report the above error message. 

OperationalError: no such table: account_profile

**Comment by deniszh** [comment]
What's your Graphite and Django versions are?

**Comment by hexian55** [comment]
Django (1.9)
django-tagging (0.4.5)

**Comment by deniszh** [comment]
Strange, it should work. Sorry, I have no good ideas here. The version is OK, migrate command should create all tables.

**Comment by hexian55** [comment]
Django must be 1.8.15!!!   it's ok

**Comment by zomawat** [comment]
Did you try to flush your database ?

**Comment by deniszh** [comment]
> Django must be 1.8.15!!! it's ok
For 0.9.15 Django 1.9 is not supported, 1.8 is fine.
For master Django 1.9 is required.

**Comment by block2busted** [comment]
https://stackoverflow.com/questions/61095742/operationalerror-at-admin-account-profile-no-such-table-account-profile
Do like this) it really work
