### ISSUE TITLE
STATIC_ROOT

### ISSUE THREAD

**Issue by Neurobion** [graphite-project/graphite-web#1841]
http://graphite.readthedocs.io/en/latest/config-local-settings.html

```
root@vagrant-ubuntu-precise-64:/opt/graphite# PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py collectstatic --noinput --settings=graphite.settings
Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named graphite.settings
```

Not sure if this help is up to date, but there is no `collectstatic` option

```
root@vagrant-ubuntu-precise-64:/opt/graphite# PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py 

Type 'django-admin.py help <subcommand>' for help on a specific subcommand.

Available subcommands:
[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    runserver
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

```

**Comment by Neurobion** [comment]
Missing environment variable `$GRAPHITE_ROOT`. But help is not showing mentioned option.
