### ISSUE TITLE
IndexError: list index out of range in distance_to_requested_interval

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#1862]
I'm performing initial testing of master as of today and seeing the following stack trace.  I am able to load other graphs.  I do still apply a few internal patches but I do not believe are impacting this code path path.  

One URL causing the issues is `/render?width=500&from=-4hours&until=now&height=400&target=carbon.carbon-daemons.*.*.metrics_received`

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 194, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 54, in evaluateTokens
    args = [evaluateTokens(requestContext, arg, replacements) for arg in tokens.call.args]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/opt/graphite/webapp/graphite/util.py", line 229, in wrapped_f
    res = f(*args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 261, in fetchData
    seriesList = _fetchData(pathExpr, startTime, endTime, now, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/util.py", line 229, in wrapped_f
    res = f(*args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 155, in _fetchData
    matching_nodes = [node for node in STORE.find(pathExpr, startTime, endTime, local=requestContext['localOnly'])]
  File "/opt/graphite/webapp/graphite/storage.py", line 44, in find
    for match in self.find_all(query, headers):
  File "/opt/graphite/webapp/graphite/storage.py", line 180, in find_all
    best_candidate = min(leaf_nodes, key=distance_to_requested_interval)
  File "/opt/graphite/webapp/graphite/storage.py", line 176, in distance_to_requested_interval
    latest = sorted(node.intervals, key=lambda i: i.end)[-1]
IndexError: list index out of range

```

**Comment by deniszh** [comment]
@cbowman0 : It's only for carbon.* metrics?

**Comment by cbowman0** [comment]
Yes.  So far that the only set I'm able to reproduce it on.

**Comment by deniszh** [comment]
Ah, according to code you have REMOTE_STORE_MERGE_RESULTS = False. Right, @cbowman0 ?
Then I fall back to old code - https://github.com/graphite-project/graphite-web/blame/3b7ccf79b6a47860deeca80aa7fa1b1e3a218c43/webapp/graphite/storage.py#L83-L132 - which is there for 5 years already. Hmmmmm...

**Comment by DanCech** [comment]
Seems that error would happen if `node.intervals` was an empty list

**Comment by cbowman0** [comment]
@deniszh I do have `REMOTE_STORE_MERGE_RESULTS = False`.  Sometime around Nov of last year time frame, something in that code path caused issues in me getting data.  I believe it may have been related to #1739.  So much has changed since then, though, that i'll be probably worthless to track back to why at this point.

@DanCech Yep.
I added some logging in there. 
Contents of leaf_nodes:
```
2017-03-21,13:07:31.886 :: leaf_nodes: [<LeafNode[7f4e2409c350]: carbon.carbon-daemons.datastore1.instance1.metrics_received (<RemoteReader[7f4e380b3e68]: 10.0.0.100>)>, <LeafNode[7f4e240d1dd0]: carbon.carbon-daemons.datastore1.instance1.metrics_received (<RemoteReader[7f4e240c4ba8]: 10.0.0.102>)>]
```
Node and contents of intervals of the first node passed to `distance_to_requested_interval`:
```
2017-03-21,13:07:31.886 :: node: <LeafNode[7f4e2409c350]: carbon.carbon-daemons.datastore1.instance1.metrics_received (<RemoteReader[7f4e380b3e68]: 10.0.0.100>)>
2017-03-21,13:07:31.886 :: node.intervals: []
```

**Comment by cbowman0** [comment]
The issue does not happen if `REMOTE_STORE_MERGE_RESULTS` is True.

If `REMOTE_STORE_MERGE_RESULTS = False`, then adding return if node.intervals is empty like
```
            if not node.intervals:
              return float('inf')
```
prior to the `latest = sorted(node.intervals, key=lambda i: i.end)[-1]` line keeps results in graphs and no errors.

**Comment by deniszh** [comment]
PR is prepared, looks good.

**Comment by deniszh** [comment]
...and merged.
