### ISSUE TITLE
Stack trace and 500 error with templates

### ISSUE THREAD

**Issue by cbowman0** [graphite-project/graphite-web#1863]
I am getting the following stack trace in the logs and a HTTP 500 error unless I set `TEMPLATE_DIRS = "/opt/graphite/webapp/graphite/templates/"` in local_settings.py

error.log:
```
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5] mod_wsgi (pid=10696): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5] Traceback (most recent call last):
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     response = self.get_response(request)
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 178, in get_response
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 224, in handle_uncaught_exception
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     return callback(request, **param_dict)
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/opt/graphite/webapp/graphite/views.py", line 7, in server_error
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     template = loader.get_template(template_name)
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     template, origin = find_template(template_name)
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]   File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5]     raise TemplateDoesNotExist(name)
[Tue Mar 21 13:34:11 2017] [error] [client 10.0.0.5] TemplateDoesNotExist: 500.html
```

exception.log:
```
==> /opt/graphite/storage/log/webapp/exception.log <==
2017-03-21,13:39:12.642 :: Exception encountered in <GET http://my_graphite_test_host.com/dashboard/>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/dashboard/views.py", line 154, in dashboard
    return render_to_response("dashboard.html", context)
  File "/usr/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: dashboard.html
```

**Comment by cbowman0** [comment]
Could this be because I'm running Django 1.5?

**Comment by deniszh** [comment]
Are you running master on 1.5 ? How's that possible?

**Comment by deniszh** [comment]
We can add `TEMPLATE_DIRS` fix, if still supported in latest Django ofc.

**Comment by cbowman0** [comment]
Yes.  I've been running on master with these specific packages for a while.  It still works 🤷‍♂️ .

**Comment by deniszh** [comment]
Yes, I think it's because of Django 1.5. Master including https://github.com/graphite-project/graphite-web/blob/89d21b73b410cc51f4c66fab6ac38c71c00c06fd/webapp/graphite/app_settings.py which contains TEMPLATE variable, which was introduced in Django 1.8

**Comment by deniszh** [comment]
Not sure should we fix that, @cbowman0 . Maybe for 0.9.16 only?

**Comment by cbowman0** [comment]
I don't know.  I haven't run the 0.9.x line in a very long time.

**Comment by cbowman0** [comment]
I'd say close this.

**Comment by leochen4891** [comment]
I ran into this issue as well with graphite-web 1.0.2 and django 1.7.11.
Adding TEMPLATE_DIRS solves the problem.

**Comment by DanCech** [comment]
@leochen4891 upgrade to a supported django, 1.8+

**Comment by leochen4891** [comment]
I have tried django 1.8.18 and it didn't work because of some "Table auth_user does not exist" issue.
Maybe I can try django 1.9.
