### ISSUE TITLE
race condition while accessing * data

### ISSUE THREAD

**Issue by neeocf** [graphite-project/graphite-web#1866]
when requesting data (for example x.y.*.www.files) via graphite-web api it's fetched from whisper storage. however it seems directory listing is made at the begining (and I've got about 200K directories at 'z' level), and it's possible the data is removed by another tool before whisper lib actually tries to access the specific directory.

```
2017-03-21,06:19:51.101 :: Failed after 2 retry! Root cause:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/graphite/render/datalib.py", line 208, in fetchData
    seriesList = _fetchData(pathExpr, startTime, endTime, now, requestContext, seriesList)
  File "/usr/lib/python2.7/dist-packages/graphite/render/datalib.py", line 114, in _fetchData
    if node.is_leaf
  File "/usr/lib/python2.7/dist-packages/graphite/node.py", line 32, in fetch
    result = self.reader.fetch(startTime, endTime)
  File "/usr/lib/python2.7/dist-packages/graphite/readers.py", line 185, in fetch
    data = whisper.fetch(self.fs_path, startTime, endTime)
  File "/usr/lib/python2.7/dist-packages/whisper.py", line 710, in fetch
    fh = open(path,'rb')
IOError: [Errno 2] No such file or directory: u'/var/lib/graphite/whisper/x/y/z/www/files.wsp'
```

as a quick workaround I've made simple change to readers module:
```
index d432c25..85edabb 100644
--- a/webapp/graphite/readers.py
+++ b/webapp/graphite/readers.py
@@ -182,7 +182,10 @@ class WhisperReader(object):
     return IntervalSet( [Interval(start, end)] )
 
   def fetch(self, startTime, endTime):
-    data = whisper.fetch(self.fs_path, startTime, endTime)
+    try:
+        data = whisper.fetch(self.fs_path, startTime, endTime)
+    except IOError:
+        return None
     if not data:
       return None
```

software details: python 2.7, graphite-web - latest git,

**Comment by deniszh** [comment]
Hi @neeocf - thanks for reporting!
@iksaif @DanCech - are we OK with simply ignoring IO errors accessing whisper? Or it's better to report it in some way?

**Comment by DanCech** [comment]
Since it's an edge case I'd suggest it should at least be logged

**Comment by deniszh** [comment]
How 'bout https://github.com/graphite-project/graphite-web/pull/1878 @DanCech ?
