### ISSUE TITLE
Random 'all subfetches failed'

### ISSUE THREAD

**Issue by iksaif** [graphite-project/graphite-web#1883]
Upgraded one of the front instances, and we keep getting random 'all subfetches failed' messages.

```
Traceback (most recent call last):
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/views.py", line 124, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
    return fetchData(requestContext, expression)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/util.py", line 229, in wrapped_f
    res = f(*args, **kwargs)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/datalib.py", line 261, in fetchData
    seriesList = _fetchData(pathExpr, startTime, endTime, now, requestContext, seriesList)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/util.py", line 229, in wrapped_f
    res = f(*args, **kwargs)
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/render/datalib.py", line 165, in _fetchData
    results = results.waitForResults()
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/readers.py", line 47, in waitForResults
    return self.wait_callback()
  File "/home/iksaif/dev/criteo-dev/graphite/graphite-web/webapp/graphite/readers.py", line 86, in merge_results
    raise Exception("All sub-fetches failed")
Exception: All sub-fetches failed
```

I haven't been able to debug why yet. I suspect a race condition in the new remote code.

cc: @DanCech

**Comment by iksaif** [comment]
`REMOTE_PREFETCH_DATA = True` seems to mitigate the issue

**Comment by DanCech** [comment]
@replay could use your eyes here also

**Comment by replay** [comment]
thx for the report @iksaif. could you please describe your env some more?
how many cluster nodes do you have, is `USE_WORKER_POOL` `true`?

**Comment by iksaif** [comment]
I'm trying to debug the issue on my setup because I think it will be quite hard to reproduce. I have it with and without `USE_WORKER_POOL` and with 10 hosts and a replication factor of 2

**Comment by iksaif** [comment]
Ok, it looks like it's caused by the slaves values from other slaves

**Comment by iksaif** [comment]
This is likely caused by 'remove noCache from backend requests'

**Comment by iksaif** [comment]
I expect this to be enough:
```diff
diff --git a/webapp/graphite/remote_storage.py b/webapp/graphite/remote_storage.py
index e50098b..6e3dbfe 100755
--- a/webapp/graphite/remote_storage.py
+++ b/webapp/graphite/remote_storage.py
@@ -198,6 +198,7 @@ class RemoteReader(object):
       ('target', self.query),
       ('format', 'pickle'),
       ('local', '1'),
+      ('noCache', '1'),
       ('from', str( int(startTime) )),
       ('until', str( int(endTime) ))
     ]
```

**Comment by iksaif** [comment]
See
* https://github.com/criteo-forks/graphite-web/commit/667e6d5d89e523b51e4d66ac50ec38519a4ddb56
* https://github.com/criteo-forks/graphite-web/commit/bc3385aa515e23df9a393d606a8bfa093bfc530b

Will send a PR tomorrow

**Comment by replay** [comment]
oh, great debugging work, i must have missed that `else` in https://github.com/criteo-forks/graphite-web/commit/667e6d5d89e523b51e4d66ac50ec38519a4ddb56

**Comment by iksaif** [comment]
https://github.com/graphite-project/graphite-web/pull/1884
