### ISSUE TITLE
ValueError: path '/opt/graphite/webapp' cannot be absolute [windows]

### ISSUE THREAD

**Issue by seanvree** [graphite-project/graphite-web#1917]
Running this on a windows 10 install. 

Pardon my noobness to graphite, but I'm no noob when it comes to PY on win. 

I can't seem to get past this error, I've tried to look for the conf file, but no luck:

```
c:\graphite-web>python setup.py install
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    **setup_kwargs
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "C:\Python27\lib\distutils\command\install.py", line 353, in finalize_options
    'userbase', 'usersite')
  File "C:\Python27\lib\distutils\command\install.py", line 504, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
  File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
    raise ValueError, "path '%s' cannot be absolute" % pathname
ValueError: path '/opt/graphite/webapp' cannot be absolute

c:\graphite-web>
```

Throw me a bone!

**Comment by deniszh** [comment]
Yes, Graphite on Windows is totally not-supported. Not even sure if it will work at all. Patches are welcome. :)

**Comment by piotr1212** [comment]
https://github.com/graphite-project/graphite-web/pull/2409
