### ISSUE TITLE
OperationalError: no such table: account_profile .. Help required

### ISSUE THREAD

**Issue by mailRavi** [graphite-project/graphite-web#1929]
Getting the below error:
2017-05-11,18:39:59.707 :: Exception encountered in <GET http://den01chh.in.open.com/browserheader>
Traceback (most recent call last):
  File "/opt/graphite/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/browser/views.py", line 35, in header
    context['profile'] = getProfile(request)
  File "/opt/graphite/webapp/graphite/user_util.py", line 25, in getProfile
    return default_profile()
  File "/opt/graphite/webapp/graphite/user_util.py", line 44, in default_profile
    profile, created = Profile.objects.get_or_create(user=user)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/opt/graphite/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/graphite/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: account_profile

----------
[den01chh webapp]# django-admin.py migrate --settings=graphite.settings
Operations to perform:
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Running migrations:
  No migrations to apply.
-----

list of packages isntalled:
fadvise==4.0.0
Django>=1.9,<1.9.99
python-memcached==1.47
txAMQP==0.4
simplejson==2.1.6
django-tagging==0.4.3
gunicorn
pytz
pyparsing
cairocffi
git+https://github.com/graphite-project/whisper.git#egg=whisper
# Ceres is optional
# git+https://github.com/graphite-project/ceres.git#egg=ceres
whitenoise
scandir
urllib3
fadvise==4.0.0
Twisted>=13.2.0
git+https://github.com/graphite-project/whisper.git#egg=whisper
txAMQP
cachetools

Any Help??!?

**Comment by mailRavi** [comment]
runniing the  below command solved thhe issue. Thanks 
manage.py migrate --run-syncdb

**Comment by Palt0n** [comment]
If you are following the 
[How-to-install-Graphite-and-Grafana tutorial by netapp](https://community.netapp.com/t5/OnCommand-Storage-Management-Software-Articles-and-Resources/How-to-install-Graphite-and-Grafana/ta-p/109456)

Instead of running:
`sudo graphite-manage syncdb
`
Run:
`sudo graphite-manage migrate --run-syncdb`
