### ISSUE TITLE
Running Django-admin gives ImportError: No module named readers.remote

### ISSUE THREAD

**Issue by hapx101** [graphite-project/graphite-web#1945]
After running setup.py for both graphite-web and carbon, I ran  `PYTHONPATH=/opt/graphite/webapp/ django-admin.py migrate --settings=graphite.settings --run-syncdb --noinput`. I get this error.

Traceback (most recent call last):
  File "/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/urls.py", line 22, in <module>
    url('^render/?', include('graphite.render.urls')),
  File "/usr/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/urls.py", line 16, in <module>
    from . import views
  File "/opt/graphite/webapp/graphite/render/views.py", line 34, in <module>
    from graphite.remote_storage import extractForwardHeaders, prefetchRemoteData
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 3, in <module>
    from graphite.finders.remote import RemoteStore, prefetchRemoteData  # noqa # pylint: disable=unused-import
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 16, in <module>
    from graphite.readers.remote import RemoteReader
ImportError: No module named readers.remote

I couldn't find anything about this.

System Details:
CentOS7
Python 2.7.5
Django 1.9.13
txAMQP (0.4)
whisper (1.1.0)
django-tagging (0.4.3)
cairocffi (0.8.0)
pytz (2017.2)
scandir (1.5)
Twisted (17.1.0)

**Comment by deniszh** [comment]
@hapx101 - are you using master? Try to use 1.0.x branch

@iksaif, could you please check ?

**Comment by hapx101** [comment]
@deniszh - Yes, I am using the master. Trying with 1.0.x branch.

**Comment by iksaif** [comment]
Can you try with https://github.com/graphite-project/graphite-web/pull/1946 ?

**Comment by deniszh** [comment]
@yesoreyeram - did #1946 fix problem for you?

**Comment by yesoreyeram** [comment]
yes @deniszh . Now it is working fine.

**Comment by deniszh** [comment]
Fixed now.
