### ISSUE TITLE
graphite-web 1.0.1 with django 1.9 

### ISSUE THREAD

**Issue by XiyuanHu** [graphite-project/graphite-web#1955]
Hi,
I'm using graphite-web 1.0.1 with carbon 1.0.0 and whisper 1.0.0 with custom storage finder. Django is 1.9. 
I can't sync db at all. Did not find anything useful online. Any suggestions?
PYTHONPATH=/opt/graphite/webapp/:/opt/graphite/webapp/graphite django-admin.py migrate --settings=local_settings  --run-syncdb

 RUN PYTHONPATH=/opt/graphite/webapp/:/opt/graphite/webapp/graphite django-admin.py migrate --settings=local_settings  --run-syncdb
 ---> Running in 0709ba3584b5
[91mTraceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 398, in execute
[0m[91m    self.check()
[0m[91m  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 426, in check
[0m[91m    [0m[91minclude_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 9, in check_url_config
    resolver = get_resolver()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 100, in wrapper
[0m[91m    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 151, in get_resolver
[0m[91m    urlconf = settings.ROOT_URLCONF
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[0m[91m    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
[0m

**Comment by deniszh** [comment]
Hi @XiyuanHu ,
Try to run `PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb` as [documentation](https://graphite.readthedocs.io/en/latest/config-database-setup.html) suggests.
