### ISSUE TITLE
KeyError: 'en-us' on current master

### ISSUE THREAD

**Issue by ybizeul** [graphite-project/graphite-web#1971]
```
[Thu Jun 22 02:45:03.039279 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773] mod_wsgi (pid=822): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Thu Jun 22 02:45:03.039453 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773] Traceback (most recent call last):
[Thu Jun 22 02:45:03.039540 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/whitenoise/base.py", line 66, in __call__
[Thu Jun 22 02:45:03.039624 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self.application(environ, start_response)
[Thu Jun 22 02:45:03.039689 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
[Thu Jun 22 02:45:03.039764 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     response = self.get_response(request)
[Thu Jun 22 02:45:03.039828 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
[Thu Jun 22 02:45:03.039901 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     response = self._middleware_chain(request)
[Thu Jun 22 02:45:03.039965 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner
[Thu Jun 22 02:45:03.040053 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     response = response_for_exception(request, exc)
[Thu Jun 22 02:45:03.040121 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
[Thu Jun 22 02:45:03.040174 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Thu Jun 22 02:45:03.040215 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
[Thu Jun 22 02:45:03.040262 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     extra={'status_code': 500, 'request': request},
[Thu Jun 22 02:45:03.040302 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/lib/python2.7/logging/__init__.py", line 1186, in error
[Thu Jun 22 02:45:03.040348 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     self._log(ERROR, msg, args, **kwargs)
[Thu Jun 22 02:45:03.040387 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
[Thu Jun 22 02:45:03.040432 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     self.handle(record)
[Thu Jun 22 02:45:03.040472 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
[Thu Jun 22 02:45:03.040517 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     self.callHandlers(record)
[Thu Jun 22 02:45:03.040556 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
[Thu Jun 22 02:45:03.040602 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     hdlr.handle(record)
[Thu Jun 22 02:45:03.040641 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
[Thu Jun 22 02:45:03.040685 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     self.emit(record)
[Thu Jun 22 02:45:03.040724 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 119, in emit
[Thu Jun 22 02:45:03.040772 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     message = "%s\\n\\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
[Thu Jun 22 02:45:03.040812 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 334, in get_traceback_text
[Thu Jun 22 02:45:03.040859 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return t.render(c)
[Thu Jun 22 02:45:03.040897 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 207, in render
[Thu Jun 22 02:45:03.040943 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self._render(context)
[Thu Jun 22 02:45:03.040982 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
[Thu Jun 22 02:45:03.041027 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self.nodelist.render(context)
[Thu Jun 22 02:45:03.041066 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 990, in render
[Thu Jun 22 02:45:03.041112 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     bit = node.render_annotated(context)
[Thu Jun 22 02:45:03.041152 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
[Thu Jun 22 02:45:03.041198 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self.render(context)
[Thu Jun 22 02:45:03.041237 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 216, in render
[Thu Jun 22 02:45:03.041290 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     nodelist.append(node.render_annotated(context))
[Thu Jun 22 02:45:03.041330 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
[Thu Jun 22 02:45:03.041396 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self.render(context)
[Thu Jun 22 02:45:03.041444 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1040, in render
[Thu Jun 22 02:45:03.041491 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     output = self.filter_expression.resolve(context)
[Thu Jun 22 02:45:03.041528 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 736, in resolve
[Thu Jun 22 02:45:03.041569 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     new_obj = func(obj, *arg_vals)
[Thu Jun 22 02:45:03.041605 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/template/defaultfilters.py", line 253, in stringformat
[Thu Jun 22 02:45:03.041648 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return ("%" + six.text_type(arg)) % value
[Thu Jun 22 02:45:03.041683 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 79, in __repr__
[Thu Jun 22 02:45:03.041726 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return repr(self.__cast())
[Thu Jun 22 02:45:03.041761 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 131, in __cast
[Thu Jun 22 02:45:03.041803 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self.__text_cast()
[Thu Jun 22 02:45:03.041838 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 119, in __text_cast
[Thu Jun 22 02:45:03.041880 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return func(*self.__args, **self.__kw)
[Thu Jun 22 02:45:03.041916 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 91, in reverse
[Thu Jun 22 02:45:03.041958 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
[Thu Jun 22 02:45:03.041995 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 438, in _reverse_with_prefix
[Thu Jun 22 02:45:03.042037 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     possibilities = self.reverse_dict.getlist(lookup_view)
[Thu Jun 22 02:45:03.042073 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]   File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 335, in reverse_dict
[Thu Jun 22 02:45:03.042115 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773]     return self._reverse_dict[language_code]
[Thu Jun 22 02:45:03.042160 2017] [wsgi:error] [pid 822] [remote 127.0.0.1:24773] KeyError: 'en-us'
```

**Comment by brutasse** [comment]
I remember having this error when working on https://github.com/graphite-project/graphite-web/pull/1960, but I'm pretty sure I fixed it.

What Django version do you have? Is your 'current master' less than 6 days old?

**Comment by ybizeul** [comment]
Thanks, looks good now, I think it was regression from my work trying to troubleshoot #667

**Comment by Haelium** [comment]
Getting what looks like a similar issue using django 1.11.10, graphite-web-1.1.2, and uWSGI (2.0.17)  on CentOS 7. Am using pypy 5.0.1, all packages installed via pip.

```
From cffi callback <function uwsgi_pypy_wsgi_handler at 0x00007fbf1bf83268>:
Traceback (most recent call last):
  File "c callback", line 472, in uwsgi_pypy_wsgi_handler
  File "/usr/lib64/pypy-5.0.1/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/lib64/pypy-5.0.1/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/lib64/pypy-5.0.1/lib-python/2.7/logging/__init__.py", line 1204, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/pypy-5.0.1/lib-python/2.7/logging/__init__.py", line 1297, in _log
    self.handle(record)
  File "/usr/lib64/pypy-5.0.1/lib-python/2.7/logging/__init__.py", line 1307, in handle
    self.callHandlers(record)
  File "/usr/lib64/pypy-5.0.1/lib-python/2.7/logging/__init__.py", line 1347, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/pypy-5.0.1/lib-python/2.7/logging/__init__.py", line 770, in handle
    self.emit(record)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/utils/log.py", line 119, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "/usr/lib64/pypy-5.0.1/site-packages/django/views/debug.py", line 334, in get_traceback_text
    return t.render(c)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/template/defaultfilters.py", line 255, in stringformat
    return ("%" + six.text_type(arg)) % value
  File "/usr/lib64/pypy-5.0.1/site-packages/django/utils/functional.py", line 79, in __repr__
    return repr(self.__cast())
  File "/usr/lib64/pypy-5.0.1/site-packages/django/utils/functional.py", line 131, in __cast
    return self.__text_cast()
  File "/usr/lib64/pypy-5.0.1/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/lib64/pypy-5.0.1/site-packages/django/urls/resolvers.py", line 439, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/usr/lib64/pypy-5.0.1/site-packages/django/urls/resolvers.py", line 335, in reverse_dict
    print "GOT HERE", language_code, self._reverse_dict[language_code]
KeyError: 'en-us'
```

**Comment by AlexZzz** [comment]
Hi! Faced with similar issue:
```
Traceback (most recent call last):
  File "/opt/graphite/local/lib/python2.7/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/utils/log.py", line 119, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "/opt/graphite/local/lib/python2.7/site-packages/django/views/debug.py", line 334, in get_traceback_text
    return t.render(c)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/template/defaultfilters.py", line 255, in stringformat
    return ("%" + six.text_type(arg)) % value
  File "/opt/graphite/local/lib/python2.7/site-packages/django/utils/functional.py", line 79, in __repr__
    return repr(self.__cast())
  File "/opt/graphite/local/lib/python2.7/site-packages/django/utils/functional.py", line 131, in __cast
    return self.__text_cast()
  File "/opt/graphite/local/lib/python2.7/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/opt/graphite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 438, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 335, in reverse_dict
    return self._reverse_dict[language_code]
KeyError: 'en-us'
```
Django version 1.11.11, graphite-web 1.1.2, installed in virtualenv, with uwsgi 1.9.17.1-debian, ubuntu 14.04.

**Comment by AlexZzz** [comment]
Found solution: python 'requests' package was not installed.
