### ISSUE TITLE
Where is manage.py in 1.0.1?

### ISSUE THREAD

**Issue by devent** [graphite-project/graphite-web#1984]
Hello, from Graphite 0.9.15 I have the following commands:

```
# install graphite
RUN git clone -b 1.0.1 --depth 1 https://github.com/graphite-project/graphite-web.git /usr/local/src/graphite-web
WORKDIR /usr/local/src/graphite-web
RUN python ./setup.py install
ADD conf/opt/graphite/conf/*.conf /opt/graphite/conf/
ADD conf/opt/graphite/webapp/graphite/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
ADD conf/opt/graphite/webapp/graphite/app_settings.py /opt/graphite/webapp/graphite/app_settings.py
RUN python /opt/graphite/webapp/graphite/manage.py collectstatic --noinput
```

I wanted to upgrade to Graphite 1.0.1 but I see that the `manage.py` moved in the repository and is also not installed from `./setup.py install`.

```
# manage.py should be here in 1.0.1
RUN python /opt/graphite/webapp/manage.py collectstatic --noinput
python: can't open file '/opt/graphite/webapp/manage.py': [Errno 2] No such file or directory
```

- why didn't `./setup.py install` installed `manage.py`?
- do I need it?

Original setup:
https://github.com/hopsoft/docker-graphite-statsd

**Comment by deniszh** [comment]
You can use `django-admin` or `python -m django` instead  - see  https://docs.djangoproject.com/en/1.11/ref/django-admin/
Please also note that 1.0.1 supports Django 1.9, upcoming 1.0.2 should support 1.8 (current LTS) too and master supporting 1.8-1.11

**Comment by devent** [comment]
Thank you. But I still have problems and I can't find anything in Google.

```
Step 20/48 : RUN PYTHONPATH="/opt/graphite/webapp/" django-admin.py collectstatic --noinput --settings=graphite.settings
 ---> Running in e2f482ae6a94

Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named cli
The command '/bin/sh -c echo $PYTHONPATH;ls -l /opt/graphite/webapp/;PYTHONPATH="/opt/graphite/lib/:/opt/graphite/webapp/" django-admin.py collectstatic --noinput --settings=graphite.settings' returned a non-zero code: 1
../utils/Makefile.image:18: recipe for target '_build' failed
make: *** [_build] Error 1
```

**Comment by deniszh** [comment]
Looks like you're trying to build docker image. You can use official one now - https://hub.docker.com/r/graphiteapp/graphite-statsd/
