### ISSUE TITLE
URL_PREFIX does not work (404)

### ISSUE THREAD

**Issue by pekuhn** [graphite-project/graphite-web#2000]
Hi,

I am trying to change the url of graphite-web to '/graphite'. I changes the follwing configs: 
First I uncommented URL_PREFIX = 'graphite' in /opt/graphite/webapp/graphite/local_settings.py
Then I changed one line in /etc/apache2/sites-available/apache2-graphite.conf:
WSGIScriptAlias / /usr/share/graphite-web/graphite.wsgi  
to  
WSGIScriptAlias /graphite /usr/share/graphite-web/graphite.wsgi/graphite
This does produce the following error: 
'Not Found
The requested URL /composer/ was not found on this server.'
As far as I can see this seems to be an issue with the url_prefix-function. What, if anything, am I doing wrong?
Thanks for your help!

**Comment by deniszh** [comment]
Which Graphite version are you using? Looks like quite old, new versions are using '/static' prefix.
For modern version, you need to set e.g.
```
STATIC_URL = '/static/'
URL_PREFIX = '/graphite'
```
Then you need to make your webserver to serve static files from static_url above, e.g.
```
Alias /static/ /opt/graphite/static
```

**Comment by zyzwizki** [comment]
Thanks,

you were right abou the version. I used pip to install 1.1
When running 
`django-admin.py  migrate --settings=graphite.settings --run-syncdb`
I get the following error: `django-admin.py migrate: error: unrecognized arguments: --run-syncdb`
When leaving out `--run-syncdb`
I get:
```
Operations to perform:
  Synchronize unmigrated apps: render, staticfiles, whitelist, metrics, composer, browser
  Apply all migrations: account, sessions, admin, auth, url_shortener, contenttypes, dashboard, events, tagging
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/usr/local/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists
```

As I am neither familiar with python, nor with django I dont really know what to make of this...

**Comment by williamleuschner** [comment]
I'm having a similar issue when running `django-admin.py migrate --settings=graphite.settings --run-syncdb`.
Here is the traceback on my end:
```Operations to perform:
  Synchronize unmigrated apps: account, cli, render, whitelist, metrics, url_shortener, dashboard, composer, events, browser
  Apply all migrations: admin, contenttypes, tagging, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib64/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "django_content_type" already exists```

**Comment by GowthamShanmugam** [comment]
even I am facing the same issue while migration, what is the solution for this?

**Comment by deniszh** [comment]
That's not a Graphite issue per se, that's a Django issue. `django_content_type` is not specific Graphite table, that's common Django table. So, you need to skip migrations, but not all, just initial - you need to use `--fake-initial` instead of `--fake` - check https://stackoverflow.com/a/29760818/1139639 and https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---fake-initial
