### ISSUE TITLE
pip install graphite fail

### ISSUE THREAD

**Issue by CCoruble** [graphite-project/graphite-web#2003]
Hi,

I might have missed something but I followed, some tutorials like this one : https://mespotesgeek.fr/fr/des-graphiques-sur-shinken-via-graphite/
and the shinken tuto on how install graphite and I got an error when using pip to install graphite on both cases.

**Config :**
Ubuntu 16.04
pip 8.1.1

**Command tested** (with sudo): 
pip install https://github.com/graphite-project/graphite-web/tarball/master
pip install graphite-web

**Error message:**
```
The directory '/home/itdept/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/itdept/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/graphite-project/graphite-web/tarball/master
  Downloading https://github.com/graphite-project/graphite-web/tarball/master (1.4MB)
    100% |████████████████████████████████| 1.4MB 411kB/s
Requirement already satisfied: Django<1.11.99,>=1.8 in ./.local/lib/python2.7/site-packages (from graphite-web==1.1.0)
Collecting django-tagging==0.4.3 (from graphite-web==1.1.0)
  Downloading django_tagging-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: pytz in ./.local/lib/python2.7/site-packages (from graphite-web==1.1.0)
Collecting pyparsing (from graphite-web==1.1.0)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 1.8MB/s
Collecting cairocffi (from graphite-web==1.1.0)
  Downloading cairocffi-0.8.0.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 3.8MB/s
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ft3Nyc/cairocffi/setup.py", line 44, in <module>
        extras_require={'xcb': ['xcffib>=0.3.2']},
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/dist.py", line 336, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/dist.py", line 419, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/itdept/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/itdept/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1126, in best_match
        return self.obtain(req, installer)
      File "/home/itdept/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1138, in obtain
        return installer(requirement)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/dist.py", line 491, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/itdept/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ft3Nyc/cairocffi/
```

I already installed the dependencies, as writted in the error message, but never could install graphite-web ...

This might be a known error or something obvious to you but didn't find out why it crashed on this step.

Thank you for helping,
Regards

**Comment by deniszh** [comment]
The real error is quite hidden, it is:
```
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
```
Try to install dev package - `libffi-dev` on Debian/Ubuntu.

**Comment by CCoruble** [comment]
Hello,

Thank you for answering so fast ! 

I did "sudo apt-get install libffi-dev" and it worked !

Log of the installation :
```
Collecting https://github.com/graphite-project/graphite-web/tarball/master
  Downloading https://github.com/graphite-project/graphite-web/tarball/master (1.4MB)
    100% |████████████████████████████████| 1.4MB 386kB/s
Requirement already satisfied (use --upgrade to upgrade): Django<1.11.99,>=1.8 in /usr/lib/python2.7/dist-packages (from graphite-web===1.1.0)
Collecting django-tagging==0.4.3 (from graphite-web===1.1.0)
  Using cached django_tagging-0.4.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/dist-packages (from graphite-web===1.1.0)
Collecting pyparsing (from graphite-web===1.1.0)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting cairocffi (from graphite-web===1.1.0)
  Using cached cairocffi-0.8.0.tar.gz
Collecting urllib3 (from graphite-web===1.1.0)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.5MB/s
Collecting scandir (from graphite-web===1.1.0)
  Downloading scandir-1.5.tar.gz
Collecting cffi>=1.1.0 (from cairocffi->graphite-web===1.1.0)
  Downloading cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl (392kB)
    100% |████████████████████████████████| 399kB 951kB/s
Collecting pycparser (from cffi>=1.1.0->cairocffi->graphite-web===1.1.0)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 1.6MB/s
Building wheels for collected packages: cairocffi, scandir, pycparser
  Running setup.py bdist_wheel for cairocffi ... done
  Stored in directory: /root/.cache/pip/wheels/ed/67/1b/c2e45826aef8e76b0942c2c1e62120da72259a5c1e46a3d02d
  Running setup.py bdist_wheel for scandir ... done
  Stored in directory: /root/.cache/pip/wheels/47/af/a2/eb591a17e9709a17d8b53696f6ad89914a05eaf9c091f36e18
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built cairocffi scandir pycparser
Installing collected packages: django-tagging, pyparsing, pycparser, cffi, cairocffi, urllib3, scandir, graphite-web
  Found existing installation: django-tagging 0.4
    Not uninstalling django-tagging at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for graphite-web ... done
Successfully installed cairocffi-0.8.0 cffi-1.10.0 django-tagging-0.4.3 graphite-web pycparser-2.18 pyparsing-2.2.0 scandir-1.5 urllib3-1.22
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I'm far from being an ubuntu pro so I might post issues again if I see problems.
Thank you again for solving this one !
Regards.
