### ISSUE TITLE
No functions under list of functions

### ISSUE THREAD

**Issue by vbichov** [graphite-project/graphite-web#2033]
There was a list of functions and their documentation and now it's gone: 

http://graphite.readthedocs.io/en/latest/functions.html

Please help!!!

**Comment by cbowman0** [comment]
For now, use the docs from the 1.0.2 release: http://graphite.readthedocs.io/en/1.0.2/functions.html

**Comment by deniszh** [comment]
Huh? Did we lose functions on master again? wtf...
Do you know something  about it, @cbowman0 ?
Or anydody? @iksaif @DanCech ?
Tests for docs looks perfect... *sigh*

**Comment by cbowman0** [comment]
I do not know how the docs work.  I can look later unless someone else gets to it.

**Comment by DanCech** [comment]
I'll take a look

**Comment by deniszh** [comment]
Strange. I just try to rebuild docs locally - it worked fine:
```
[dzhdanov:~/git/graphite-web] master+ ± mkdir docs-html
[dzhdanov:~/git/graphite-web] master+ ± pip2 install Sphinx sphinx_rtd_theme scandir
Requirement already satisfied: Sphinx in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: sphinx_rtd_theme in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: scandir in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: imagesize in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: docutils>=0.11 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: typing; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python2.7/site-packages (from Sphinx)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python2.7/site-packages (from babel!=2.0,>=1.3->Sphinx)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx)
[dzhdanov:~/git/graphite-web] master+ ± sphinx-build -b html docs docs-html
Running Sphinx v1.6.3
Could not import graphite.local_settings, using defaults!
/Users/dzhdanov/git/graphite-web/webapp/graphite/settings.py:286: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
WARNING: while setting up extension conf.py: directive 'autofunction' is already registered, it will be overridden
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 47 source files that are out of date
updating environment: 47 added, 0 changed, 0 removed
reading sources... [100%] who-is-using
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] who-is-using
generating indices... genindex py-modindex
writing additional pages... search
copying images... [100%] ../webapp/content/img/overview.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
[dzhdanov:~/git/graphite-web] master+* ± ls -al docs-html/functions.html
-rw-r--r--  1 dzhdanov  dzhdanov  115571 Sep 10 21:34 docs-html/functions.html
```

**Comment by deniszh** [comment]
Travis job for docs looks fine - https://travis-ci.org/graphite-project/graphite-web/jobs/273504741
But TBH I have no idea howit comes to https://graphite.readthedocs.io/
Will ask Jason :)

**Comment by DanCech** [comment]
Yeah same here, might be a transient problem with whatever builds docs for the site? I just pushed a minor docs tweak to master so I guess we'll see if the build is still failing

**Comment by DanCech** [comment]
Appears to be an issue with importing scandir:
```
/home/docs/checkouts/readthedocs.org/user_builds/graphite/checkouts/latest/docs/functions.rst:17: WARNING: autodoc: failed to import module u'graphite.render.functions'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/graphite/render/functions.py", line 33, in <module>
    from graphite.storage import STORE
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/graphite/storage.py", line 17, in <module>
    from graphite.finders.utils import FindQuery
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/graphite/finders/utils.py", line 6, in <module>
    from graphite.readers.utils import wait_for_result, FetchInProgress
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/graphite/readers/__init__.py", line 3, in <module>
    from graphite.readers.whisper import WhisperReader, GzippedWhisperReader  # noqa # pylint: disable=unused-import
  File "/home/docs/checkouts/readthedocs.org/user_builds/graphite/envs/latest/lib/python2.7/site-packages/graphite/readers/whisper.py", line 9, in <module>
    from scandir import scandir, stat  # noqa # pylint: disable=unused-import
ImportError: No module named scandir
```
from https://readthedocs.org/projects/graphite/builds/5956726/
Digging into what it will take to make that available on readthedocs

**Comment by DanCech** [comment]
Found it, readthedocs uses `docs/requirements.txt` which doesn't include `scandir`.  I just added it, hopefully that'll do the trick.

**Comment by DanCech** [comment]
All fixed 👍
