### ISSUE TITLE
Table 'graphite.auth_user' doesn't exist

### ISSUE THREAD

**Issue by leochen4891** [graphite-project/graphite-web#2059]
I'm getting the following error message when installing graphite 1.0.2 with django 1.9.13
I don't see this error if downgrade django to 1.7.10

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/opt/graphite/webapp/graphite/user_util.py", line 25, in getProfile
    return default_profile()
  File "/opt/graphite/webapp/graphite/user_util.py", line 41, in default_profile
    'password': '!'})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'graphite.auth_user' doesn't exist")
```

I'm not able to find the root cause of this error.
Any idea or suggestion is appreciated.

**Comment by DanCech** [comment]
Did you run `manage.py migrate` ?

**Comment by leochen4891** [comment]
No, I'm installing graphite on a VM. 
Strangely, I don't find manage.py anywhere on the machine.

**Comment by DanCech** [comment]
It should be at `/opt/graphite/webapp/manage.py`

**Comment by DanCech** [comment]
You may also want to try `PYTHONPATH=/opt/graphite/webapp django-admin.py syncdb --settings=graphite.settings`  If you're using a virtualenv then you'll need to have that activated.

**Comment by leochen4891** [comment]
`PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb` works for me
Thanks @DanCech
