### ISSUE TITLE
internal server error : ordinal not in range

### ISSUE THREAD

**Issue by YouriAndropov** [graphite-project/graphite-web#2108]
I'm using graphite with jmeter, sending tests results during the run.
Then I can have nice curves in grafana.

But it seems graphite has some problems with API requests (/graphite/render) using non-standard ASCII characters.

I got this stack trace in apache, and get an HTTP 400 or 500 in grafana.

```
[wsgi:error] Internal Server Error: /graphite/render
[wsgi:error] Traceback (most recent call last):
[wsgi:error]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[wsgi:error]     response = get_response(request)
[wsgi:error]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[wsgi:error]     response = self._get_response(request)
[wsgi:error]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[wsgi:error]     response = self.process_exception_by_middleware(e, request)
[wsgi:error]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[wsgi:error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/views.py", line 130, in renderView
[wsgi:error]     seriesList = evaluateTarget(requestContext, target)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 8, in evaluateTarget
[wsgi:error]     result = evaluateTokens(requestContext, tokens)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
[wsgi:error]     return evaluateTokens(requestContext, tokens.expression, replacements)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 54, in evaluateTokens
[wsgi:error]     args = [evaluateTokens(requestContext, arg, replacements) for arg in tokens.call.args]
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 29, in evaluateTokens
[wsgi:error]     return evaluateTokens(requestContext, tokens.expression, replacements)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/evaluator.py", line 45, in evaluateTokens
[wsgi:error]     return fetchData(requestContext, expression)
[wsgi:error]   File "/opt/graphite/webapp/graphite/util.py", line 229, in wrapped_f
[wsgi:error]     res = f(*args, **kwargs)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/datalib.py", line 262, in fetchData
[wsgi:error]     seriesList = _fetchData(pathExpr, startTime, endTime, now, requestContext, seriesList)
[wsgi:error]   File "/opt/graphite/webapp/graphite/util.py", line 229, in wrapped_f
[wsgi:error]     res = f(*args, **kwargs)
[wsgi:error]   File "/opt/graphite/webapp/graphite/render/datalib.py", line 156, in _fetchData
[wsgi:error]     matching_nodes = [node for node in STORE.find(pathExpr, startTime, endTime, local=requestContext['localOnly'])]
[wsgi:error]   File "/opt/graphite/webapp/graphite/storage.py", line 44, in find
[wsgi:error]     for match in self.find_all(query, headers):
[wsgi:error]   File "/opt/graphite/webapp/graphite/storage.py", line 96, in find_all
[wsgi:error]     for node in nodes:
[wsgi:error]   File "/opt/graphite/webapp/graphite/finders/standard.py", line 31, in find_nodes
[wsgi:error]     for absolute_path in self._find_paths(root_dir, pattern_parts):
[wsgi:error]   File "/opt/graphite/webapp/graphite/finders/standard.py", line 117, in _find_paths
[wsgi:error]     for match in self._find_paths(absolute_path, patterns):
[wsgi:error]   File "/opt/graphite/webapp/graphite/finders/standard.py", line 117, in _find_paths
[wsgi:error]     for match in self._find_paths(absolute_path, patterns):
[wsgi:error]   File "/opt/graphite/webapp/graphite/finders/standard.py", line 83, in _find_paths
[wsgi:error]     entries = [x.name for x in scandir(current_dir)]
[wsgi:error] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)
```

Any solution ?

**Comment by deniszh** [comment]
Unfortunately current graphite-web doesn't support non-ascii metrics. Maybe we can make a quick fix for standart finder? /cc @piotr1212 @brutasse

**Comment by YouriAndropov** [comment]
graphite-web doesn't support non-ASCII characters, but carbon-cache does.
This is quite inconsistent.

**Comment by piotr1212** [comment]
@YouriAndropov Yes it is. We would prefer to add support to Graphite-web than to just disable it in carbon. To support utf-8 properly would take a lot of time. Maybe it would be better to fix separate issues incrementally.
