### ISSUE TITLE
auth_user.last_login may not be NULL

### ISSUE THREAD

**Issue by yuribit** [graphite-project/graphite-web#2214]
Hi!
I am trying to run graphite-web from virtualenv using Python 2.7 on a CentOS 6.5 server.
I built the RPM from source. I am using LDAP auth and `USE_REMOTE_USER_AUTHENTICATION = True`

When I try to login I get the following error:

```==> /opt/graphite-web-venv/graphite/storage/log/webapp/apache-graphite-error.log <==
[Fri Jan 26 17:01:57 2018] [error] Internal Server Error: /
[Fri Jan 26 17:01:57 2018] [error] Traceback (most recent call last):
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Fri Jan 26 17:01:57 2018] [error]     response = get_response(request)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/utils/deprecation.py", line 138, in __call__
[Fri Jan 26 17:01:57 2018] [error]     response = self.process_request(request)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 91, in process_request
[Fri Jan 26 17:01:57 2018] [error]     user = auth.authenticate(request, remote_user=username)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
[Fri Jan 26 17:01:57 2018] [error]     user = _authenticate_with_backend(backend, backend_path, request, credentials)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
[Fri Jan 26 17:01:57 2018] [error]     return backend.authenticate(*args, **credentials)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 147, in authenticate
[Fri Jan 26 17:01:57 2018] [error]     UserModel.USERNAME_FIELD: username
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
[Fri Jan 26 17:01:57 2018] [error]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
[Fri Jan 26 17:01:57 2018] [error]     return self._create_object_from_params(lookup, params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
[Fri Jan 26 17:01:57 2018] [error]     six.reraise(*exc_info)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
[Fri Jan 26 17:01:57 2018] [error]     obj = self.create(**params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
[Fri Jan 26 17:01:57 2018] [error]     obj.save(force_insert=True, using=self.db)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 80, in save
[Fri Jan 26 17:01:57 2018] [error]     super(AbstractBaseUser, self).save(*args, **kwargs)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
[Fri Jan 26 17:01:57 2018] [error]     force_update=force_update, update_fields=update_fields)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
[Fri Jan 26 17:01:57 2018] [error]     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
[Fri Jan 26 17:01:57 2018] [error]     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
[Fri Jan 26 17:01:57 2018] [error]     using=using, raw=raw)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
[Fri Jan 26 17:01:57 2018] [error]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
[Fri Jan 26 17:01:57 2018] [error]     return query.get_compiler(using=using).execute_sql(return_id)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
[Fri Jan 26 17:01:57 2018] [error]     cursor.execute(sql, params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
[Fri Jan 26 17:01:57 2018] [error]     return super(CursorDebugWrapper, self).execute(sql, params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Fri Jan 26 17:01:57 2018] [error]     return self.cursor.execute(sql, params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
[Fri Jan 26 17:01:57 2018] [error]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Fri Jan 26 17:01:57 2018] [error]     return self.cursor.execute(sql, params)
[Fri Jan 26 17:01:57 2018] [error]   File "/opt/graphite-web-venv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
[Fri Jan 26 17:01:57 2018] [error]     return Database.Cursor.execute(self, query, params)
[Fri Jan 26 17:01:57 2018] [error] IntegrityError: auth_user.last_login may not be NULL
```

I found [this](https://stackoverflow.com/questions/30556593/creating-users-in-django-not-null-constraint-failed-auth-user-last-login) on the web, tried to run the migrations again but didn't work. 
Has anyone had the same issue before? Any ideas?

Thanks.

**Comment by deniszh** [comment]
Hi @yuribit,
Did you configure remote user auth properly - https://docs.djangoproject.com/en/2.0/howto/auth-remote-user/ ?
Did your web server really set REMOTE_USER variable?

**Comment by yuribit** [comment]
@deniszh, thank you so much! I was missing the `MIDDLEWARE` and `AUTHENTICATION_BACKENDS` settings.
Closing this.
