### ISSUE TITLE
Unable to visualize available metric points in a whisper file

### ISSUE THREAD

**Issue by raghavan20** [graphite-project/graphite-web#2222]
Given a whisper file with the archive `(1s:14d)`

```
whisper-info.py direction.wsp 
maxRetention: 1209600
xFilesFactor: 0.5
aggregationMethod: average
fileSize: 14515228

Archive 0
retention: 1209600
secondsPerPoint: 1
points: 1209600
size: 14515200
offset: 28
```

having data points for 16 July 2017.
```
...
321184: 1500199984,          0
321187: 1500199987,          0
321190: 1500199990,          0
321193: 1500199993,          1
321198: 1500199998,          0
...

$ for i in 1500199984 1500199987 1500199990 1500199993 1500199998 ; do  echo "$i - `date -d @$i`"; done
1500199984 - Sun 16 Jul 11:13:04 BST 2017
1500199987 - Sun 16 Jul 11:13:07 BST 2017
1500199990 - Sun 16 Jul 11:13:10 BST 2017
1500199993 - Sun 16 Jul 11:13:13 BST 2017
1500199998 - Sun 16 Jul 11:13:18 BST 2017
```
When viewing the same data from `graphite-web`, there are not results.

```
http://localhost/render?from=10%3A00_20170716&until=14%3A00_20170716&width=400&height=250&target=direction&_uniq=0.24008196147297345&title=DEVICE_3375.direction&rawData=1

empty result
```

Can someone please explain why this happens? Is graphite-web performing some kind of aggregation and considering most data points as null? For some time durations (over several seconds) in the whisper file, all available slots are not filled.

**Comment by DanCech** [comment]
Right now whisper always calculates available data from the current time, so it won't be able to retrieve data older than 14 days.  You can work around it via the render API if you're running master or the 1.1.x branch by passing `now=14%3A00_20170716` in your render request.

**Comment by raghavan20** [comment]
Sorry, I do not understand your comment completely as I managed to read data points in the whisper file using `whisper-dump` utility.

```
# Searching for interested data points based on timestamp
whisper-dump.py direction.wsp  | grep 150019
```

why do you say that i cannot visualize data older than 14 days?

**Comment by deniszh** [comment]
@raghavan20 : You have single `1s:14d` archive in whisper. That means "Store data every 1 second and keep last 14 days of data". So, Graphite by default takes 14 days from current date and renders data - but there's no data for last 14 days - then it shows nothing.
The proper solution for that situation - change your storage schema. If you need to keep more that 14 days of data, please change it accordingly  - or increase retention or add another archive.
But if you need to just render data for that period once - then you can trick Graphite to think that today is 16 july 2017 - add  `now=14%3A00_20170716` to your render request, but it will work only in Graphite 1.1 or newer.

**Comment by raghavan20** [comment]
thanks @deniszh  for the answer. our original intention was to create a backup for a  historic event and visualize later in time. i was thinking if i just copied the whisper file immediately soon after the interested event occurred and assuming that no new data went in ( hence no aggregation happens ), i should be able to visualize historic data. i guess we should have set retention like `1s:2y` if we wanted to visualize data at `1s` granularity in the next two years. i originally did not think about it considering that all data except the interested event duration is waste of file space.

but from what you have explained `graphite-web` would not work like that. the amount of data that can be visualized from whisper files is based on `archives and points`. now given that i have the whisper file which holds 14 days of historical data, is it possible to run through some tools so that i can visualize from Graphite apart from the `now` query parameter supported with `1.1+` version of `graphite-web` application?

**Comment by raghavan20** [comment]
Hi, I tried to run the latest version of `graphite-web` so that i can use the `now` query parameter. 

I believe I am using `1.1+` of `graphite-web` based on the below output. I am running a Docker container from `graphiteapp/graphite-statsd`.


```
# ls /opt/graphite/lib/* | grep py2
lib/carbon-1.1.1-py2.7.egg-info
```

Exception while viewing the direction.wsp file from `graphite/exception.log`
```
 2018-02-05,15:54:52.884 :: Exception encountered in <GET http://localhost/render?from=09%3A00_20170713&until=17%3A00_20170717&width=400&height=250&target=DEVICE_3375.direction&_uniq=0.9074819190254235&title=DEVICE_3375.direction>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 15, in evaluateTarget
    prefetchData(requestContext, pathExpressions)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 255, in prefetchData
    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
  File "/opt/graphite/webapp/graphite/storage.py", line 137, in fetch
    raise Exception("Fetch for %s failed: %s" % (str(patterns), str(job.exception)))
Exception: Fetch for [u'DEVICE_3375.direction'] failed: 'NoneType' object is not iterable

```

**Comment by deniszh** [comment]
That's strange. Are you sure that you mount all volumes properly? Can you render other targets? (e.g. carbon or statsd statistics)

**Comment by DanCech** [comment]
I've been able to duplicate this error when the whisper file exists but `whisper.fetch` returns `None`, will open a PR to fix that shortly
