### ISSUE TITLE
Unable to find the graphite.db file

### ISSUE THREAD

**Issue by DineshGuptaa** [graphite-project/graphite-web#2227]
Hello,
 I am novice user for graphite. I have started installation but stuck in the middle because of  'graphite.db' is missing form storage location. There is no such file.

Please help me where I can find it or how should I create with default value for graphite.

Regards,
Dinesh Gupta

**Comment by deniszh** [comment]
Hello @DineshGuptaa,
You need to set up Django database for Graphite. Please see documentation - https://graphite.readthedocs.io/en/latest/config-database-setup.html
```
To set up a new database and create the initial schema, run:

PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
```

**Comment by DineshGuptaa** [comment]
Hello @deniszh  
Thanks for quick reply :-)
While running said command then getting below error:

django-admin.py: command not found

Please let me know what I need to do.

Regards,
Dinesh

**Comment by 6d6178** [comment]
You might need to use the absolute path to django-admin.py.
django-admin.py is most likely located at
`/usr/lib/python2.7/site-packages/django/bin/django-admin.py`
making the full commad
`PYTHONPATH=$GRAPHITE_ROOT/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb`

**Comment by Abid1986** [comment]
I am getting below error  PYTHONPATH=$GRAPHITE_ROOT/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb
/usr/lib/python2.7/site-packages/graphite/settings.py:249: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib64/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/tagging/admin.py", line 3, in <module>
    from tagging.forms import TagAdminForm
  File "/usr/lib/python2.7/site-packages/tagging/forms.py", line 11, in <module>
    class TagAdminForm(forms.ModelForm):
  File "/usr/lib64/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagAdminForm needs updating.

**Comment by deniszh** [comment]
@Abid1986 : which version of django are you using?

**Comment by 6d6178** [comment]
> Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
from django.contrib.contenttypes import generic

@Abid1986 This is just a guess, but judging by the warning you are using Django < 1.9
You could update to the latest version and see if it resolves it.
`pip install "django<2"`

**Comment by Abid1986** [comment]
Currently i am using Django 1.11  and still getting the below error.

[root@localhost graphite]# django-admin.py version
1.11
[root@localhost graphite]# PYTHONPATH=/opt/graphite/webapp /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/events/models.py", line 4, in <module>
    from tagging.models import Tag
  File "/usr/lib/python2.7/site-packages/tagging/models.py", line 10, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic

**Comment by deniszh** [comment]
@Abid1986 
You probably using old `django-tagging` packgage, you should use v0.4.6 - https://github.com/graphite-project/graphite-web/blob/master/requirements.txt#L43

**Comment by Abid1986** [comment]
I reinstalled django-tagging again with latest version.It worked.
Many thanks :)

**Comment by 6d6178** [comment]
@deniszh This one is resolved too.
