### ISSUE TITLE
Tags autoComplete timing-out on clustered setup (infinite loop!)

### ISSUE THREAD

**Issue by Quentin-M** [graphite-project/graphite-web#2243]
Hi there,

I am using a graphite cluster with 4 carbon-cache processes, on 4 different nodes, that run alongside 4 graphite-web instances. Fronting those, 2 cache-relay instances.

When starting to type a query in Grafana (first node field), Grafana issues two API calls:
- `metrics/find?from=X&until=Y&query=*`
- `tags/autoComplete/tags` (or `tags/autoComplete/tags?tagPrefix=%2A&limit=100`)

However, it looks like something is really wrong with the tags request. First of all, the request takes forever and eventually time-out. But also, after a few attempts in grafana, the logs start spamming with timeouts for tags and tracebacks reading the tags from the other servers (see below), and it keeps going forever, even though no more requests are being made by grafana whatsoever. It seems that there is an endless loop somehow, like if `local=1` was not respected, or something along those lines. Then indeed, the web servers stops being able to even respond to `metrics/find` requests.

However, if in Grafana, we set the graphite version to <1.1, no `tags/autoComplete/tags` queries are made, and everything works wonderfully: auto-completion is snappy and graphs are showing perfectly.

Furthermore, when curling a single time the `tags/autoComplete/tags` API endpoint (see below), the logs go bonkers yet again, and basically never stops hard trying. According to the logs below, it'd seem like, indeed, `local=1` (as well as the msgpack`) parameters are missing from the queries, which would create an infinite loop?

```
curl 'localhost:8080/tags/autoComplete/tags?tagPrefix=%2A&limit=100' 
```

```
2018-02-26,07:54:21.246 :: RemoteFinder[graphite-cache-3:8080] Error response 500 from http://graphite-cache-3.graphite-cache.dev.svc.cluster.local:8080/tags/autoComplete/tags?tagPrefix=%2A&limit=100
NoneType: None
2018-02-26,07:54:21.405 :: RemoteFinder[graphite-cache-3:8080] Error response 500 from http://graphite-cache-3:8080/tags/autoComplete/tags?tagPrefix=%2A&limit=100
NoneType: None
2018-02-26,07:54:21.421 :: RemoteFinder[graphite-cache-2:8080] Error response 500 from http://graphite-cache:8080/tags/autoComplete/tags?tagPrefix=%2A&limit=100
NoneType: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 260, in request
    preload_content=False)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='graphite-cache-3', port=8080): Max retries exceeded with url: /tags/autoComplete/tags?tagPrefix=%2A&limit=100 (Caused by ReadTimeoutError("HTTPConnectionPool(host='graphite-cache-3.graphite-cache.dev.svc.cluster.local', port=8080): Read timed out. (read timeout=10)",))

==> /var/log/info.log <==
2018-02-26,07:41:43.888 :: Timed out after 10.000133s for tags for [] *
2018-02-26,07:41:44.004 :: Timed out after 10.000131s for tags for [] *
2018-02-26,07:41:44.309 :: Timed out after 10.000152s for tags for []
2018-02-26,07:41:51.993 :: Timed out after 10.000126s for tags for [] *
2018-02-26,07:41:52.070 :: Timed out after 10.000104s for tags for [] *
2018-02-26,07:41:52.078 :: Timed out after 10.000345s for tags for [] *
2018-02-26,07:41:52.140 :: Timed out after 10.000111s for tags for []
2018-02-26,07:41:52.141 :: Timed out after 10.000168s for tags for []
2018-02-26,07:41:52.215 :: Timed out after 10.000107s for tags for []
```  

### local_settings.py
```
CLUSTER_SERVERS=[<the three non-local carbon caches>?format=msgpack&local=1]
CARBONLINK_HOSTS=['127.0.0.1:7002']

FETCH_TIMEOUT=10
FIND_TIMEOUT=10

TAGDB='graphite.tags.redis.RedisTagDB'
TAGDB_REDIS_HOST='graphite-redis'
```

### carbon-cache.conf
```
[cache]
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_PORT = 2004
USE_INSECURE_UNPICKLER = False

CACHE_QUERY_INTERFACE = 127.0.0.1
CACHE_QUERY_PORT = 7002

DATABASE = whisper
ENABLE_LOGROTATION = False
MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 1000
MAX_CREATES_PER_MINUTE = inf
MIN_TIMESTAMP_RESOLUTION = 1

USE_FLOW_CONTROL = True
LOG_UPDATES = False
LOG_CREATES = False
LOG_CACHE_HITS = False
LOG_CACHE_QUEUE_SORTS = False
CACHE_WRITE_STRATEGY = sorted
WHISPER_AUTOFLUSH = False
WHISPER_FALLOCATE_CREATE = True

GRAPHITE_URL = http://127.0.0.1:8080
```

**Comment by DanCech** [comment]
The changes in #2244 seem like they should solve the problem you have currently where each host is trying to forward the tag requests to the others in an infinite loop.

An alternative approach if you're using a single redis tagdb for all 4 instances would be to specify `noTags=1` in your CLUSTER_HOST definitions, which will cause the graphite-web host that initially receives the query to resolve the tags and pass the resolved names to each of the non-local graphite-web instances.
