### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Deriul** [graphite-project/graphite-web#2282]
After the upgrade to Ubuntu 17.10 I keep getting the following message in web browser on port 81 of my graphite-web

"The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Apache/2.4.27 (Ubuntu) Server at sgo-vc03 Port 81"

/var/log/apache2/graphite-web_error.log shows the following data

```
[Fri Apr 20 15:57:55.988481 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578] mod_wsgi (pid=2424): Target WSGI script '/usr/share/graphite-web/graphite.wsgi' cannot be loaded as Python module.
[Fri Apr 20 15:57:55.988596 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578] mod_wsgi (pid=2424): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Fri Apr 20 15:57:55.989230 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578] Traceback (most recent call last):
[Fri Apr 20 15:57:55.989408 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/share/graphite-web/graphite.wsgi", line 5, in <module>
[Fri Apr 20 15:57:55.989426 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     django.setup()
[Fri Apr 20 15:57:55.989495 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 19, in setup
[Fri Apr 20 15:57:55.989512 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Apr 20 15:57:55.989536 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Fri Apr 20 15:57:55.989549 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     self._setup(name)
[Fri Apr 20 15:57:55.989570 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 43, in _setup
[Fri Apr 20 15:57:55.989582 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     self._wrapped = Settings(settings_module)
[Fri Apr 20 15:57:55.989603 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/local/lib/python3.6/dist-packages/django/conf/__init__.py", line 106, in __init__
[Fri Apr 20 15:57:55.989616 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Apr 20 15:57:55.989636 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Fri Apr 20 15:57:55.989648 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Apr 20 15:57:55.989668 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Fri Apr 20 15:57:55.989690 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Fri Apr 20 15:57:55.989713 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Fri Apr 20 15:57:55.989736 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Fri Apr 20 15:57:55.989760 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Fri Apr 20 15:57:55.989782 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Fri Apr 20 15:57:55.989804 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Fri Apr 20 15:57:55.989914 2018] [wsgi:error] [pid 2424:tid 139754987800320] [remote 10.5.50.9:54578] ModuleNotFoundError: No module named 'graphite'
```

I am pretty sure I missed something very essential but I don't see what exactly.

**Comment by piotr1212** [comment]
apache httpd cannot find the graphite python module. Most likely the PYTHONPATH variable in /usr/share/graphite-web/graphite.wsgi is incorrect.
