### ISSUE TITLE
No graphs found / No module graphite.settings found

### ISSUE THREAD

**Issue by nc-gsf** [graphite-project/graphite-web#2290]
### OS
CentOS 7

### Kernel
3.10.0-042stab127.2

### Python version
2.7.5

### Django version
1.11.13

### Icinga 2 version
r2.8.4-1

## Problem:
When I go to the Graphite tab in IcingaWeb2 it shows “No graphs found.” If I go to the `/metrics/expand?query=icinga2` site it shows `results [ ]` and the rest of the site is blank.

## What I tried

I tried to use the `PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py syncdb --settings=graphite.settings` command (I know the `syncdb` command is deprecated, I also tried it with the `migrate` command). And it tells me `ImportError: No module named graphite.settings`

If I start graphite up via `python /opt/graphite/bin/run-graphite-devel-server.py --port 8080 /opt/graphite/` it says:

```
You have 21 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): account, admin, auth, contenttypes, dashboard, events, sessions, tagging, tags, url_shortener.
Run 'python manage.py migrate' to apply them.

May 17, 2018 - 16:48:48
Django version 1.11.13, using settings 'graphite.settings'
```

But I don’t know where it takes the 'graphite.settings' from. There is no match if I try to locate it.

This is the ouptut if I go to localhost:8080:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/composer/views.py", line 35, in composer
    profile = getProfile(request)
  File "/opt/graphite/webapp/graphite/user_util.py", line 35, in getProfile
    return default_profile()
  File "/opt/graphite/webapp/graphite/user_util.py", line 51, in default_profile
    'password': '!'})
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'graphite.auth_user' doesn't exist")
```

Thanks is advance!

**Comment by gms1234** [comment]
After some fiddling around, I'm now able to access the Graphite Compose.

I think what fixed my problem was `pip install pysqlite`.

**Comment by deniszh** [comment]
@gms1234 
If you run
```
cd $GRAPHITE_ROOT/webapp
ls -al graphite/settings.py
```
what is saying?

**Comment by gms1234** [comment]
-rw-r--r-- 1 root root 10187 Apr 25 16:43 settings.py

**Comment by deniszh** [comment]
Sorry, @gms1234, but we're not supporting Icinga2, please try to ask support from Icinga community. I do not know how Icinga getting metrics and how it integrates with Graphite.
