### ISSUE TITLE
/metrics/find with remote backend fails when query parameter is empty

### ISSUE THREAD

**Issue by deejay1** [graphite-project/graphite-web#2292]
When doing a `/metrics/find/query=` Graphite-web 1.1.3 returns HTTP 500
```python
Traceback (most recent call last):
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/metrics/views.py", line 124, in find_view
    leaves_only=leaves_only,
  File "/opt/graphite/webapp/graphite/storage.py", line 253, in find
    for match in self._find(query):
  File "/opt/graphite/webapp/graphite/storage.py", line 284, in _find
    for node in result or []:
  File "/opt/graphite/webapp/graphite/finders/remote.py", line 146, in find_nodes
    node = BranchNode(path)
  File "/opt/graphite/webapp/graphite/node.py", line 8, in __init__
    self.name = path.split('.')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
while 0.9.x returned an empty list, which IMHO should be the desired behaviour to keep.

**Comment by deniszh** [comment]
well, technically it's a bug, but I would say empty search string is technically incorrect anyway...

**Comment by deejay1** [comment]
It sort of "breaks" (just an ugly warning) a lot of dashboards in Grafana where there was ![Value groups/tags](https://i.imgur.com/auMJoMy.png) selected, that's why I noticed it. Maybe a HTTP 400 like for the missing parameter would be in order? I only wonder how to properly unit test it :(

**Comment by deniszh** [comment]
Ah, that makes sense. Well, error 400 will also generate a warning in Grafana. We can fix it, should be quite simple fix.

**Comment by deniszh** [comment]
Ah, returning something there is hard - because we need to create proper response for every output format. But proper error message is easy - https://github.com/graphite-project/graphite-web/pull/2295
Not sure will it help with Grafana warning, though

**Comment by deejay1** [comment]
Ok, I think we can close this issue now, I'm ok with a proper error message.
