### ISSUE TITLE
pkg_resources.ResolutionError: No script named 'django-admin.py'

### ISSUE THREAD

**Issue by m2cci-KGY** [graphite-project/graphite-web#2335]
Hi;
I installed graphite in redhat 7.4, I use the Django.1.11.13 like requirement 
so when I make this commande ligne to create the databases : 
 PYTHONPATH=/usr/share/graphite/webapp django-admin syncdb --settings=graphite.settings
I got this error: 
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named graphite.settings

So I read some issues in git 
I make this commande to fix my problem :
PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
so I got another error that's : 

Traceback (most recent call last):
  File "/usr/bin/django-admin.py", line 4, in <module>
    __import__('pkg_resources').run_script('Django==1.11.13', 'django-admin.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'django-admin.py'

someone can help me?
Thank you for your help.

**Comment by piotr1212** [comment]
Where did you find that doc? It should be updated, it now is manage.py instead of graphite-admin.py

**Comment by deniszh** [comment]
According to Google search if `django-admin.py` saying `pkg_resources.ResolutionError: No script named 'django-admin.py'` that means some Django installation error, e.g. mixing different version of Django installed with different ways (e.g. through pip and easy_instyall). I didn't find any solution for that case, though.
But you can try what @piotr1212 said - use `manage.py` or `python -m django` instead - https://docs.djangoproject.com/en/2.1/ref/django-admin/

**Comment by m2cci-KGY** [comment]
I Make this commande : 
]# PYTHONPATH=/usr/share/graphite/webapp manage.py syncdb --settings=graphite.settings
-bash: manage.py: command not found

**Comment by m2cci-KGY** [comment]
]# PYTHONPATH=/usr/share/graphite/webapp manage.py syncdb --settings=graphite.settings
-bash: manage.py: command not found

**Comment by m2cci-KGY** [comment]
PYTHONPATH=/usr/share/graphite/webapp manage.py syncdb --settings=graphite.settings
-bash: manage.py: command not found

**Comment by viper539** [comment]
I tried django-admin (without .py) but then it dies with "ImportError: cannot import name generic" which stackoverflow answer with "The django.contrib.contenttypes module has been reorganized in Django 1.7"
