### ISSUE TITLE
Number only metric names fail in functions

### ISSUE THREAD

**Issue by piotr1212** [graphite-project/graphite-web#2388]
Carbon can create metricnames with numbers only, eg "42" or "42.1". Graphite-web can display them, but as soon as I start using them in functions I get an exception. The problem is with pyparsing parsing function arguments as numbers when they don't contain alphanum characters.

I don't see how to fix this without having to describe all argument types per function and do the parsing based on the function. Which wouldn't be a bad thing but just is a lot of work. As number only metrics names don't make much sense (I just used it for some quick testing) it would be easier to configure some default filters in Carbon so they cannot be created. Like suggested in https://github.com/graphite-project/graphite-web/issues/961

stack trace, reproducible with `&target=diffSeries(40,a)`:
```
Internal Server Error: /render/                                                                                 
Traceback (most recent call last):                                                                                                                                                                                
  File "/home/piotr/venv37/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)                                                                                                                                                                              
  File "/home/piotr/venv37/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)                                                                                                                                                   
  File "/home/piotr/venv37/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                                                       
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/views.py", line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))                                                                                    
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/evaluator.py", line 29, in evaluateTarget                                                                                                  
    result = evaluateTokens(requestContext, target)                                                             
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/evaluator.py", line 59, in evaluateTokens                                                                                                  
    return evaluateTokens(requestContext, tokens.expression, replacements)                                
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/evaluator.py", line 95, in evaluateTokens
    return func(requestContext, *args, **kwargs)                                                                       
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/functions.py", line 531, in diffSeries
    return aggregate(requestContext, seriesLists, 'diff')                                                                                                                                                         
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/functions.py", line 323, in aggregate
    (seriesList, start, end, step) = normalize(seriesList)                                                                                                                                                        
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/functions.py", line 230, in normalize
    seriesList = reduce(lambda L1,L2: L1+L2,seriesLists)                                                                                                                                                          
  File "/home/piotr/venv37/lib/python3.7/site-packages/graphite/render/functions.py", line 230, in <lambda>
    seriesList = reduce(lambda L1,L2: L1+L2,seriesLists)                                                        
TypeError: can only concatenate list (not "int") to list                   
[27/Nov/2018 10:55:00] "GET /render/?width=961&height=587&_salt=1543316100.868&from=-15minutes&target=diffSeries(b%2C40) HTTP/1.1" 500 15436
```

**Comment by deniszh** [comment]
I can't find that in docs now (d-oh), but I definitely remember that somewhere we have a metric description, and then it was mentioned that metric name should start with alphanumeric character.
Agreed that we need to deny it on carbon level.  👍
