### ISSUE TITLE
graphite DB initialization gives: table "django_content_type" already exists

### ISSUE THREAD

**Issue by GowthamShanmugam** [graphite-project/graphite-web#2389]
I have updated graphite-web from:
   graphite-web-0.9.15-1.el7rhgs.noarch
   python-carbon-0.9.15-2.1.el7rhgs.noarch
   python-whisper-0.9.15-1.1.el7rhgs.noarch
   python-django-tagging-0.3.1-11.1.el7rhgs.noarch
   python-django-1.6.11-7.el7rhgs.noarch

to:
    graphite-web-1.1.4-1.el7rhgs.noarch
    python-carbon-1.1.4-1.el7rhgs.noarch
    python-whisper-1.1.4-1.el7rhgs.noarch
    python-django-tagging-0.4.6-1.el7rhgs.noarch
    python2-django-1.11.15-1.el7rhgs.noarch

When I try to initialize DB using the command:
    PYTHONPATH=$GRAPHITE_ROOT/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --settings=graphite.settings --run-syncdb

it gives an error like:
      Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 319, in create_model
    self.execute(sql, params or None)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "django_content_type" already exists

I can avoid this using fake command:

PYTHONPATH=$GRAPHITE_ROOT/webapp/ /usr/lib/python2.7/site-packages/django/bin/django-admin.py migrate --fake --settings=graphite.settings --run-syncdb (is this comamnd is correct?)

But is that correct migration? using fake will migrate completely? and if I use fake command one more time it throws an error(django.db.utils.IntegrityError: django_content_type.name may not be NULL).  
But in a fresh machine I can run migration command anytime it is not giving an error.

How to do migration safely in the machine already have an old version and updated to a new version?

what is the exact command to migrate already existing table in new version?

**Comment by deniszh** [comment]
Exact migration command really depends on source and destination Django and Graphite version, I'm afraid, it will be quite hard to create a really generic solution.
But still open for any suggestions or even PRs.

**Comment by piotr1212** [comment]
I don't think the database can be migrated from 0.9.x to 1.x, You'll probably need to create a new one.

**Comment by GowthamShanmugam** [comment]
what is the migration command actually suggested by graphite-web document ?

**Comment by GowthamShanmugam** [comment]
> Exact migration command really depends on source and destination Django and Graphite version, I'm afraid, it will be quite hard to create a really generic solution.
> But still open for any suggestions or even PRs.

can you please tell me an example? in our database migration is not happening if we use a fake command, old schema remains the same.

**Comment by deniszh** [comment]
That's not a Graphite issue per se, that's a Django issue. `django_content_type` is not specific Graphite table, that's common Django table. So, you need to skip migrations, but not all, just initial - you need to use `--fake-initial` instead of `--fake` - check https://stackoverflow.com/a/29760818/1139639 and https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---fake-initial
