### ISSUE TITLE
manage.py execute failure

### ISSUE THREAD

**Issue by moozhub** [graphite-project/graphite-web#2408]
I'm using the latest version of graphite-web, python-carbon and python-django from the EPEL repo on Centos 7. I'm having issues trying to execute the various scripts that were installed with graphite web. For example, I'm trying to execute manage.py and getting a traceback: 

`Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/graphite/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/graphite/events/models.py", line 6, in <module>
    from tagging.managers import ModelTaggedItemManager
  File "/usr/lib/python2.7/site-packages/tagging/managers.py", line 8, in <module>
    from tagging.models import Tag, TaggedItem
  File "/usr/lib/python2.7/site-packages/tagging/models.py", line 10, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic`

I'm simply following various different tutorials to try to get this up and running but haven't had any success (eg. https://www.server-world.info/en/note?os=CentOS_7&p=graphite)

Installed versions:
 
[root@ns1 graphite-web-0.9.16]# rpm -qa \| grep -E "graphite\|carbon\|django"
python2-django-1.11.13-4.el7.noarch
python-django-tagging-0.3.1-11.el7.noarch
python-carbon-0.9.16-1.el7.noarch
graphite2-1.3.10-1.el7_3.x86_64
graphite-web-0.9.16-2.el7.noarch
python-django-bash-completion-1.11.13-4.el7.noarch

Any ideas?

**Comment by deniszh** [comment]
Graphite 0.9.16 was released in 2015 and it supports Django 1.4 only - https://github.com/graphite-project/graphite-web/blob/0.9.16/requirements.txt#L32
Or donwngrade Django to 1.4 or upgrade Graphite to latest release (1.1.5).

**Comment by moozhub** [comment]
Thanks for the reply. Didn't see the requirements there. Appreciate it.

**Comment by moozhub** [comment]
Thanks for the reply. Didn't see the requirements there. Appreciate it.
