### ISSUE TITLE
graphite.wsgi' cannot be loaded as Python module.

### ISSUE THREAD

**Issue by rufa11** [graphite-project/graphite-web#2442]
Hello,
I installed graphite on Ubuntu 18.04 but i have the following issue:
```
[Fri Apr 12 17:25:59.373128 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446] mod_wsgi (pid=11510): Target WSGI script '/usr/share/graphite-web/graphite.wsgi' cannot be loaded as Python module.
[Fri Apr 12 17:25:59.373165 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446] mod_wsgi (pid=11510): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Fri Apr 12 17:25:59.373198 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446] Traceback (most recent call last):
[Fri Apr 12 17:25:59.373214 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446]   File "/usr/share/graphite-web/graphite.wsgi", line 14, in <module>
[Fri Apr 12 17:25:59.373259 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446]     application = get_wsgi_application()
[Fri Apr 12 17:25:59.373269 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446]   File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Fri Apr 12 17:25:59.373297 2019] [wsgi:error] [pid 11510:tid 140183124670208] [remote 172.16.24.99:59446]     django.setup(set_prefix=False)
...
```

I tried:
- Starting Apache without wsgi.py but the same error.
- Replacing wsgi.py with the following lines but the same error:
```
import sys
# In case of multi-instance graphite, uncomment and set appropriate name
# import os
# os.environ['GRAPHITE_SETTINGS_MODULE'] = 'graphite.local_settings'
sys.path.append('/opt/graphite/webapp')

from graphite.wsgi import application 
``` 

Can someone help please !

**Comment by ploxiln** [comment]
Please include the end of the backtrace, it may provide a good hint about what is wrong.

**Comment by rufa11** [comment]
Hi @ploxiln and thank you for the reply,
here bellow the full error from /var/log/apach2/graphite-web_error.log, i'm running Ubuntu 18.04
```
[Sun Apr 14 23:14:18.673665 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264] mod_wsgi (pid=4639): Target WSGI script '/usr/share/graphite-web/graphite.wsgi' cannot be loaded as Python module.
[Sun Apr 14 23:14:18.673693 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264] mod_wsgi (pid=4639): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Sun Apr 14 23:14:18.673707 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264] Traceback (most recent call last):
[Sun Apr 14 23:14:18.673722 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]   File "/usr/share/graphite-web/graphite.wsgi", line 14, in <module>
[Sun Apr 14 23:14:18.673755 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]     application = get_wsgi_application()
[Sun Apr 14 23:14:18.673773 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]   File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Sun Apr 14 23:14:18.673786 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]     django.setup(set_prefix=False)
[Sun Apr 14 23:14:18.673792 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]   File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
[Sun Apr 14 23:14:18.673808 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]     apps.populate(settings.INSTALLED_APPS)
[Sun Apr 14 23:14:18.673815 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]   File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 78, in populate
[Sun Apr 14 23:14:18.673826 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264]     raise RuntimeError("populate() isn't reentrant")
[Sun Apr 14 23:14:18.673838 2019] [wsgi:error] [pid 4639] [remote 127.0.0.1:47264] RuntimeError: populate() isn't reentrant 
```

**Comment by ploxiln** [comment]
That is more informative ... unfortunately I'm not too familiar with django so I'm not sure how that can happen. Did you install graphite-web (and is dependencies) from the standard ubuntu package repo? If so, I think that would get you graphite-web 1.0.2 and django 1.11.11 ... maybe try installing a newer version with pip?

**Comment by rufa11** [comment]
Thanks for the @ploxiln i will try with pip ad if it works i will post the solution.

**Comment by piotr1212** [comment]
` raise RuntimeError("populate() isn't reentrant")` can basically mean everything. Is there no error message before, or in exception.log?

**Comment by DrHashi** [comment]
This is still happening

**Comment by piotr1212** [comment]
> Is there no error message before, or in exception.log?

**Comment by DrHashi** [comment]
> > Is there no error message before, or in exception.log?

More of the same 
```
[Thu Jul 04 17:57:35.494374 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820] mod_wsgi (pid=25862): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Thu Jul 04 17:57:35.494439 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820] Traceback (most recent call last):
[Thu Jul 04 17:57:35.494457 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
[Thu Jul 04 17:57:35.501931 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     response = self.get_response(request)
[Thu Jul 04 17:57:35.501989 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
[Thu Jul 04 17:57:35.502023 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     response = self._middleware_chain(request)
[Thu Jul 04 17:57:35.502032 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner
[Thu Jul 04 17:57:35.502045 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     response = response_for_exception(request, exc)
[Thu Jul 04 17:57:35.502063 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
[Thu Jul 04 17:57:35.502410 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Thu Jul 04 17:57:35.502437 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
[Thu Jul 04 17:57:35.504633 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     return callback(request, **param_dict)
[Thu Jul 04 17:57:35.504717 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/graphite/views.py", line 11, in server_error
[Thu Jul 04 17:57:35.506686 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     return HttpResponseServerError( template.render(context) )
[Thu Jul 04 17:57:35.506726 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/template/backends/django.py", line 64, in render
[Thu Jul 04 17:57:35.507918 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     context = make_context(context, request, autoescape=self.backend.engine.autoescape)
[Thu Jul 04 17:57:35.507958 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 287, in make_context
[Thu Jul 04 17:57:35.509024 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820]     raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
[Thu Jul 04 17:57:35.509499 2019] [wsgi:error] [pid 25862:tid 140316352075520] [remote 10.1.1.1:53820] TypeError: context must be a dict rather than Context.
[Thu Jul 04 17:57:35.553915 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821] mod_wsgi (pid=25862): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[Thu Jul 04 17:57:35.553989 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821] Traceback (most recent call last):
[Thu Jul 04 17:57:35.554025 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
[Thu Jul 04 17:57:35.554064 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     response = self.get_response(request)
[Thu Jul 04 17:57:35.554105 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
[Thu Jul 04 17:57:35.554144 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     response = self._middleware_chain(request)
[Thu Jul 04 17:57:35.554164 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner
[Thu Jul 04 17:57:35.554182 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     response = response_for_exception(request, exc)
[Thu Jul 04 17:57:35.554190 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
[Thu Jul 04 17:57:35.554211 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Thu Jul 04 17:57:35.554219 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
[Thu Jul 04 17:57:35.554229 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     return callback(request, **param_dict)
[Thu Jul 04 17:57:35.554236 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/graphite/views.py", line 11, in server_error
[Thu Jul 04 17:57:35.554248 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     return HttpResponseServerError( template.render(context) )
[Thu Jul 04 17:57:35.554265 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/template/backends/django.py", line 64, in render
[Thu Jul 04 17:57:35.554276 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     context = make_context(context, request, autoescape=self.backend.engine.autoescape)
[Thu Jul 04 17:57:35.554284 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 287, in make_context
[Thu Jul 04 17:57:35.554299 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821]     raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
[Thu Jul 04 17:57:35.554315 2019] [wsgi:error] [pid 25862:tid 140316368860928] [remote 10.1.1.1:53821] TypeError: context must be a dict rather than Context.
```

**Comment by piotr1212** [comment]
How is that "the same"?

Anyway this message is actually useful. You are using an older graphite version which is not compatible with Django 1.11+. This is fixed in https://github.com/graphite-project/graphite-web/commit/b602664916c0529be0414f441d207562381179e7

Upgrade your Graphite or downgrade Django.

**Comment by DrHashi** [comment]
I don't believe it is the case, my django version is Django==1.11.22

**Comment by piotr1212** [comment]
1.11+ is inclusive, 1.11 and higher.

**Comment by izavyalov** [comment]
Got similar issue with 
* Django VERSION = (1, 9, 12, 'final', 0) 
* graphite VERSION = (1, 1, 5)

At the end issue was about wrong ownership on log files and graphite wouldn't start. 
Similar symptoms and a link to custom wsgi to output full stack of exception:
https://github.com/graphite-project/graphite-web/issues/2046
