### ISSUE TITLE
High CPU usage - 100%

### ISSUE THREAD

**Issue by njchandu** [graphite-project/graphite-web#2454]
Hi,

I'm not savvy with mod_wsgi. Any help is appreciated.

Grafana dashboards query graphite instance via a classic AWS LB.

```
LoadModule wsgi_module modules/mod_wsgi.so
WSGISocketPrefix /var/run/wsgi

Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header set Access-Control-Max-Age "1000"
Header set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"

Listen 8080
<VirtualHost *:8080>

    ServerName graphite
    DocumentRoot /opt/graphite/webapp
    ErrorLog /opt/graphite/storage/log/webapp/error.log
    CustomLog /opt/graphite/storage/log/webapp/access.log common

    WSGIDaemonProcess graphite-web processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120
    WSGIProcessGroup graphite-web
    WSGIApplicationGroup %{GLOBAL}
    WSGIImportScript /opt/graphite/conf/graphite.wsgi process-group=graphite-web application-group=%{GLOBAL}

    WSGIScriptAlias / /opt/graphite/conf/graphite.wsgi

    Alias /static/ /opt/graphite/static/

    <Directory /opt/graphite/static/>
            <IfVersion < 2.4>
                    Order deny,allow
                    Allow from all
            </IfVersion>
            <IfVersion >= 2.4>
                    Require all granted
            </IfVersion>
    </Directory>

    <Directory /opt/graphite/conf/>
            <IfVersion < 2.4>
                    Order deny,allow
                    Allow from all
            </IfVersion>
            <IfVersion >= 2.4>
                    Require all granted
            </IfVersion>
    </Directory>
</VirtualHost>
```
It's super cool that wsgi has many options to mitigate this issue short time, so I'm using cpu-time-limit to mitigate this for now

WSGIDaemonProcess graphite-web processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120 request-timeout=120 cpu-priority=15 cpu-time-limit=120

Restarting httpd solves the issue for sometime though.

I see this error in /opt/graphite/storage/log/webapp/exception.log
```
ValueError: dividendSeriesList and divisorSeriesList argument must have equal length
2019-06-12,16:19:53.132 :: Exception encountered in <POST http://rts-aggregated-graphite.aws.dataxu.net/render>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 88, in evaluateTokens
    args = [evaluateTokens(requestContext, arg, replacements) for arg in rawArgs]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 93, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 1019, in divideSeriesLists
    raise ValueError("dividendSeriesList and divisorSeriesList argument must have equal length")
ValueError: dividendSeriesList and divisorSeriesList argument must have equal length
2019-06-12,16:19:53.282 :: Exception encountered in <POST http://rts-aggregated-graphite.aws.dataxu.net/render>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 88, in evaluateTokens
    args = [evaluateTokens(requestContext, arg, replacements) for arg in rawArgs]
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 93, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 1019, in divideSeriesLists
    raise ValueError("dividendSeriesList and divisorSeriesList argument must have equal length")
```

<img width="969" alt="Screen Shot 2019-06-12 at 12 06 21 PM" src="https://user-images.githubusercontent.com/7442733/59383479-f7af0d00-8d2d-11e9-90e0-da59b6ceea5a.png">

Thanks

**Comment by piotr1212** [comment]
What exactly is your question?

**Comment by njchandu** [comment]
Hi Piotr, apologies for not being clear. The mod_wagi process takes up 100% cpu. I can’t seem to find why.

**Comment by piotr1212** [comment]
Maybe because it is being used?

**Comment by njchandu** [comment]
It’s inconsistent, it spikes up all of a sudden and upon restarting httpd everything works fine for a few hours and then spikes up again.

**Comment by piotr1212** [comment]
Without any users?

**Comment by njchandu** [comment]
With the same amount of users.

**Comment by piotr1212** [comment]
So probably one of your users is sending heavy queries, analyze your apache logs for requests which take a long time.
