### ISSUE TITLE
UnboundLocalError: local variable 'start' referenced before assignment

### ISSUE THREAD

**Issue by Soul-Code** [graphite-project/graphite-web#2481]
Hi,

This problem has recently happened to specific requests which contains 'asPercent'. The request was requested by grafana. And the version of my graphite is 1.1.2.
The bad request looks like:`alias(offset(scale(asPercent(sumSeries(path_to_frontend.frontend_*), path_to_frontend.frontend_request_count, 0), -1), 100), 'frontend_10')`
Details about this:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./graphite/render/views.py", line 117, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "./graphite/render/evaluator.py", line 28, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "./graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "./graphite/render/evaluator.py", line 88, in evaluateTokens
    args = [evaluateTokens(requestContext, arg, replacements) for arg in rawArgs]
  File "./graphite/render/evaluator.py", line 57, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "./graphite/render/evaluator.py", line 93, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "./graphite/render/functions.py", line 899, in asPercent
    resultSeries = TimeSeries(name,start,end,step,resultValues,xFilesFactor=xFilesFactor)
UnboundLocalError: local variable 'start' referenced before assignment
```
Thanks

**Comment by deniszh** [comment]
Hello @Soul-Code ,

Looks like a bug, but please note that 1.1.2 is 18 months old. I would recommend to upgrade to latest version 1.1.5

**Comment by Soul-Code** [comment]
Thanks for your advice.I've just been in charge of this for a few days.I'll upgrade it at once
