### ISSUE TITLE
[BUG] graphite-web strips part of file path after single quote when querying metrics

### ISSUE THREAD

**Issue by invizus** [graphite-project/graphite-web#2544]
**Describe the bug**
Metric stored in whisper under path
`/var/lib/graphite/whisper/collectd/firewall/snmp/if_octets-Adaptive_Security_Appliance_'interface'_interface/tx.wsp`
I can query this with whisper-fetch. But I cannot query this metric in Grafana and Graphite-web interface. 
In log I see query:
`2020-02-21,10:14:12.337 :: graphite.render.datalib.fetchData :: lookup and merge of "collectd.firewall.snmp.if_octets-Adaptive_Security_Appliance_" took 5.43594e-05s`

Was working on graphite-web version 0.9.12+debian-6, carbon version 0.9.12-3

**To Reproduce**
Create and store metrics under directory with single quotes, i.e.
`/var/lib/graphite/whisper/collectd/test2544/snmp/device_'test'_interface/`
copy any .wsp into that directory
try to query in graphite web
monitor logs `/var/log/graphite/info.log`

**Expected behavior**
graphite-web will retrieve metrics and display graph.

**Environment (please complete the following information):**
 - OS flavor: Debian 10
 - Graphite-web version 1.1.4-3+deb10u1
 - Django/Python version python3-django/stable,now 1:1.11.28-1~deb10u1
 - Setup type from official Debian repository

**Comment by deniszh** [comment]
Hi @invizus,

Did you try to escape quote character with backslash during querying ?

**Comment by invizus** [comment]
@deniszh yes, that works for me. I will be fine with it.

**Comment by deniszh** [comment]
Cool, thanks for checking! I understand that's not ideal, though.

**Comment by dimonoid** [comment]
Similar issue in dashboard.
Unable to use function applyByNode(matric*,1,"function('here')") , in 3rd argument between double quotes sometimes needs to be single quote as double quotes inside double quotes cause an error. Works in main UI, but fails in dashboard (single quotes are automatically replaced with double quotes).

From /var/log/graphite/exception.log

Traceback (most recent call last):
  File "/opt/graphite/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/errors.py", line 101, in new_f
    return f(*args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 130, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 34, in evaluateTarget
    result = evaluateTokens(requestContext, target)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 67, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, replacements)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 120, in evaluateTokens
    return func(requestContext, *args, **kwargs)
  File "/opt/graphite/webapp/graphite/render/functions.py", line 5109, in applyByNode
    for resultSeries in evaluateTarget(newContext, templateFunction.replace('%', prefix)):
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 18, in evaluateTarget
    pathExpressions = extractPathExpressions(requestContext, targets)
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 200, in extractPathExpressions
    target = grammar.parseString(target)
  File "/opt/graphite/webapp/graphite/render/grammar.py", line 12, in parseString
    return _grammar.parseString(instring)
  File "/opt/graphite/lib/python3.9/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/opt/graphite/lib/python3.9/site-packages/pyparsing/core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: , found "'"  (at char 0), (line:1, col:1)
