### ISSUE TITLE
[BUG] `round` function adds numeric tag, breaks `aliasByTags`

### ISSUE THREAD

**Issue by shanson7** [graphite-project/graphite-web#2571]
**Describe the bug**

[round](https://github.com/graphite-project/graphite-web/blob/de2592d/webapp/graphite/render/functions.py#L1688) adds the precision as a number. If you go on to use `aliasByTags` it returns error:

```
Traceback (most recent call last): 
 File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner response = get_response(request)
 File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response response = self.process_exception_by_middleware(e, request)
 File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/opt/graphite/webapp/graphite/render/views.py", line 117, in renderView data.extend(evaluateTarget(requestContext, targets))
 File "/opt/graphite/webapp/graphite/render/evaluator.py", line 28, in evaluateTarget result = evaluateTokens(requestContext, target)
 File "/opt/graphite/webapp/graphite/render/evaluator.py", line 57, in evaluateTokens return evaluateTokens(requestContext, tokens.expression, replacements)
 File "/opt/graphite/webapp/graphite/render/evaluator.py", line 93, in evaluateTokens return func(requestContext, *args, **kwargs)
 File "/opt/graphite/webapp/graphite/render/functions.py", line 5169, in aliasByTags return aliasByNode(requestContext, seriesList, *tags)
 File "/opt/graphite/webapp/graphite/render/functions.py", line 2376, in aliasByNode series.name = aggKey(series, nodes, pathExpression)
 File "/opt/graphite/webapp/graphite/render/functions.py", line 195, in aggKey return '.'.join([getNodeOrTag(series, n, pathExpression) for n in nodes]) TypeError: sequence item 0: expected string, int found
```

**To Reproduce**
Described above

**Expected behavior**
I think tags should have string values, but not sure if this is enforced elsewhere (e.g. on ingestion)

**Environment (please complete the following information):**
 - OS flavor: [e.g. Ubuntu, CentOS, Debian etc]: CentOS
 - Graphite-web version [e.g. 1.1.2, 1.0.1, etc]: 1.1.5
 - Django/Python version [e.g. 1.11/2.7, 2.1/3.8 etc]
 - Setup type [e.g. pip, from sources, from OS packages etc]

**Comment by DanCech** [comment]
Good catch, it should be set as a string.
