### ISSUE TITLE
[Q] ImportError: No module named graphite.settings

### ISSUE THREAD

**Issue by kix23** [graphite-project/graphite-web#2575]
Issue while installing graphite-web
First some system Informations:
Running on raspberry3 with Raspbian GNU/Linux 10 (buster)
uname -a
`Linux graphitesrv 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux`
Graphite versions (simply installed with apt install):
```
graphite-carbon 1.1.4-2
graphite-web 1.1.4-3+deb10u1
```
django versions (also apt install):
python3-* was installed as dependency with graphite-web
```
python-django                        1:1.11.28-1~deb10u1
python-django-common                 1:1.11.28-1~deb10u1
python-django-tagging                1:0.4.5-1
python3-django                       1:1.11.28-1~deb10u1
python3-django-tagging               1:0.4.5-1
```
/etc/graphite/local_settings.py
```
SECRET_KEY = 'isetsomethinghere'
TIME_ZONE = 'Europe/Berlin'
LOG_ROTATION = False
DEFAULT_XFILES_FACTOR = 0
GRAPHITE_ROOT = '/usr/share/graphite-web'
CONF_DIR = '/etc/graphite'
STORAGE_DIR = '/var/lib/graphite/whisper'
STATIC_ROOT = '/usr/share/graphite-web/static'
LOG_DIR = '/var/log/graphite'
INDEX_FILE = '/var/lib/graphite/search_index'
WHISPER_DIR = '/var/lib/graphite/whisper'
DATABASES = {
    'default': {
        'NAME': 'graphitedb',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'graphitedbuser',
        'PASSWORD': 'graphitedbpass',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}
FUNCTION_PLUGINS = []
``````

db got populated via:
(no migrations to apply here bec already did.)
```
root@graphitesrv:~# django-admin migrate --settings=graphite.settings --run-syncdb
Operations to perform:
  Synchronize unmigrated apps: browser, composer, functions, metrics, render, staticfiles, whitelist
  Apply all migrations: account, admin, auth, contenttypes, dashboard, events, sessions, tagging, tags, url_shortener
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
root@graphitesrv:~# graphite-manage migrate
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, dashboard, events, sessions, tagging, tags, url_shortener
Running migrations:
  No migrations to apply.
```
notice: graphite.service works here.

db seems ok:
```
+----------------------------+
| Tables_in_graphitedb         |
+----------------------------+
| account_mygraph            |
| account_profile            |
| account_variable           |
| account_view               |
| account_window             |
| auth_group                 |
| auth_group_permissions     |
| auth_permission            |
| auth_user                  |
| auth_user_groups           |
| auth_user_user_permissions |
| dashboard_dashboard        |
| dashboard_dashboard_owners |
| dashboard_template         |
| dashboard_template_owners  |
| django_admin_log           |
| django_content_type        |
| django_migrations          |
| django_session             |
| events_event               |
| tagging_tag                |
| tagging_taggeditem         |
| tags_series                |
| tags_seriestag             |
| tags_tag                   |
| tags_tagvalue              |
| url_shortener_link         |
+----------------------------+
```
Webserver gives a "500 - Internal Server Error"
apache config:
```
<VirtualHost *:8003>
	WSGIDaemonProcess _graphite processes=5 threads=5 display-name='%{GROUP}' inactivity-timeout=120 user=_graphite group=_graphite
	WSGIProcessGroup _graphite
	WSGIImportScript /usr/share/graphite-web/graphite.wsgi process-group=_graphite application-group=%{GLOBAL}
	WSGIScriptAlias / /usr/share/graphite-web/graphite.wsgi
	Alias /static/ /usr/share/graphite-web/static/
	<Location "/static/">
		SetHandler None
	</Location>
	ErrorLog ${APACHE_LOG_DIR}/graphite-web_error.log
	LogLevel warn
	CustomLog ${APACHE_LOG_DIR}/graphite-web_access.log combined
</VirtualHost>

```
Webserver graphite-web_error.log:
```
[wsgi:error] mod_wsgi (pid=3528): Failed to exec Python script file '/usr/share/graphite-web/graphite.wsgi'.
[wsgi:error] mod_wsgi (pid=3528): Exception occurred processing WSGI script '/usr/share/graphite-web/graphite.wsgi'.
[wsgi:error] Traceback (most recent call last):
[wsgi:error]    File "/usr/share/graphite-web/graphite.wsgi", line 14, in <module>
[wsgi:error]      application = get_wsgi_application()
[wsgi:error]    File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[wsgi:error]      django.setup(set_prefix=False)
[wsgi:error]    File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
[wsgi:error]      configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[wsgi:error]    File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[wsgi:error]      self._setup(name)
[wsgi:error]    File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[wsgi:error]      self._wrapped = Settings(settings_module)
[wsgi:error]    File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
[wsgi:error]      mod = importlib.import_module(self.SETTINGS_MODULE)
[wsgi:error]    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[wsgi:error]      __import__(name)
[wsgi:error] ImportError: No module named graphite.settings
```
my guess is, that the installed packages use different python versions
in the log python2.7 is called
but if i search for graphite.service it only appears in some python3 binary files:
```
/usr/lib/python3/dist-packages/graphite/__pycache__/wsgi.cpython-37.pyc
/usr/lib/python3/dist-packages/graphite/__pycache__/settings.cpython-37.pyc
```
and as mentioned above no error was thrown by `django-admin migrate`

i'm not good in python and also this django thing is new for me.
i just want to run graphite for my icinga dashboard.
so still hoping its just a simple config issue.

**Comment by deniszh** [comment]
According to https://packages.debian.org/buster/graphite-web Graphite in Debian 10 indeed built against Python 3. So, please configure Apache to use mod_wsgi 3 instead of mod_wsgi. IIRC you need to install `libapache2-mod-wsgi-py3` and remove `libapache2-mod-wsgi` for that.
Also, you need to provide proper path to  `WSGIDaemonProcess` (e.g. `WSGIDaemonProcess graphiteweb python-path=/etc/graphite:/usr/local/lib/python3.6/dist-packages processes=5 ...`) but probably it will work automatically.

**Comment by deniszh** [comment]
Or you can use Docker, latest release has ARM version - https://github.com/graphite-project/docker-graphite-statsd

**Comment by deniszh** [comment]
Or you can peek at https://github.com/obfuscurity/synthesize/pull/79 - it's for Ubuntu 18, but should work for Debian 10 too.

**Comment by kix23** [comment]
installing `libapache2-mod-wsgi-py3` was the simple solution i hoped for!
thank you very much @deniszh !
