### ISSUE TITLE
[Q] Directory is not created when following the Pip install method

### ISSUE THREAD

**Issue by itinneed2022** [graphite-project/graphite-web#2760]
Following the pip install, and working on the initial configuration [webapp database setup,](https://graphite.readthedocs.io/en/stable/config-database-setup.html) I'm running into an issue where the folders were not created after running the pip install commands:

(graphite) [root@graphite1 graphite]# PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin.py migrate --settings=graphite.settings
Could not import graphite.local_settings, using defaults!
/opt/graphite/lib/python3.6/site-packages/graphite/settings.py:360: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
Traceback (most recent call last):
  File "/opt/graphite/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/opt/graphite/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/graphite/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/graphite/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/graphite/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/graphite/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/graphite/lib/python3.6/site-packages/graphite/functions/__init__.py", line 9, in <module>
    from graphite.functions.params import Param, ParamTypes, ParamTypeAggFunc  # noqa
  File "/opt/graphite/lib/python3.6/site-packages/graphite/functions/params.py", line 3, in <module>
    from graphite.errors import InputParameterError
  File "/opt/graphite/lib/python3.6/site-packages/graphite/errors.py", line 2, in <module>
    from graphite.logger import log
  File "/opt/graphite/lib/python3.6/site-packages/graphite/logger.py", line 96, in <module>
    log = GraphiteLogger() # import-shared logger instance
  File "/opt/graphite/lib/python3.6/site-packages/graphite/logger.py", line 29, in __init__
    level = logging.DEBUG if settings.DEBUG else logging.INFO,
  File "/opt/graphite/lib/python3.6/site-packages/graphite/logger.py", line 68, in _config_logger
    handler = Rotater(log_file, when=when, backupCount=backupCount)
  File "/usr/lib64/python3.6/logging/handlers.py", line 202, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib64/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/graphite/lib/python3.6/storage/log/webapp/info.log'

Is there a step between the initial database setup and the pip install that I missed? This is just a centos 7 node.

**Comment by itinneed2022** [comment]
@deniszh That sounds like a step I missed somewhere.

**Comment by deniszh** [comment]
it should not be mandatory, default should be /opt/graphite - but it's not working for some reason on your system.

**Comment by itinneed2022** [comment]
I also have tried the from source version and it also fails on this step.
