### ISSUE TITLE
go-carbon stopping to pull metrics and showing below erroe

### ISSUE THREAD

**Issue by Prasadevops0710** [graphite-project/graphite-web#2770]
go-carbon stopped to show metrics and showing below error everytime I need to restart go-carbon service to work fine can u please help regarding this @deniszh 

Jul 28 01:06:03 ip-10-0-250-82 sh[16094]:     os.rename(self.baseFilename, dfn)
Jul 28 01:06:03 ip-10-0-250-82 sh[16094]: OSError: [Errno 2] No such file or directory
Jul 28 01:06:03 ip-10-0-250-82 sh[16094]: Logged from file logger.py, line 88
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]: Traceback (most recent call last):
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]:   File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]:     self.doRollover()
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]:   File "/usr/lib/python2.7/logging/handlers.py", line 350, in doRollover
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]:     os.rename(self.baseFilename, dfn)
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]: OSError: [Errno 2] No such file or directory
Jul 28 01:56:37 ip-10-0-250-82 sh[16094]: Logged from file logger.py, line 88

**Comment by Prasadevops0710** [comment]
please help @deniszh its production server

**Comment by Prasadevops0710** [comment]
s
