### ISSUE TITLE
Error response 504 from http://graphite-jp.knorex-internal.com:80/render/?

### ISSUE THREAD

**Issue by Prasadevops0710** [graphite-project/graphite-web#2771]
I'M GETTING THIS ERROR AND GRAFANA DASHBOARD SHOWING `QUERY ERROR : 504 GATEWAY TIMEOUT " BUT  after refreshing page grafana dashboard is showing metrics but we need to do refresh mostof the time to see dashboard please help @deniszh 

Exception: Error response 504 from http://graphite-sea.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
2022-08-03,06:22:46.301 :: RemoteFinder[graphite-jp.knorex-internal.com:80] Error response 504 from http://graphite-jp.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/remote.py", line 63, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/data/graphite/webapp/graphite/finders/remote.py", line 266, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 504 from http://graphite-jp.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
2022-08-03,06:22:46.301 :: Failed after 2 attempts! Root cause:
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/remote.py", line 63, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/data/graphite/webapp/graphite/finders/remote.py", line 266, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 504 from http://graphite-sea.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/remote.py", line 63, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/data/graphite/webapp/graphite/finders/remote.py", line 266, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 504 from http://graphite-sea.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
2022-08-03,06:22:46.302 :: Failed after 2 attempts! Root cause:
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/remote.py", line 63, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/data/graphite/webapp/graphite/finders/remote.py", line 266, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 504 from http://graphite-jp.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745
Traceback (most recent call last):
  File "/data/graphite/webapp/graphite/readers/remote.py", line 63, in fetch_multi
    timeout=settings.FETCH_TIMEOUT,
  File "/data/graphite/webapp/graphite/finders/remote.py", line 266, in request
    raise Exception("Error response %d from %s" % (result.status, url_full))
Exception: Error response 504 from http://graphite-jp.knorex-internal.com:80/render/?format=pickle&local=1&noCache=1&from=1659421345&until=1659507745&target=ai.optimiser.summary.global.ai_num_adgroups&now=1659507745

**Comment by Prasadevops0710** [comment]
here is the screenshot of grafana
<img width="1440" alt="Screenshot 2022-08-03 at 12 01 15 PM" src="https://user-images.githubusercontent.com/97157679/182539751-fe73317a-b1b3-454b-8664-0b32bcbb2de6.png">
)

**Comment by Prasadevops0710** [comment]
hi @deniszh  please help here thanks in advance

**Comment by deniszh** [comment]
Hi @Prasadevops0710 
You have issues with your cluster, but which exactly - it's hard to say. Logs above only says that it tries to call host http://graphite-jp.knorex-internal.com and instead of result it returns 504 error. You need to login to this host (or clusters behind this host) and check errors there.
