### ISSUE TITLE
[Q] Unexpected token error

### ISSUE THREAD

**Issue by heejeongMin** [graphite-project/graphite-web#2775]
Just installed Graphite using homebrew. 
Installation was done without error, and followed the step here to authenticate. 
https://docs.graphite.dev/guides/graphite-cli/authenticating-the-cli

however any commands using gt gives me the following error. Tried to unstalled and reinstalled also but seems it is same. 
What should be done to solve this error ? tried to google it but didn't really get the right answer. 

Xcode version : 13.4.1
MacOs : Monterey 12.5.1
Installed graphite : v0.20.10.zip

```
/usr/local/Cellar/graphite/0.20.10/libexec/lib/node_modules/@withgraphite/graphite-cli/dist/src/background_tasks/post_traces.js:38
                auth: user_config_spf_1.userConfigFactory.loadIfExists()?.data.authToken,
                                                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/Cellar/graphite/0.20.10/libexec/lib/node_modules/@withgraphite/graphite-cli/dist/src/index.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by deniszh** [comment]
Hi @heejeongMin 

Wrong repo. You're using https://graphite.dev/ but this repo is about https://graphiteapp.org/
