### ISSUE TITLE
UTF8  proble

### ISSUE THREAD

**Issue by anch665** [graphite-project/graphite-web#2790]
**Get ERROR UTF8**
i'm uncomment UTF8_METRICS = True in webapp/graphite/local_settings.py
but i get errol

2022-12-07,18:06:27.654 :: Failed CarbonLink query 'RTM.PROD.server3.nbo2.choice.offers.dynamic.segment.NBO_APP.BANNER.RTM_FINANCE_1.CAMP1017348.3827_ММ_Obeschanniy_platezh.273004.count'
Traceback (most recent call last):
  File "/sas/graphite/webapp/graphite/readers/utils.py", line 110, in merge_with_carbonlink
    cached_datapoints = CarbonLink().query(metric)
  File "/sas/graphite/webapp/graphite/carbonlink.py", line 96, in query
    results = self.send_request(request)
  File "/sas/graphite/webapp/graphite/carbonlink.py", line 142, in send_request
    log.cache("CarbonLink finished receiving %s from %s" % (str(metric), str(host)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 115-116: ordinal not in range(128)
where ММ - is russian symbol whith code 1052

2022-12-07,16:15:12.025 :: Failed CarbonLink query 'collectd.PROD.server6.RtdmByPerl.1243____Приглашение_в_кампанию.gauge'
Traceback (most recent call last):
  File "/sas/graphite/webapp/graphite/readers/utils.py", line 110, in merge_with_carbonlink
    cached_datapoints = CarbonLink().query(metric)
  File "/sas/graphite/webapp/graphite/carbonlink.py", line 96, in query
    results = self.send_request(request)
  File "/sas/graphite/webapp/graphite/carbonlink.py", line 142, in send_request
    log.cache("CarbonLink finished receiving %s from %s" % (str(metric), str(host)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 69-79: ordinal not in range(128)
where 1243____Приглашение_в_кампанию.gauge - russian string in UTF8

**Environment (please complete the following information):**
 - OS flavor: CentOS
 - Graphite-web version 1.1.10
 - Django/Python version [e.g. 1.11/2.7, 2.1/3.8 etc]
 - Setup type from sources

**Additional context**

**Comment by deniszh** [comment]
Yes, looks like a bug. All `str()` where string can be UTF8 in [log.cache](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/carbonlink.py) should be replaced with `encode('utf-8')` 
Could you please check does LOG_CACHE_PERFORMANCE=False in local_settigs.py fixing the issue?

**Comment by anch665** [comment]
Денис, надеюсь вы не обидитесь на русский язык. включение LOG_CACHE_PERFORMANCE=False в  local_settings.py проблему не исправляет

Что интересно без включения опции UTF8_METRICS = True  метрики collectd.PROD.server6.RtdmByPerl.1243____Приглашение_в_кампанию.gauge отображает в графане, а при отображении RTM.PROD.server3.nbo2.choice.offers.dynamic.segment.NBO_APP.BANNER.RTM_FINANCE_1.CAMP1017348.3827_ММ_Obeschanniy_platezh.273004.count пишет ошибку
