### ISSUE TITLE
Sporadic exception - datalib.py in fetchData

### ISSUE THREAD

**Issue by syepes** [graphite-project/graphite-web#282]
Hello,

Recently I have noticed that we are getting the same sporadic exception:

/opt/graphite/storage/log/webapp/exception.log

```
Mon Apr 08 16:18:36 2013 :: Exception Caught
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 230, in fetchData
    cachedResults = CarbonLink.query(dbFile.real_metric)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 139, in query
    results = self.send_request(request)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 165, in send_request
    result = self.recv_response(conn)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 177, in recv_response
    len_prefix = recv_exactly(conn, 4)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 190, in recv_exactly
    data = conn.recv( num_bytes - len(buf) )
timeout: timed out
```

Anyone know what could be causing this exception?

We are running the off the 0.9.x branch.

Best regards,
Sebas

**Comment by stevebanik** [comment]
I have increased CARBONLINK_TIMEOUT to 30.0 and I'm still seeing the timeout in datalib.py.  'iostat' shows my RAID5 SSD %util at about 98% at all times.  I have 98GB of RAM.  Are there any tips/tricks on how to effectively balance in-memory vs on-disk reads, writes and lookups?
