### ISSUE TITLE
Running carbon gives the AttributeError: 'module' object has no attribute 'CAN_FALLOCATE'

### ISSUE THREAD

**Issue by murtazavf** [graphite-project/graphite-web#426]
Hi need help running the carbon. When i issue the following command:

 /opt/graphite/bin/carbon-cache.py start

It throws the following exception and carbon does not start. Please help in this regard:

/usr/lib/python2.7/dist-packages/zope/**init**.py:3: UserWarning: Module twisted was already imported from /usr/local/lib/python2.7/dist-packages/twisted/**init**.pyc, but /opt/graphite/lib is being added to sys.path
  import pkg_resources
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(**file**)
  File "/opt/graphite/lib/carbon/util.py", line 94, in run_twistd_plugin
    config.parseOptions(twistd_options)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 614, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 266, in parseOptions
    self.subOptions.parseOptions(rest)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/usage.py", line 276, in parseOptions
    self.postOptions()
  File "/opt/graphite/lib/carbon/conf.py", line 221, in postOptions
    if whisper.CAN_FALLOCATE:
AttributeError: 'module' object has no attribute 'CAN_FALLOCATE'

**Comment by susampath** [comment]
@frejsoya could you please tell me how to update whispher

**Comment by deniszh** [comment]
It really depends on how it was installed, @susampath

**Comment by susampath** [comment]
Thnk you very much


On 26 Jul 2017 12:58 pm, "Denis Zhdanov" <notifications@github.com> wrote:

It really depends on how it was installed, @susampath
<https://github.com/susampath>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/graphite-project/graphite-web/issues/426#issuecomment-317972055>,
or mute the thread
