### ISSUE TITLE
(master only) Unable to fetch from remote servers

### ISSUE THREAD

**Issue by bmhatfield** [graphite-project/graphite-web#987]
```
Sun Oct 12 01:34:40 2014 :: Error requesting http://10.144.251.222:8180/render/?target=stats_counts.worker.blahblahlsfljljdf&format=pickle&local=1&noCache=1&from=1413090280&until=1413092080
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 181, in wait_for_results
    response = connection.getresponse()
NameError: free variable 'connection' referenced before assignment in enclosing scope
Sun Oct 12 01:34:40 2014 :: Failed to complete subfetch
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers.py", line 52, in fetch
    results[i] = result.waitForResults()
  File "/opt/graphite/webapp/graphite/readers.py", line 29, in waitForResults
    return self.wait_callback()
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 207, in extract_my_results
    for series in wait_for_results():
  File "/opt/graphite/webapp/graphite/remote_storage.py", line 181, in wait_for_results
    response = connection.getresponse()
NameError: free variable 'connection' referenced before assignment in enclosing scope
```

Noting `NameError: free variable 'connection' referenced before assignment in enclosing scope`, This appears to be the result of a very old (2012) merge - and I don't see how the code could have worked since that merge >2y ago.

**Comment by beevee** [comment]
I had the same problem, and it disapperead after I switched gunicorn from gevent back to default sync workers. I don't feel very inclined to debug gevent-related problems, but maybe somebody else is.

**Comment by obfuscurity** [comment]
@bmhatfield do you know if this is still valid?
